### ISSUE TITLE
Improve concurrent traffic and access response speed

### ISSUE THREAD

**Issue by zoujiali1996** [opencv/cvat#4682] opened 2022-06-09 03:49 UTC
When more than five accounts are accessed at the same time, the system crashes frequently and cannot save the annotation result. The annotation result disappears after refreshing

**Comment by zhiltsov-max** [comment] 2022-10-25 17:30
Hi. Please check if the server has enough RAM, the problem sounds like the server can be crashing for being out of memory. I'll close the issue, feel free to reopen if the problem is still actual. Please also try to upgrade the server to the latest version.

**Closed by zhiltsov-max** 2022-10-25 17:30 UTC
