### ISSUE TITLE
 Remotely accessing tool outside LAN

### ISSUE THREAD

**Issue by PavneshYadav123** [opencv/cvat#1021] opened 2020-01-02 06:55 UTC
@nmanovic 
i want to execute CVAT on my website 
i have done following changes on 
### 1)changes in [base.py](https://github.com/PavneshYadav123/Cvat/blob/master/base.py)  
    **line no 28:**
                  ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 
                                        'localhost,127.0.0.1,labelytics.trantorglobal.com').split(',')
    **line no 188 to 200:**
                  UI_WITHOUT_PORT = UI_URL
                  CORS_ORIGIN_WHITELIST = [UI_URL, UI_WITHOUT_PORT]
  
### 2)Changes in [Docker-compose.yml](https://github.com/PavneshYadav123/Cvat/blob/master/docker-compose.yml)
    **added new code line no 56**
            ALLOWED_HOSTS: '*'
    **line no 58** 
            UI_HOST: labelytics.trantorglobal.com
    **line no 81** 
            REACT_APP_API_HOST: labelytics.trantorglobal.com
### 3)Changes in [react_nginx.conf ](https://github.com/PavneshYadav123/Cvat/blob/master/react_nginx.conf)
   **added new code line no 6**
                add_header Access-Control-Allow-Origin "*";

if i am giving UI_HOST and REACT_APP_API_HOST as IP address insted of URL it is workig fine but it is not working on URL what should i do 
I have attach all file along with server and URL 
Please suggest me

**Comment by bsekachev** [comment] 2020-01-09 06:25
@PavneshYadav123 

Hi, 
Now I can go to URL you specified and get access to your instance of CVAT. 
At least login page works fine. The issue is relevant?

**Comment by PavneshYadav123** [comment] 2020-01-09 14:26
@bsekachev i have hosted tool on my site

**Comment by bsekachev** [comment] 2020-01-10 08:28
@PavneshYadav123 
I suppose you have solved the issue.
So, I'll close it for now. Don't hesitate reopen it if you have a question

**Closed by bsekachev** 2020-01-10 08:28 UTC
Labels: question
