### ISSUE TITLE
Can track between jobs?

### ISSUE THREAD

**Issue by mfdefs** [opencv/cvat#4756] opened 2022-07-15 02:10 UTC
I found track mode only enable in one job.
Except track shape can exist in last jobs.

**Comment by nmanovic** [comment] 2022-07-15 03:33
@mfdefs , It is not enough information to understand the problem. Could you please share steps to reproduce?

**Comment by mfdefs** [comment] 2022-07-15 04:07
job1 and job2 in the same task;
1.add a shape a in track mode at job1;
2.expcept the tracked shape a exist in  job2;

**Comment by bsekachev** [comment] 2022-08-21 11:52
Create a task with non-zero ``overlap`` parameter. See documentation for more details.  
You can annotate job1, then open job2 and annotate the same overlapped frames. You will not see annotated tracks from job1 because it might be invalid from point of view permission system. 
But when you dump annotations for a task, they will be merged to one track.

**Closed by bsekachev** 2022-08-21 11:52 UTC
