### ISSUE TITLE
Task creation with video file and divide the frames to several jobs using API endpoints

### ISSUE THREAD

**Issue by RKAnonymous** [opencv/cvat#5814] opened 2023-03-07 11:04 UTC
I have several 2-3 minutes of videos and I am going to automate the process of task creation as well as having frames divided to several jobs in a single task.

Tried to use API endpoints: 
1. https://app.cvat.ai/api/docs/#tag/tasks/operation/tasks_create
2. https://app.cvat.ai/api/docs/#tag/tasks/operation/tasks_create_data

As I understand:
the 1st one create kind of a template for a task with meta data, the 2nd attaches files to that task

I managed to create an empty task using 1st endpoint, but stack at the 2nd without lack of information in the docs about how to upload video file.

Also, I tried to mimic the process observing UI(Inspect-Network) how this functionality was handled in UI, but again could not understand the format of the uploaded files in requests.

Please give any suggestions of yours
![image](https://user-images.githubusercontent.com/104907216/223404265-ddb372da-12f1-4635-bec3-94b28325289c.png)
![image](https://user-images.githubusercontent.com/104907216/223404402-9de78c2f-cdd0-43d6-915f-b83c83bf306e.png)

Cannot understand the "job_file_mapping" field. Generally how files will be uploaded without attaching any image/video physically, but only by names in json.

**Comment by bsekachev** [comment] 2023-03-13 10:41
Hi @RKAnonymous 

I can suggest you to create a task via a browser and in dev console on ``Network`` tab you can see all requests happen.

**Comment by zhiltsov-max** [comment] 2023-03-13 20:52
Hi.

> As I understand:
the 1st one create kind of a template for a task with meta data, the 2nd attaches files to that task

Yes, you understand the endpoints correctly. The first one creates an empty task with specified parameters and the second one allows to upload files to the task with one or multiple requests. You can specify job split parameters in the first request.

If you want to specify a custom split, please look at [this API test](https://github.com/opencv/cvat/blob/develop/tests/python/rest_api/test_tasks.py#L858-L899) which creates a task with custom file-job separation. Currently, it supports only images, not video. We're open for feature requests - feel free to ask if you need this.

**Comment by zhiltsov-max** [comment] 2023-03-22 11:25
Hi, I will close the issue. Please feel free to ask more questions and reopen in the case the problem is not resolved. Please also check [this answer](https://github.com/opencv/cvat/issues/5847#issuecomment-1468564437) if there are difficulties with file uploading.

**Closed by zhiltsov-max** 2023-03-22 11:25 UTC
Labels: question
