### ISSUE TITLE
Noticeable lag when working with images that have a large amount of annotations

### ISSUE THREAD

**Issue by Errin890** [opencv/cvat#4945] opened 2022-09-13 18:49 UTC
This issue is duplicate of #3875 
It has been a year since this issue has had any response, I was wondering if there is any update on the matter?
I regularly deal with images that require thousands of labels and after about 600-800 there is a noticeable lag between every single action (selection, creation, deletion, resizing, moving, etc.), sometimes as a large as whole seconds.
As of this moment, I use the latest version in the develop branch.

This issue template is closely related to @WiktorAdamczyk1 's template in the original issue.

### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)
- [x] Tried both the local and web versions
- [x] Tried different browsers (Chrome, Brave, Opera, etc.)

### Expected Behaviour

UI should be able to handle a large number of annotations on a single image without making every action delayed.

### Current Behaviour

Loading an image with hundreds or thousands of annotations takes a long time to load, sometimes resulting in many 'page unresponsive' prompts. Any action on the image is also incredibly delayed (selection, creation, deletion, editing, etc.).

### Possible Solution

It seems that the application lags on a larger number of annotations as every action involves a reload/recheck/redraw of everything on the image. Perhaps only update newly created/edited/deleted annotations with each action.
The possible solution brought about in the original issue may also work as well.

### Steps to Reproduce (for bugs)

Loading an image:
1. Load an image with thousands of annotations.
2. Create/edit/delete an annotation

When annotating a new image:
1. Create enough annotations (my application starts lagging around 600-800 annotations)
2. Create/edit/delete an annotation

### Context

I deal with images that require a lot of annotations in the form of bounding boxes, as there are many objects that need to be labelled within the image.

### Your Environment

- Git hash commit (`git log -1`):

C:\Users\Errin\Documents\work\projects\cvat>git log -1
commit 9f89787f95504474b154974c7ec6087dd13149dd (HEAD -> develop, origin/develop, origin/HEAD)
Author: Maria Khrustaleva <maya17grd@gmail.com>
Date:   Tue Sep 13 11:39:43 2022 +0200

    Source & target storage support (#4842)

- Docker version `docker version` (e.g. Docker 17.0.05):

Docker 20.10.17

- Are you using Docker Swarm or Kubernetes?

No.

- Operating System and version (e.g. Linux, Windows, MacOS):

Windows 10

- Code example or link to GitHub repo or gist to reproduce problem:

None

- GPU: NVIDIA GeForce GTX 1070
- CPU: Intel(R) Core(TM) i7-8750H
- RAM: 16GB

**Comment by bsekachev** [comment] 2022-09-15 06:34
Hi, that is true.

UI performance needs to be optimized. We remember about the issue, but currently we do not have enough resources to work on it. 

I will close the issue as a duplicate of #3875

**Closed by bsekachev** 2022-09-15 06:34 UTC
