### ISSUE TITLE
"No media data found" when trying to create a task via SDK

### ISSUE THREAD

**Issue by julled** [opencv/cvat#5230] opened 2022-11-03 19:07 UTC
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I want to create a task including a file from shared disk via the SDK, but i receive a error that the file is not found:
> Error: Request failed with status code 500. "ValueError: No media data found\n".

### Expected Behaviour

The Task should be created

### Current Behaviour

No task creation possible.

### Possible Solution

I think there is a error in the shared files implementation.
Could it be that there is  a error in the file path generation with the Quotation marks as seen in the log of the buttom of the issue ? Looks suspicous to me, but beside the quotation marks the path would be correct.

### Steps to Reproduce (for bugs)
1. Create a uploader script
```
from cvat_sdk import make_client, models
from cvat_sdk.core.proxies.tasks import ResourceType, Task

user="xxx"
pw="xxx"
host="xxx"

# Create a Client instance bound to a local server and authenticate using basic auth
with make_client(host=host, credentials=(user, pw), port=8080) as client:
    # Let's create a new task.

    # Fill in task parameters first.
    # Models are used the same way as in the layer 1.
    task_spec = {
        "name": "example task",
        "labels": [
            {
                "name": "car",
                "color": "#ff00ff",
                "attributes": [
                    {
                        "name": "a",
                        "mutable": True,
                        "input_type": "number",
                        "default_value": "5",
                        "values": ["4", "5", "6"],
                    }
                ],
            }
        ],
    }
    oneFile ="flightdata/2022-08-13T09-00-00-payload-images-helgoland/cam-l/2022-06-15T08-21-49.975755.jpg" # i am not 100perc sure about this, but i created a task via UI including this file and used the shared folder path which was shown in UI on the top
    task = client.tasks.create_from_data(
        spec=task_spec,
        resource_type=ResourceType.SHARE,
        resources=[oneFile]
    )
    
```
1. Run the script
1. Response:
```
(cvat) xxx@asfasf:~/cvat_task_creator$ python3 creator.py 
Traceback (most recent call last):
  File "/rzhome/xxx/cvat_task_creator/creator.py", line 42, in <module>
    task = client.tasks.create_from_data(
  File "/rzhome/xxx/miniconda3/envs/cvat/lib/python3.9/site-packages/cvat_sdk/core/proxies/tasks.py", line 311, in create_from_data
    raise exceptions.ApiException(
cvat_sdk.api_client.exceptions.ApiException: Status Code: 200
Reason: OK
HTTP response headers: HTTPHeaderDict({'Allow': 'GET, HEAD, OPTIONS', 'Content-Length': '77', 'Content-Type': 'application/vnd.cvat+json', 'Date': 'Thu, 03 Nov 2022 18:52:43 GMT', 'Referrer-Policy': 'same-origin', 'Server': 'Apache', 'Vary': 'Accept,Origin', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY'})
HTTP response body: b'{"state":"Failed","message":"ValueError: No media data found","progress":0.0}'
```

### Context

I want to create tasks automatically without using the UI, the folders with the images include also other files . 
In the  UI its too much work explicitly excluding all non-images, so i want to have a SDK way to create tasks. The CLI also doesnt work for me due to https://github.com/opencv/cvat/issues/4962 ( i think i need to wait for the next release be able to use it?)

### Your Environment

- Running via  `CVAT_VERSION=dev docker-compose  up -d`
- Git hash commit (`git log -1`):
```
commit 2311b10b800a5c564af3af547472541e9b9b7cde (HEAD -> develop, origin/develop, origin/HEAD)                                                                          
Author: Anastasia Yasakova <yasakova_anastasiya@mail.ru>
Date:   Fri Oct 21 12:52:36 2022 +0300

    Fix an issue with Imagenet dataset import (#4861)

```
- Docker version `docker version` (e.g. Docker 17.0.05): Docker 20.10.12
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Debian
- Code example or link to GitHub repo or gist to reproduce problem: No
- Other diagnostic information / logs:
```

django@c58e8b630737:~$ cat logs/cvat_server.log 
....
[2022-11-03 18:52:38,760] INFO cvat.server: create task #117
[2022-11-03 18:52:38,766] WARNING cvat.server: Skip '/home/django/share/"flightdata/2022-08-13T09-00-00-payload-images-helgoland/cam-l/2022-06-15T08-21-49.975755.jpg"' file (its mime type doesn't correspond to supported MIME file type)

```

**Comment by zhiltsov-max** [comment] 2022-11-04 07:26
Hi. It looks like the image or the file share use might be the cause. Here are some checks that can help us to resolve the problem:
- could you check if you can create the task with another image? 
- could you check if you can create the task with this or another image if it is uploaded from the local disk?
- could you share the image file (maybe privately) so we could check it and try to reproduce the problem?

**Comment by julled** [comment] 2022-11-04 10:31
I tried the same script with image_1 & image_2 from [the shared unittestfolder](https://github.com/opencv/cvat/tree/develop/tests/mounted_file_share/images), but get the same error.

```
django@c58e8b630737:~$ cat logs/cvat_server.log 

[2022-11-04 10:24:15,943] WARNING cvat.server: Skip '/home/django/share/"flightdata/test/image_2.jpg"' file (its mime type doesn't correspond to supported MIME file type)              
[2022-11-04 10:24:15,943] WARNING cvat.server: Skip '/home/django/share/"flightdata/test/image_1.jpg"' file (its mime type doesn't correspond to supported MIME file type)       
```
So it doesnt seem to be the iamges themselfs which cause the problem.

My real folderstructure on the HDD is like
```
/data/flightdata/test/
```
and

```
(base) xxx@xxxx:/opt/cvat$ cat docker-compose.override.yml 
version: '3.3'

services:
  cvat_server:
    volumes:
      - cvat_share:/home/django/share:ro
  cvat_worker_default:
    volumes:
      - cvat_share:/home/django/share:ro

volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /data
      o: bind
```

Does the Filesystem mounts look correct?

**Comment by zhiltsov-max** [comment] 2022-11-04 10:38
@SpecLad, could you please check?

**Comment by SpecLad** [comment] 2022-11-04 14:52
This seems like the same bug as #4962. @julled did you build the SDK yourself or are you using a release version?

**Comment by julled** [comment] 2022-11-04 14:59
> This seems like the same bug as #4962. @julled did you build the SDK yourself or are you using a release version?

but isnt the error message a different one?

I use the release version.

**Comment by SpecLad** [comment] 2022-11-04 15:06
> but isnt the error message a different one?

Sure, but the cause is the same - extra quotes inserted where they don't belong.

I'm pretty sure it's the same bug, so I'm going to close this issue. If you can reproduce it with an SDK built from the development branch, or with the next release (when that comes out), feel free to reopen it.

**Closed by SpecLad** 2022-11-04 15:06 UTC

**Comment by julled** [comment] 2022-11-04 15:09
If i try to build the SDK on my own it fails

```
(base) xxx@xxx:/opt/cvat$ docker-compose -f docker-compose.yml -f docker-compose.dev.yml run     --no-deps --entrypoint '/usr/bin/env python' --rm -u "$(id -u)":"$(id -g)" -v "$PWD":"/local"     cvat_server     manage.py spectacular --file /local/cvat-sdk/schema/schema.yml                                                    
WARNING: The no_proxy variable is not set. Defaulting to a blank string.                                       
WARNING: Found orphan containers (cvat) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.                                 
Creating cvat_cvat_server_run ... done
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 363, in execute        
    settings.INSTALLED_APPS
  File "/opt/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__                
    self._setup(name)
  File "/opt/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup                     
    self._wrapped = Settings(settings_module)
  File "/opt/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__                  
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module                                  
    return _bootstrap._gcd_import(name[level:], package, level)                                                
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import                                              
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load                                            
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked                                   
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked                                            
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module                                      
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                 
  File "/home/django/cvat/settings/production.py", line 5, in <module>                                         
    from .base import *
  File "/home/django/cvat/settings/base.py", line 394, in <module>                                             
    os.makedirs(Path(IAM_OPA_BUNDLE_PATH).parent, exist_ok=True)                                               
  File "/usr/lib/python3.8/os.py", line 223, in makedirs                                                       
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/django/static/opa'                                       
ERROR: 1

```

**Comment by julled** [comment] 2022-11-05 17:01
I think (not expert in this) i was able to compile the sdk on my own using the official schema from https://app.cvat.ai/api/docs/ and the howto from https://opencv.github.io/cvat/docs/api_sdk/sdk/developer-guide/

But i still get the same problem in the log:

`[2022-11-05 16:55:49,722] WARNING cvat.server: Skip '/home/django/share/"flightdata/2022-08-13T09-00-00-payload-images-helgoland/cam-l/2022-06-15T08-21-49.975755.jpg"' file (its mime type doesn't correspond to supported MIME file type)
`

Does this mean that the SDK recompilation cant be succesful or the issue might be somewhere else?
