### ISSUE TITLE
Make sure the CVAT backend and all necessary services

### ISSUE THREAD

**Issue by h904798869** [opencv/cvat#5923] opened 2023-03-24 02:56 UTC
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by azhavoro** [comment] 2023-03-24 08:56
Please provide logs from `cvat_server` and `cvat_db` containers

**Comment by azhavoro** [comment] 2023-03-24 08:58
Duplicate of #5922

**Closed by azhavoro** 2023-03-24 08:58 UTC
