### ISSUE TITLE
Can't create a new task with a non-admin user

### ISSUE THREAD

**Issue by VesninEN** [opencv/cvat#345] opened 2019-03-07 05:49 UTC
I'm just setup docker on Windows10. Restart.
run in windows powershel these commands:
docker-compose build
docker-compose up -d

Open localhost:8080, register and press button "Create New Task
![2019-03-07_084030_cr](https://user-images.githubusercontent.com/29756588/53934980-d054fe00-40b5-11e9-95f2-afe98c32592a.png)
".
After filling fields in Task Configuration I cant't do anything - button "Submit" didn't take any effect (I only see big red licence text).
2019-03-07_084030_cr

**Comment by nmanovic** [comment] 2019-03-07 05:54
@VesninEN , OK. I will mark the issue as a bug. Too many users complain. But the problem here is only bad error handling. Indeed your user doesn't have permissions to create a task. To do that you need to go to "admin" panel and add necessary permissions to the new user (e.g. assign "user" group/role). Read here how to create the superuser: https://github.com/opencv/cvat#create-superuser-account

**Comment by Vafilor** [comment] 2019-06-01 04:49
I think this issue has been resolved.
Just tried it on develop - a311648 and got the following.

<img width="617" alt="Screen Shot 2019-05-31 at 9 47 42 PM" src="https://user-images.githubusercontent.com/7330539/58743827-ceb58080-83ed-11e9-84f9-bd1210fe53fb.png">

Not the prettiest error, but it's better than the license text and explains what the issue is.

**Comment by nmanovic** [comment] 2019-06-01 12:40
@Vafilor , I agree. Let's close the issue. Thanks for the notice.

**Closed by nmanovic** 2019-06-01 12:40 UTC
Labels: bug

**Comment by keshavadk** [comment] 2021-11-10 05:12
> @VesninEN , OK. I will mark the issue as a bug. Too many users complain. But the problem here is only bad error handling. Indeed your user doesn't have permissions to create a task. To do that you need to go to "admin" panel and add necessary permissions to the new user (e.g. assign "user" group/role). Read here how to create the superuser: https://github.com/opencv/cvat#create-superuser-account
