### ISSUE TITLE
Authorization error on login page while running the CVAT using helm

### ISSUE THREAD

**Issue by Rekha-Prakash** [opencv/cvat#4192] opened 2022-01-18 09:19 UTC
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

### Expected Behaviour
run the cvat on my mac using helm chart doc provided [here](https://github.com/openvinotoolkit/cvat/tree/develop/helm-chart) without any issue

### Current Behaviour
Running into authorization error while accessing UI and unable to sign in/up.

### Steps to Reproduce (for bugs)

1. Followed the doc - https://github.com/openvinotoolkit/cvat/tree/develop/helm-chart till step 3
2.  did port forward to access the server and UI from browser
```
kubectl port-forward service/cvat-backend-service 8080:8080
kubectl port-forward service/cvat-frontend-service 8090:80
``` 
3. opened the chrome browser in incognito mode - http://localhost:8090 and getting this error,
<img width="1784" alt="CVAT_error" src="https://user-images.githubusercontent.com/10654761/149906982-f4e66dd2-369c-45db-a907-f6e81c231697.png">

### Your Environment

- Docker Desktop : Docker Desktop 4.3.2 (72729) 
- Kubernetes enabled in docker desktop - v1.22.4
- Operating System and version (e.g. Linux, Windows, MacOS): MacOS

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment] 2022-01-18 12:16
@Rekha-Prakash , thanks for the report. CVAT team doesn't support Kubernetes officially. I believe we have the problem because of new component which was integrated recently. Looks like it is necessary to update helm charts and add `opa`.

**Comment by Goseokbin** [comment] 2022-02-10 05:21
@nmanovic 
i have a same issue. do you have any plan to update?

**Comment by nmanovic** [comment] 2022-02-10 09:36
@Goseokbin , yes. It is in our nearest plans.

**Comment by HarrisDePerceptron** [comment] 2022-03-10 08:14
Similar issue. lanched a much more detail issue here #4438  maybe it matches this

**Comment by bsekachev** [comment] 2022-09-02 13:28
Hello,

I will close the issue for now. 
Try to use the latest version of CVAT, if the issue is still relevant, do not hesitate to reopen :)

**Closed by bsekachev** 2022-09-02 13:28 UTC
