### ISSUE TITLE
Expect label attributes to be imported from COCO annoations

### ISSUE THREAD

**Issue by fierval** [opencv/cvat#4764] opened 2022-07-18 23:12 UTC
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I have images of store receipts annotated & saved as COCO. I have defined labels (categories) for my CVAT project to have attribute `utf8_string` which contains the text

E. g.
```json
  {
    "name": "STORE.NAME",
    "color": "#3d3df5",
    "attributes": [
      {
        "name": "utf8_string",
        "input_type": "text",
        "mutable": true,
        "values": [
          "text"
        ]
      }
    ]
  },
```

When I try to import COCO annotations into the tool, everything appears to import fine, except the attribute value which is ignored.

So for this bit of image:

![Walmart Receipt](https://user-images.githubusercontent.com/987574/179631649-4da5acda-1fda-4326-be17-feca1dd55260.png)

### Expected Behaviour
Label (category) attribute values to be imported.

![Correct Annotatin](https://user-images.githubusercontent.com/987574/179631788-00b9f32c-4bf4-4f85-9e6f-2102b6bfb0ee.png)

### Current Behaviour
Label (category) is lost and a default value is substituted:

![Wrong Annotation](https://user-images.githubusercontent.com/987574/179631850-5d8b3818-6243-4acb-a1ae-e93bd50e5591.png)

### Context
I have thousands of annotated images and I need a way to fix the text in many annotations. Exporting the attributes works correctly, importing should as well.
 
### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by kirill-sizov** [comment] 2022-08-29 08:57
Hi, @fierval thank you for reporting the issue.

I have tried to reproduce your problem, but in my case everything works fine.

If it's possible, could you please provide piece of your annotation file that will help us to reproduce your problem?
In which version did you meet this problem?

**Comment by kirill-sizov** [comment] 2022-09-05 09:45
Hello,
I will close this issue.
If the issue is still relevant, do not hesitate to reopen.

**Closed by kirill-sizov** 2022-09-05 09:45 UTC
Labels: need info
