### ISSUE TITLE
PROBLEM WITH RESOLUTION IMAGES 1944x27136 pixels (30,596 KB)

### ISSUE THREAD

**Issue by mmstec** [opencv/cvat#3427] opened 2021-07-16 19:45 UTC
Hello everyone!

We are working with research on image annotations at the university (UEFS/BR).

In COCO Annotation, CVAT Annotation and LabelMe Annotation, we can upload and annotate images up to 1910x8815 px (20,322 KB).

However, we are unable to load high resolution images, for example:
1944x27136 px (30,596 KB).

Can you tell us something about it?
Today, what would be the tool's resolution limit?

We appreciate your cooperation!

Marcos Morais
Computer Science master’s degree,
Information Technology post-graduate and
Bachelor in Information Systems
linktr.ee/marcosmoraisjr

Teaching is the highest form of understanding.
Aristotle, Greek philosopher (384 - 322 BC)

**Comment by nmanovic** [comment] 2021-07-19 07:34
@mmstec , at the moment CVAT doesn't support tiling of images. For such big images, it is an extremely important feature. What is the input for your NN? Are you going to use crops or original images for the input layer?

**Comment by bsekachev** [comment] 2024-01-30 14:39
Duplicate of #2205

**Closed by bsekachev** 2024-01-30 14:39 UTC
Labels: duplicate, enhancement
