### ISSUE TITLE
Can not use video on cloud storage - "Invalid 'manifest.jsonl file structure': 'extension' is required, but not found".

### ISSUE THREAD

**Issue by chorus12** [opencv/cvat#5171] opened 2022-10-26 14:11 UTC
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Created a matifest.jsonl for mp4 video. Uploaded both to S3 cloud storage and created a cloud storage in cvat server.  
Then created a project and a task and selected a cloud storage with corresponding video manifest. 
So system gives me an error:
```
Could not fetch content for cloud storage #5
Error: Request failed with status code 400. "Invalid 'manifest.jsonl file structure': 'extension' is required, but not found".
```
This is ugly strange cos extension is valid for pictures only.  
Contents of manifest.jsonl is  
```
{"version":"1.1"}
{"type":"video"}
{"properties":{"name":"video25.mp4","resolution":[1920,1200],"length":3270}}
{"number":0,"pts":0,"checksum":"4815365990e6644fa58ee9f52383ad3d"}
{"number":12,"pts":3072,"checksum":"d7e7a38c416541a9040acc3165fd6b79"}
{"number":24,"pts":6144,"checksum":"3fa58d757b91c17a2a225f1d4d1316a7"}
{"number":36,"pts":9216,"checksum":"be37551a52327874fdcf2ebc8114689b"}
{"number":48,"pts":12288,"checksum":"be0564207bb2dbcf5f04995d5c3b6f8b"}
{"number":60,"pts":15360,"checksum":"57dbecc197fd5358fa2e6802231fa2a8"}
{"number":72,"pts":18432,"checksum":"a486049853a6b6785096d8cd76887374"}
{"number":84,"pts":21504,"checksum":"3a58ee985c2259b0a67786aa8e71692f"}
{"number":96,"pts":24576,"checksum":"7a07a6e27085e8c30390afa8d7279f78"}
{"number":108,"pts":27648,"checksum":"ec3879dd92c4f00256788d4b6b47ceed"}
...
```

### Expected Behaviour

All should work

### Current Behaviour

see the description

### Your Environment

- Git hash commit (`git log -1`):
```
commit 99c006a612f75b72455e3b6a812eec139173951d (HEAD -> develop, origin/develop, origin/HEAD)
Author: Kirill Sizov <kirill.sizov@cvat.ai>
Date:   Mon Oct 10 15:00:58 2022 +0300

    Add docs for webhooks (#5035)
```
- Docker version `docker version` (e.g. Docker 17.0.05): Docker version 20.10.18, build b40c2f6b5d
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Linux bright 5.19.12-arch1-1

**Comment by Marishka17** [comment] 2022-10-26 15:06
Duplicate of #4460, #4853

**Comment by nmanovic** [comment] 2023-01-04 15:21
I will close the issue as a duplicate.

**Closed by nmanovic** 2023-01-04 15:21 UTC
Labels: duplicate
