### ISSUE TITLE
Impossible to import a dataset in COCO when images named image1.png and image1.jpg

### ISSUE THREAD

**Issue by codewithunknown** [opencv/cvat#7545] opened 2024-03-02 16:03 UTC
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

### Steps to Reproduce

1.Create a new task on CVAT.
2.upload images named image1.png and image1.jpg
3.upload COCO annotations which is Empty nothing in it
Will throw error 500 Internal Server Error
![image](https://github.com/opencv/cvat/assets/126901279/d70810ad-090a-45de-a352-957f8d896b33)

### Expected Behavior

Show a notification that the File is Invalid

**Comment by codewithunknown** [comment] 2024-03-02 16:04
cc : @nmanovic

**Comment by konavivekramakrishna** [comment] 2024-03-02 16:04
Hey 

I'm interested in contributing to this issue

**Comment by konavivekramakrishna** [comment] 2024-03-02 16:05
@codewithunknown 

can you please explain it in detail

**Comment by nmanovic** [comment] 2024-03-05 06:54
Duplicate of #7523

**Closed by nmanovic** 2024-03-05 06:54 UTC
Labels: bug, good first issue
