### ISSUE TITLE
both admin account and account create from webpage can modify tasks 

### ISSUE THREAD

**Issue by yxftju** [opencv/cvat#1114] opened 2020-02-01 12:33 UTC
I found that both admin account and account create from webpage can modify tasks, assign handlers. It seems it is an bug .How can I manage the account using admin ?

**Comment by azhavoro** [comment] 2020-02-03 07:34
@yxftju 
Hi, thanks for the report. It looks a duplicate of https://github.com/opencv/cvat/issues/1030.
We are going to fix it in the nearest future.

**Comment by azhavoro** [comment] 2020-06-23 10:51
At the moment as workaround is possible to set `reduce_task_visibility` to True here https://github.com/opencv/cvat/blob/develop/cvat/settings/base.py#L424 to remove public access to unassigned tasks. The new permission system will be introduced in future releases.

**Closed by azhavoro** 2020-06-23 10:51 UTC
Labels: bug, duplicate

**Comment by liucong255** [comment] 2021-12-23 09:01
> 目前，可以在`reduce_task_visibility`此处将解决方法设置为 True https://github.com/opencv/cvat/blob/develop/cvat/settings/base.py#L424以删除对未分配任务的公共访问权限。新的权限系统将在未来版本中引入。
I have modified the cvat/cvat/Settings/base. Py of reduce_task_visibility is True, then the up - d more new but doesn't work, everyone can see the task
