### ISSUE TITLE
Taking too long to load image, zoom in/out, edit points, etc - CVAT lags in working with aerial images.

### ISSUE THREAD

**Issue by arasharchor** [opencv/cvat#2846] opened 2021-02-21 17:13 UTC
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)
- [ ] 
### Expected Behaviour
To be able to annotate aerial images easily similar to Qgis software.
I am annotating 100 aerial images with the size of 6000x8000px with more than 1000 objects and about 3000points.

### Current Behaviour
I have to wait for a long time until the image is loaded. Then takes long if I want to zoom in or out to edit points. 
Browser is asking to stop the page:
![image](https://user-images.githubusercontent.com/12903362/108632231-1b68a700-746e-11eb-878e-2a9d51284b9a.png)

![image](https://user-images.githubusercontent.com/12903362/108632176-d2b0ee00-746d-11eb-826e-ae7e18ba52b2.png)
![image](https://user-images.githubusercontent.com/12903362/108632295-6c789b00-746e-11eb-9774-784d1d37e7bc.png)
![image](https://user-images.githubusercontent.com/12903362/108632327-9631c200-746e-11eb-95ee-aac0a51b8437.png)
![image](https://user-images.githubusercontent.com/12903362/108632360-c1b4ac80-746e-11eb-974d-6ec3e3f655c4.png)

### Possible Solution
There is a solution for this case by making image pyramid. Also for the annotations, there is a way of working with tiled json in aerial imagery.
There is a sample for loading large images into the website here:
https://sg.geodatenzentrum.de/web_dop_viewer/viewer.html#lat=48.9156&lon=9.0070&zoom=5&webatlasde=false&dop40=true&layer_4=false&layer_3=true&layer_2=true&layer_1=false

### Steps to Reproduce (for bugs)
Load 100 large images with more than 6000x6000px size and populate with more than 1000 objects.

### Your Environment
cvat version 1.2
ubuntu 18.04

@nmanovic 
I do appreciate it if you could let me know if there is a solution for my use case.

Shall I switch to OnePanel for this case?
https://github.com/onepanelio/onepanel

**Comment by nmanovic** [comment] 2021-02-21 17:49
@arasharchor , it is known that CVAT doesn't support well high resolution images for now. It has to be implemented. I believe we have a similar issue already: https://github.com/openvinotoolkit/cvat/issues/531

I don't think that it is a huge feature to implement. If somebody can contribute the feature, it will help. 

The simplest workaround is to tile images outside CVAT and annotate tiles. Of course it is extra pre-processing and post-processing steps.

**Comment by arasharchor** [comment] 2021-02-21 17:56
@nmanovic 
Thanks a lot for your prompt reply and sorry for overlooking the mentioned issue. I should have searched more.

At the moment, I am annotating the small images in cvat and stitch them in Qgis, but the problem is to merge polylines which can not be merged also a lot of time to spend to stitch the annotations to make sure of no gap on the image boundaries.

**Comment by bsekachev** [comment] 2024-01-30 14:41
Duplicate of #2205

**Closed by bsekachev** 2024-01-30 14:41 UTC
Labels: enhancement
