### ISSUE TITLE
Colors exported masks do not match labels

### ISSUE THREAD

**Issue by cecileconrad** [opencv/cvat#6274] opened 2023-06-09 08:52 UTC
### My actions before raising this issue
- [ yes] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ yes] Searched [past issues](/issues)

Last week, when I exported my job as a segmentation mask, everything went alright. However, when I export my job today (without changing anything in my settings or in the job) the colors in the label map do not match my masks. 
Last week's image (expected behavior):
![image](https://github.com/opencv/cvat/assets/78492274/311144a8-7bbd-46e7-a078-ff449bdb55d4)

This week's image (current behavior):
![Color_frame_50](https://github.com/opencv/cvat/assets/78492274/03095483-bdb0-427c-8438-8ac10427ec75)

The label map is unchanged, being: 

Background:0,215,255::
Bone:255,0,204::
Cartilage:0,255,133::
Condyle:252,0,42::
Damage:0,255,0::
Meniscus:204,153,51::
Skin:212,0,255::
Tissue:255,255,0::
background:0,0,0:: --> not used this one

For example, you would expect the background to be blue and not red(ish). 

I did not change any setting and cannot find a solution online. 

### Your Environment
I am using the online CVAT tool at https://app.cvat.ai with:

Server version: 2.4.5
Core version: 9.1.1
Canvas version: 2.16.6
UI version: 1.51.1

**Comment by cecileconrad** [comment] 2023-06-09 09:21
Even an update: 
For two frames with the same labels, the colors differ per image per label. 
![Color_frame_133](https://github.com/opencv/cvat/assets/78492274/3400db95-8362-43aa-aa3d-d27bebf41482)
![Color_frame_148](https://github.com/opencv/cvat/assets/78492274/c15af57e-8bf7-4c4f-af08-89b090f19dd2)
These images are part of the same task. The label structure which is "white" in the top image is the same label as the brown in the bottom image. The same applies the other way around (brown becomes white, but is the same label). The colors again do not match the labelmap.

**Comment by zhiltsov-max** [comment] 2023-06-09 11:46
Hi, could you please share the task id (maybe, privately, via email)?

**Comment by zhiltsov-max** [comment] 2023-06-16 10:25
The annotations were shared privately. In the `Segmentation Mask` format, the `SegmentationClass` directory contains class labels, so it is affected by label colors specified in the task/project configuration. In turn, the `SegmentationInstance` directory contains the object ids encoded as colors, which use the original VOC colormap. Please check the `SegmentationClass` directory, it should contain the expected colors. 

I will close the issue, feel free to reopen if the problem is not resolved.

**Closed by zhiltsov-max** 2023-06-16 10:25 UTC
Labels: need info
