### ISSUE TITLE
Brush and Erase Tool based on polygon with holes similar to COCO Annotator and Gimp

### ISSUE THREAD

**Issue by arasharchor** [opencv/cvat#2384] opened 2020-10-31 22:52 UTC
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
To be able to annotate object with a brush tool with defined class and color similar to CoCo annotator and Gimp softwares in which one draw freely  and can click on one point, keep "ctrl" bottom pressed to **draw a straight line as well.**
One is also possible to make the beginning of the point as a straight line with defined angle rather than a circle.
### Current Behaviour
Right now it is not possible to have a similar. for having that one has to use Polygon tool and in case of a whole, one has to annotate that area with a Background class.

### Possible Solution
One could adapt COCO Annotator tool to be able to draw straight line as well as right endings in addition to circle endings.

**Comment by bsekachev** [comment] 2020-11-02 12:04
Duplicate of #1849

**Closed** 2024-01-30 14:38 UTC
Labels: duplicate, enhancement
