### ISSUE TITLE
Users cannot be deleted (Server error: 500) 

### ISSUE THREAD

**Issue by JingyuQian** [opencv/cvat#664] opened 2019-08-24 01:28 UTC
Hello, thanks for this annotation tool, it's really useful! 
1) Just curious, how do I erase all the users previously registered? I tried deleting a user in the admin panel, but received an `Server error: 500`. 
2) Once a user logged in, the next time he wants to log in with another account, how to switch between accounts? I don't see a button on the UI for it. 

Thanks very much!

**Comment by nmanovic** [comment] 2019-08-24 13:16
@JingyuQian, 

>> Just curious, how do I erase all the users previously registered? I tried deleting a user in the admin panel, but received an Server error: 500.

It is a bug.

>> Once a user logged in, the next time he wants to log in with another account, how to switch between accounts? I don't see a button on the UI for it.

Use http://localhost:8080/auth/login or REST point http://localhost:8080/api/v1/auth/logout. In the future we will add a button to logout the user.

**Comment by nmanovic** [comment] 2019-08-24 13:22
There are several problems here:
- [ ] server error when you try to delete a user.
- [ ] I don't see a way to delete a user in REST API (need to re-check)
- [ ] New user has all groups now (admin, user, annotator, observer)

```
[Sat Aug 24 13:08:28.547340 2019] [wsgi:error] [pid 312:tid 139630710662912] [remote 172.18.0.1:54624]   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 84, in _execute
[Sat Aug 24 13:08:28.547351 2019] [wsgi:error] [pid 312:tid 139630710662912] [remote 172.18.0.1:54624]     return self.cursor.execute(sql, params)
[Sat Aug 24 13:08:28.547362 2019] [wsgi:error] [pid 312:tid 139630710662912] [remote 172.18.0.1:54624] django.db.utils.ProgrammingError: relation "allauth_socialaccount" does not exist
[Sat Aug 24 13:08:28.547373 2019] [wsgi:error] [pid 312:tid 139630710662912] [remote 172.18.0.1:54624] LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "allauth_s...
[Sat Aug 24 13:08:28.547385 2019] [wsgi:error] [pid 312:tid 139630710662912] [remote 172.18.0.1:54624]
```

**Comment by JingyuQian** [comment] 2019-08-24 21:44
@nmanovic 
Thanks for the clarification. Yes I can also confirm the third problem you mentioned above.
- I experimented several times and found out that admin&user groups have the right to create a new task, while annotator&observer don't (they receive a 503 error).
- All groups seem to have the right to delete a task. Maybe we can change it to only the task creator and admin can delete a task?

It would be nice that in the `group` section of the admin panel, we can display some info about what privileges a group has.

**Comment by bsekachev** [comment] 2019-09-03 12:25
@JingyuQian 
Hi, I have the same issue with deleting a user. 
I found a solution in #687

**Comment by bsekachev** [comment] 2019-09-03 12:28
> I experimented several times and found out that admin&user groups have the right to create a new task, while annotator&observer don't (they receive a 503 error).

It isn't a problem. Such behavior is expected.

> All groups seem to have the right to delete a task. Maybe we can change it to only the task creator and admin can delete a task?

Are you sure? Only admin and task owner can delete any task (I've just checked it). I get code 403

**Comment by bsekachev** [comment] 2019-09-03 12:31
@nmanovic 
> New user has all groups now (admin, user, annotator, observer)

Checked it on both django and rest registrations. Can't reproduce.

**Comment by JingyuQian** [comment] 2019-09-03 18:44
> @JingyuQian
> 
> > I experimented several times and found out that admin&user groups have the right to create a new task, while annotator&observer don't (they receive a 503 error).
> 
> It isn't a problem. Such behavior is expected.
> 
> > All groups seem to have the right to delete a task. Maybe we can change it to only the task creator and admin can delete a task?
> 
> Are you sure? Only admin and task owner can delete a task (I've just checked it). I get code 403

@bsekachev 

I didn't see such code back then. I think the system was having some issues when I was experimenting so the privileges got messed up. It would be nice if each group's privileges are shown in the admin panel.

**Comment by nmanovic** [comment] 2019-09-25 14:35
@JingyuQian ,

The metioned problem was fixed by Boris. I will close the issue. If you see other problems please submit a new issue with corresponding title.

**Closed by nmanovic** 2019-09-25 14:35 UTC
Labels: bug
