### ISSUE TITLE
Increase the number of characters in the "text" attribute 

### ISSUE THREAD

**Issue by aschernov** [opencv/cvat#1075] opened 2020-01-20 08:47 UTC
Hi! Could you increase the number of characters in the "text" attribute?
Now the limit is 64 symbols. Sometimes we use longer lines in case when we working on text recognition task, for example.

**Comment by azhavoro** [comment] 2020-01-20 08:52
duplicate of #973

**Closed** 2020-01-20 09:33 UTC
Labels: bug, duplicate
