### ISSUE TITLE
Import error when adding additional labels

### ISSUE THREAD

**Issue by manybodycpa** [opencv/cvat#1845] opened 2020-07-03 12:23 UTC
I have the following issue. I have an existing task with labels A and B. Now, I want to add labels C and D that appear in a file with annotations. After adding the labels in the task interface, uploading the annotations produces the following error:

`TypeError: Cannot read property 'attributes' of undefined`

If I instead create a new task with labels C and D, the import works fine.

Server version: 1.0rc0
Core version: 2.0.0
Canvas version: 1.0.0
UI version: 1.1.

**Comment by azhavoro** [comment] 2020-07-06 06:27
@manybodycpa  Hi, thanks for the report!

**Comment by bsekachev** [comment] 2020-08-25 10:47
@manybodycpa 

I am unable to reproduce the issue. 
Steps I tried:
1. Created a task with two labels
2. Created four objects there
3. Dumped annotations as CVAT Images
4. Changed labels in the dumped annotation file for two objects (doesn't exist in the task)
5. Added these labels on the task page
6. Uploaded annotations successfully 

Please, update your CVAT and the issue probably will go away. 
I will close the issue for now, if you still experience it, please reopen

**Closed by bsekachev** 2020-08-25 10:47 UTC
Labels: bug
