### ISSUE TITLE
Documentation: improve contributing guide

### ISSUE THREAD

**Issue by kirill-sizov** [opencv/cvat#5264] opened 2022-11-09 12:25 UTC
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Expected Behaviour
It would be great to separate instructions for different OS in our contributing guide (e.g. with using `{{< tabpane >}}`)

### Current Behaviour
Currently all our instructions in [contributing guide](https://opencv.github.io/cvat/docs/contributing/development-environment/) are displayed as large plain text that contains different instructions and different notes for different platforms. Also, some development environment installation steps are displayed in the wrong order.

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by nmanovic** [comment] 2022-11-19 14:17
Duplicate of https://github.com/opencv/cvat/issues/5264

**Closed by nmanovic** 2022-11-19 14:17 UTC
Labels: enhancement, documentation
