### ISSUE TITLE
No export if one Task is empty

### ISSUE THREAD

**Issue by EpicMinister** [opencv/cvat#5022] opened 2022-10-01 19:47 UTC
Hello,

I have noticed that when exporting a project, you are not allowed to have an empty task. This leads to the following error:
"AttributeError: 'NoneType' object has no attribute 'get_frame_step'\n".

### Expected Behaviour
Export dataset with empty tasks or show warning.

### Current Behaviour
Error is thrown and you cannot export the dataset

### Possible Solution
Check if empty task is present. Is so then ignore that one.

### Steps to Reproduce (for bugs)
1. Create empty task
2. Export dataset

### Context
Timewaste (1h) due to lag of information.

### Your Environment
Server version: 2.1
Core version: 5.0.1
Canvas version: 2.13.2
UI version: 1.37.0

**Comment by zhiltsov-max** [comment] 2022-10-07 09:32
Hi! Could you please provide more information about the project and the export format? It seems that the problem is not just an unannotated task in the project.

**Comment by bsekachev** [comment] 2022-10-10 15:52
@zhiltsov-max 

Looks like it is about tasks which were created, but not filled out by data.

**Comment by bsekachev** [comment] 2022-10-18 15:01
Hi, @EpicMinister 

I was not able to reproduce the issue. 
I could export and backup a project with an empty task.

That is about current develop branch.

```
Server version: 2.3.dev20221018123604
Core version: 7.0.1
Canvas version: 2.15.4
UI version: 1.42.4
```

So, I will close the issue. If you still have the issue on the newer version, please reopen and provide us more details about reproducing.

**Closed by bsekachev** 2022-10-18 15:01 UTC
Labels: bug
