### ISSUE TITLE
Could not fetch projects Open the Browser Console to get details

### ISSUE THREAD

**Issue by jayden0331** [opencv/cvat#5749] opened 2023-02-22 00:44 UTC
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.
![image](https://user-images.githubusercontent.com/125533002/220491375-e6787bad-f597-410a-8044-be91300098ce.png)

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

![image](https://user-images.githubusercontent.com/125533002/220491445-81a5c192-58e1-44d5-aa64-23f9a39f70d2.png)
![image](https://user-images.githubusercontent.com/125533002/220491456-1f82b123-da15-4684-a758-a9310cdbb271.png)
![image](https://user-images.githubusercontent.com/125533002/220491477-8cb9c618-d127-440e-a3cb-8c48e96f94ee.png)

![image](https://user-images.githubusercontent.com/125533002/220491490-c91ed668-3daf-495f-8bf9-fb12a1851f40.png)

**Comment by zhiltsov-max** [comment] 2023-02-22 10:30
Seems also like the https://github.com/opencv/cvat/pull/5747. Could you please describe your actions to get the error?

**Comment by yasakova-anastasia** [comment] 2023-02-28 10:29
It seems the issue is similar to #5666.

**Comment by yasakova-anastasia** [comment] 2023-02-28 10:32
I think the issue has been fixed by #5662 and #5700. I will close this issue. Please reopen this issue if you have it again.

**Closed by yasakova-anastasia** 2023-02-28 10:32 UTC
Labels: bug
