### ISSUE TITLE
Creating project with REST API gives a project with no labels

### ISSUE THREAD

**Issue by IdoKarlinskiAB** [opencv/cvat#5750] opened 2023-02-22 08:34 UTC
### My actions before raising this issue
I am new to CVAT, I tried to create a basic project with some labels from the REST API,
I got response with status code 201 and the project shows in the UI but with no labels.
this is the payload for my post request - 
payload = {
    "name": 'project_from_rest_api',
            "labels": [ {'name': 'car', 'color': '#2080c0',
                          'attributes': [{'id': 7, 'name': 'is_truncated',
                                                                                      'mutable': True,
                                                                                      'input_type': 'radio',
                                                                                      'default_value': 'true', 'values': ['true', 'false']}],
                                                                                      'type': 'rectangle', 'sublabels': [], 'has_parent': False}],
    "owner_id": 1,

}
am I using wrong syntax to add labels?

**Comment by zhiltsov-max** [comment] 2023-02-22 10:37
Hi, could you please specify your CVAT version as described in the issue template? Is it your local server or the app.cvat.ai?

**Comment by zhiltsov-max** [comment] 2023-02-22 10:50
Hi! This seems to be fixed by #5700. Could you please check with that branch?

**Comment by zhiltsov-max** [comment] 2023-02-22 10:52
Possible duplicate of #5749

**Closed** 2023-03-13 22:07 UTC
Labels: question

**Comment by Qalababbass** [comment] 2023-11-11 00:39
Hi, I had a similar task where i needed to create tasks in a pre-defined project in CVAT using CVAT REST API. I am also uploading images to these tasks. There are some other methods too for debug.
Maybe it will be helpful for somebody new at CVAT.
[CVAT_REST_API](https://github.com/Qalababbass/CVAT_REST_API/blob/main/create_cvat_tasks.py)

Happy for my contribution.
