### ISSUE TITLE
Nuclio serverless deploy path has a typo via configuration interface.

### ISSUE THREAD

**Issue by IuliuNovac** [opencv/cvat#4901] opened 2022-09-04 10:33 UTC
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

There is an extra "/" in the path when deploying configurations from nuclio interface.

<a href="https://ibb.co/6FfJcw9"><img src="https://i.ibb.co/7K6NxCM/Screenshot-2022-09-04-122939.png" alt="Screenshot-2022-09-04-122939" border="0"></a>
<a href="https://ibb.co/48sYHVS"><img src="https://i.ibb.co/F5s0FDY/Screenshot-2022-09-04-123028.png" alt="Screenshot-2022-09-04-123028" border="0"></a>

**Comment by nmanovic** [comment] 2023-01-05 16:47
@IuliuNovac , thanks for the report. Please send us a PR if the issue is critical for you. I will close the issue.

**Closed by nmanovic** 2023-01-05 16:47 UTC
