### ISSUE TITLE
Failed status when uploading the model

### ISSUE THREAD

**Issue by sbanori** [opencv/cvat#560] opened 2019-07-10 10:49 UTC
Hello,

We tried to upload our model. We have 4 files which CVAT needs (xml, bin, json and py) but finally we have this type of comment:
"Checking request has returned the "failed" status. Message: Work-horse process was terminated unexpectedly (waitpid returned 139)".
What means this error?

Michael

**Comment by bsekachev** [comment] 2019-07-10 11:36
@azhavoro 
Andrey, could you please look into this?

**Comment by nmanovic** [comment] 2019-07-10 14:29
@sbanori ,

Could you please send us these 4 files to investigate the issue on our side?

**Comment by nmanovic** [comment] 2019-07-10 14:30
@sbanori , which version of OpenVINO do you use?

**Comment by Simonvil** [comment] 2019-07-11 06:54
Hello,
I had the same issue when I tried to upload my model with OpenVino 2019 R1.1.
I used the 2 files in the archive below with the .bin and .xml returned by the Model Optimizer for the model "faster_rcnn_resnet50_coco_2018_01_28".
The same .json and the .py worked with the .xml and .bin returned by the Model Optimizer for the model
"ssd_inception_v2_coco_2018_01_28"

[json_and_py.zip](https://github.com/opencv/cvat/files/3380571/json_and_py.zip)

**Comment by Simonvil** [comment] 2019-07-11 07:02
Adding a new model with files that work after this error causes the new model to appear as it should, along with an empty model with no name and no label, with the "upload date" being the moment of the error.

**Comment by sbanori** [comment] 2019-07-11 11:57
I use 2019_R1.1 version of OpenVino Toolkit
I have TF in version 1.14.

A comment to 
https://www.easypaste.org/file/eDZPuoNW/frozen.inference.graph.zip?lang=pl
is:
"Test started" and then "Checking request has returned the "failed" status. Message: Exception: Model was not properly created/updated. Test failed: not enough values to unpack (expected 4, got 2)"

A comment to
"Test started" and then "Checking request has returned the "failed" status. Message: Work-horse process was terminated unexpectedly (waitpid returned 139)"

This both are model of "faster_rcnn_resnet50_coco_2018_01_28".

**Comment by benhoff** [comment] 2019-07-11 14:36
@Simonvil, OpenVino 2019 isn't supported until https://github.com/opencv/cvat/pull/545 get's merged.

**Comment by nmanovic** [comment] 2019-07-11 14:46
The problem was fixed by @benhoff . I will close the issue. If you still can reproduce it on latest develop branch please don't hesitate to re-open it again.

**Closed by nmanovic** 2019-07-11 14:46 UTC
Labels: bug
