### ISSUE TITLE
Could not fetch frame data from the server

### ISSUE THREAD

**Issue by atekoa** [opencv/cvat#6400] opened 2023-06-29 08:45 UTC
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Specify a Cross-Origin Embedder Policy to prevent this frame from being blocked

### Context

Self hosted solution with CVAT v2.4.8
Used to work fine until CVAT v2.4.0 ... Maybe is related with [Replaced Apache mod_wsgi with Uvicorn ASGI server for backend use(https://github.com/opencv/cvat/pull/6195)]

### Your Environment

- Docker version `docker version`
Docker 20.10.14

- Are you using Docker Swarm or Kubernetes?
Yes, docker swarm

- Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 20.04 LTS

![COEP](https://github.com/opencv/cvat/assets/5947222/5967c183-dbf5-4e4a-b896-72bdd4dcd2ba)

**Comment by azhavoro** [comment] 2023-06-29 08:47
duplicate of #6399

**Closed** 2023-06-29 09:30 UTC
