### ISSUE TITLE
Export Individual Jobs Or Completed Jobs

### ISSUE THREAD

**Issue by nmichlo** [opencv/cvat#4669] opened 2022-06-01 21:42 UTC
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
Currently it is possible to export both projects and tasks. It should also be possible to export individual jobs.

### Current Behaviour
You cannot export individual jobs, only tasks or projects.

### Possible Solution
Similar API and UI options should be available for jobs with regards to importing/exporting labels and data as there currently exists for projects and tasks 

### Steps to Reproduce (for bugs)
N/A

### Context
- Projects are great for organising content for a specific purpose
- Tasks are great for organising data from different sources
- Jobs are great for progressive labelling and can be marked as complete, it may take quite long to label all the jobs in a particular task, but often we only want to export the labelled data. Adding export functionality for individual jobs would be great to work around this issue.

My current use case would be solved if export functionality was added that skips uncompleted jobs.

### Your Environment
N/A

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by zhiltsov-max** [comment] 2022-10-25 18:12
Duplicate of #5032 . Should be covered by #5160

**Closed** 2022-12-01 08:39 UTC

**Comment by nmichlo** [comment] 2022-12-01 11:04
Awesome work! Does the change in #5052 enable exporting only the jobs that are marked as complete, under a larger combined dataset?

**Comment by Marishka17** [comment] 2022-12-01 11:06
@nmichlo, Hi, it is possible to export any job
