### ISSUE TITLE
Cvat Could Not Check Authorization On The server

### ISSUE THREAD

**Issue by ObjectMuffin** [opencv/cvat#4714] opened 2022-06-22 14:11 UTC
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Current Behaviour
For the last two days, I have not been able to get into Cvat. I keep getting errors or checking authorization on the server. This hasn't happened to me before for this many attempts normally after an hour or so it will randomly work again. I am now wondering if this was a server-wide issue or me somehow. 

### Steps to Reproduce (for bugs)

1. Go to log in page
1. Type in log in information
1. Log in
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by strcom** [comment] 2022-06-23 12:54
Ensure you have opa rules loaded. I've tried today update to latest version CVAT and coudn't login for some time, because my opa rules where empty (I'm using default docker-compose configuration).

**Comment by nmanovic** [comment] 2022-08-20 04:07
@ObjectMuffin , I hope the problem is resolved now. I will close the issue. Please don't hesitate to reopen, if you still have any issues.

**Closed by nmanovic** 2022-08-20 04:07 UTC
