### ISSUE TITLE
export coco dataset

### ISSUE THREAD

**Issue by dzcmingdi** [opencv/cvat#4185] opened 2022-01-16 10:15 UTC
<img width="757" alt="截屏2022-01-16 下午6 10 49" src="https://user-images.githubusercontent.com/37565801/149655684-6a0169b5-d984-4936-84d3-a03783eb9330.png"> 

different image file but same image id. Is this a problem?

**Comment by zhiltsov-max** [comment] 2022-01-17 13:06
Hi, the problem appears because images have the same file name. Currently, CVAT support it only in the "CVAT for images" format. Please tell, if supporting it is important for your use case.

**Comment by zhiltsov-max** [comment] 2022-01-27 09:18
Duplicate of https://github.com/openvinotoolkit/cvat/issues/2046

**Closed** 2024-01-30 14:40 UTC
Labels: duplicate
