### ISSUE TITLE
How to add a job to an existing task?

### ISSUE THREAD

**Issue by adizhol** [opencv/cvat#1186] opened 2020-02-24 11:15 UTC
How to add a job to an existing task in version > 0.5

**Comment by bsekachev** [comment] 2020-02-25 07:50
@adizhol 

No way to add a job after task was created. 
If you see a problem here, you can share thoughts with us on [gitter](https://gitter.im/opencv-cvat). 
I will close the issue.

**Closed by bsekachev** 2020-02-25 07:50 UTC
Labels: question

**Comment by guillemboada** [comment] 2023-10-13 09:08
@bsekachev, I noticed that the gitter link is no longer available. Could you clarify whether the inability to add a job to an existing task is a design choice or a technical constraint? Thank you.

**Comment by bsekachev** [comment] 2023-10-13 09:49
* You can create one ground truth job per task https://opencv.github.io/cvat/docs/manual/advanced/analytics-and-monitoring/annotation-quality/
* You can not create additional annotation jobs

**Comment by guillemboada** [comment] 2023-10-13 09:57
Thanks for the quick reply. I'm specifically interested in the possibility of creating additional annotation jobs. If I acquire a new batch of data, I'd like the flexibility to extend an existing task by adding new jobs with that new data. Is the current limitation due to a technical constraint or rather design decision? If it's by design, how should the workflow look like when acquiring new data after the task has already been created?

**Comment by bsekachev** [comment] 2023-10-13 10:13
> Thanks for the quick reply. I'm specifically interested in the possibility of creating additional annotation jobs. If I acquire a new batch of data, I'd like the flexibility to extend an existing task by adding new jobs with that new data.

You probably want to create a project and extend the project with new data, by creating new tasks.

Project = dataset (it supports new data uploading, subsets, etc). You can even export it as a dataset.
Task = one data item (e.g. set of images or a video file).
Job = a way to parallel annotation work in CVAT, jobs do not exist out of CVAT context.
