### ISSUE TITLE
CORS issue on trying to upload large files

### ISSUE THREAD

**Issue by mbsachitk** [opencv/cvat#6229] opened 2023-06-02 05:44 UTC
### My actions before raising this issue
I'm hosting a CVAT instance on AWS EC2 instance by using my custom domain name to hit the AWS application load balancer which directs to EC2 instance where CVAT containers are running.
Running containers as follows: 
docker compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d --build

### Steps to Reproduce (for bugs)
The problem I'm facing is that for smaller images(size < 1 MB), the annotation tasks are getting created and we could see that the API call happening is "https".
But, when I try to create tasks with bigger images (Size >1 MB) for annotation, those API calls are using "http" protocol and is not working fine. I'm getting CORS error as follows.
"Could not create the task. Error: tus: failed to upload chunk at offset 0, caused by [object ProgressEvent], originated from request (method: PATCH,..........................."
When inspected using google chrome - developer tools, we could see the issue is with "upload.js" file residing in "tus-client" folder. This is the file used to implement chunking option for big files.
Please let me know how we can resolve the issue

Error message displayed in console:
Mixed Content: The page at 'https://www.xx.com/tasks/create' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.xx.com/api/tasks/72/data/7c08e3a2-962f-44cc-a63d-31955475d81a'. This request has been blocked; the content must be served over HTTPS.
cvat-app.tsx:354 Error: tus: failed to upload chunk at offset 0, caused by [object ProgressEvent], originated from request (method: PATCH, url: http://www.xx.com/api/tasks/72/data/7c08e3a2-962f-44cc-a63d-31955475d81a, response code: n/a, response text: n/a, request id: n/a).

**Comment by azhavoro** [comment] 2023-06-02 13:22
duplicate of #6201

**Closed by azhavoro** 2023-06-02 13:22 UTC
