### ISSUE TITLE
deploy automatic annotations to CVAT

### ISSUE THREAD

**Issue by seasenzzr000** [opencv/cvat#5902] opened 2023-03-22 09:55 UTC
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

I need to deploy automatic annotations to CVAT. Is there a detailed tutorial guide. thanks!
sorry I can't find it.

**Comment by zhiltsov-max** [comment] 2023-03-22 16:46
Hi, could you please be more specific about what you're trying to do? Do you want to annotate a dataset using a pre-trained model or you want to upload a file with already created annotations for your dataset? Both options are available in CVAT.

[Export, import](https://opencv.github.io/cvat/docs/manual/advanced/export-import-datasets/)
[Autoannotation with models](https://opencv.github.io/cvat/docs/manual/advanced/serverless-tutorial/)

**Comment by zhiltsov-max** [comment] 2023-04-13 20:15
I will close the issue, don't hesitate to reopen it, if the problem is not resolved.

**Closed by zhiltsov-max** 2023-04-13 20:15 UTC
Labels: question
