### ISSUE TITLE
new task video upload decode_slice_header after upload video mp4

### ISSUE THREAD

**Issue by Lifeguard-alex** [opencv/cvat#4891] opened 2022-08-31 18:31 UTC
last version 

decode_slice_header after upload video mp4

on older version like 2.0 i have no problem like this ?

Could not create the task on the server. av.error.PermissionError: [Errno 1] Operation not permitted; last error log: [h264] decode_slice_header error.

any help

**Comment by azhavoro** [comment] 2022-09-01 07:37
Hi, please provide exact cvat version are you used (got log -1) and steps to reproduce the issue on our side.
Have you tried to create a task with this video on app.cvat.ai?

**Comment by Lifeguard-alex** [comment] 2022-09-01 10:27
hi
i try to upload the video to  app.cvat.ai

and i get error :
Could not create the task
Error: Could not create the task on the server. av.error.PermissionError: [Errno 1] Operation not permitted.

**Comment by azhavoro** [comment] 2022-09-13 09:12
Hi, I cannot reproduce the issue,
What is the output of `ffprobe your_video_file` command?
Can you share the problematic video?

**Comment by nmanovic** [comment] 2022-09-21 16:52
@Lifeguard-alex , I will close the issue. Don't hesiitate to reopen if you have steps to reproduce.

**Closed by nmanovic** 2022-09-21 16:52 UTC
