### ISSUE TITLE
Using external database without default port

### ISSUE THREAD

**Issue by abertoldo** [opencv/cvat#4779] opened 2022-07-26 21:58 UTC
I have an environment running with external database in postgresql. We are migrating to another postgresql database, but it is running on another port, instead of the default 5432. We dumped the base and uploaded it to this other server, but when connecting to cvat, we received the error of Could not check authorization on the server . When uploading this same dump on another server using the default port 5432, the problem doesn't happen. My question is: I can't change the default port of the database? Can you help me?

**Comment by kirill-sizov** [comment] 2022-08-29 07:16
Hi, @abertoldo, thank you for reporting the issue.

Have you tried to change `CVAT_POSTGRES_HOST` and `CVAT_POSTGRES_PORT` environment variables?

**Comment by kirill-sizov** [comment] 2022-09-05 09:44
Hello, 
I will close this issue.
If the issue is still relevant, do not hesitate to reopen

**Closed by kirill-sizov** 2022-09-05 09:44 UTC
Labels: need info, infra
