### ISSUE TITLE
can`t build CUDA

### ISSUE THREAD

**Issue by wemamawe** [opencv/cvat#668] opened 2019-08-27 09:17 UTC
$ docker-compose -f docker-compose.yml -f docker-compose.override.yml -f components/analytics/docker-compose.analytics.yml -f components/cuda/docker-compose.cuda.yml -f components/openvino/docker-compose.openvino.yml -f cvat/apps/dextr_segmentation/docker-compose.dextr.yml up -d --build

WARNING: The no_proxy variable is not set. Defaulting to a blank string.
WARNING: The http_proxy variable is not set. Defaulting to a blank string.
WARNING: The https_proxy variable is not set. Defaulting to a blank string.
Building cvat
Step 1/48 : FROM ubuntu:16.04
 ---> 5e13f8dd4c1a
Step 2/48 : ARG http_proxy
 ---> Using cache
 ---> 281b3d6f81e3
Step 3/48 : ARG https_proxy
 ---> Using cache
 ---> 58aff67e3fec
Step 4/48 : ARG no_proxy
 ---> Using cache
 ---> 98a839e1d880
Step 5/48 : ARG socks_proxy
 ---> Using cache
 ---> 601b2210c391
Step 6/48 : ENV TERM=xterm     http_proxy=${http_proxy}       https_proxy=${https_proxy}     no_proxy=${no_proxy}     socks_proxy=${socks_proxy}
 ---> Using cache
 ---> a2b35cfc99c4
Step 7/48 : ENV LANG='C.UTF-8'      LC_ALL='C.UTF-8'
 ---> Using cache
 ---> dc5d74dfda5d
Step 8/48 : ARG USER
 ---> Using cache
 ---> 55fc0a46c0cd
Step 9/48 : ARG DJANGO_CONFIGURATION
 ---> Using cache
 ---> 0d358b9de58e
Step 10/48 : ENV DJANGO_CONFIGURATION=${DJANGO_CONFIGURATION}
 ---> Using cache
 ---> 8aeb1e3b9bc4
Step 11/48 : RUN apt-get update &&     apt-get install -yq         python-software-properties         software-properties-common         wget &&     add-apt-repository ppa:mc3man/xerus-media -y &&     add-apt-repository ppa:mc3man/gstffmpeg-keep -y &&     apt-get update &&     DEBIAN_FRONTEND=noninteractive apt-get install -yq         apache2         apache2-dev         libapache2-mod-xsendfile         supervisor         ffmpeg         gstreamer0.10-ffmpeg         libldap2-dev         libsasl2-dev         python3-dev         python3-pip         unzip         unrar         p7zip-full         vim &&     add-apt-repository --remove ppa:mc3man/gstffmpeg-keep -y &&     add-apt-repository --remove ppa:mc3man/xerus-media -y &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> e48180d07efe
Step 12/48 : ENV USER=${USER}
 ---> Using cache
 ---> 3d8c49f764dc
Step 13/48 : ENV HOME /home/${USER}
 ---> Using cache
 ---> 80b3507f7f2d
Step 14/48 : WORKDIR ${HOME}
 ---> Using cache
 ---> a0b93e921feb
Step 15/48 : RUN adduser --shell /bin/bash --disabled-password --gecos "" ${USER}
 ---> Using cache
 ---> 13b10634685e
Step 16/48 : COPY components /tmp/components
 ---> Using cache
 ---> 18626abec2b9
Step 17/48 : ARG CUDA_SUPPORT
 ---> Using cache
 ---> bf0deaf8966b
Step 18/48 : ENV CUDA_SUPPORT=${CUDA_SUPPORT}
 ---> Using cache
 ---> 08e1210c1920
Step 19/48 : RUN if [ "$CUDA_SUPPORT" = "yes" ]; then         /tmp/components/cuda/install.sh;     fi
 ---> Running in 60a76af9ac3c
Executing: /tmp/tmp.D46u6I0xDm/gpg.1.sh --fetch-keys
http://developer.download.nvidia.cn/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
gpg: key 7FA2AF80: public key "cudatools <cudatools@nvidia.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
cudasign.pub: OK
```_E: Malformed entry 1 in list file /etc/apt/sources.list.d/cuda.list (Suite)
E: The list of sources could not be read.
ERROR: Service 'cvat' failed to build: The command '/bin/sh -c if [ "$CUDA_SUPPORT" = "yes" ]; then         /tmp/components/cuda/install.sh;     fi' returned a non-zero code: 100_```

**Comment by wemamawe** [comment] 2019-08-27 09:19
The error is 

> The list of sources could not be read.
and I find it happend when run `echo "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/" > /etc/apt/sources.list.d/cuda.list && \
echo "deb http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/" > /etc/apt/sources.list.d/nvidia-ml.list`

**Comment by bsekachev** [comment] 2019-08-27 09:23
@wemamawe 
Thanks for the report. Please wait some time till I try to build it on my own.

**Comment by bsekachev** [comment] 2019-08-27 10:11
@wemamawe 
Works fine for me.

**Comment by bsekachev** [comment] 2019-08-27 10:14
@wemamawe 
What branch do you use? I have a little another sequence of steps from the develop branch.

**Comment by wemamawe** [comment] 2019-08-27 12:16
I down the cvat-0.4.1 release from [https://github.com/opencv/cvat/releases](https://github.com/opencv/cvat/releases)

**Comment by bsekachev** [comment] 2019-08-27 12:29
@wemamawe 
I see, there have been changes since 0.4.1 release. 
In particular CUDNN version has been updated. 

Actually we don't think that it's a reason of the error, but anyway you can try to build from the develop branch. Eventually sometimes problems can disappear just on rebuild.

**Comment by wemamawe** [comment] 2019-08-28 02:00
i try to rebuild CUDA, also had the same error. and if i  used command line like this `docker-compose -f docker-compose.yml -f docker-compose.override.yml -f components/analytics/docker-compose.analytics.yml -f components/openvino/docker-compose.openvino.yml -f components/tf_annotation/docker-compose.tf_annotation.yml -f cvat/apps/dextr_segmentation/docker-compose.dextr.yml` it run success.

**Comment by bsekachev** [comment] 2019-08-28 06:43
@wemamawe 
It is success because you install CVAT without CUDA.
Could you please attach whole building logs (with cuda) as a text file?

**Comment by bsekachev** [comment] 2019-09-02 10:33
@wemamawe 
I'll close this issue because we couldn't reproduce it and we didn't get enough information to investigation. 
Don't be shy reopen it if you still have problems with CUDA installation.

**Closed by bsekachev** 2019-09-02 10:33 UTC
Labels: question
