### ISSUE TITLE
empty API return for retrieve_annotations with format

### ISSUE THREAD

**Issue by timresink** [opencv/cvat#5942] opened 2023-03-27 15:36 UTC
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Hi all,
I am trying to load annotations through the CVAT low-level python SDK (v2.3.0). However, if I specify a format (I tried COCO 1.0, MOT 1.1, among others) then I only get a 202  with reason 'Accepted', but no data. However, when I do not specify a format I do get data in the response.
 
The API call I am making in Python looks like:
```
from cvat_sdk.api_client import ApiClient, Configuration
configuration = Configuration(
        host = host,
        username = user,
        password = pw
    )

with ApiClient(configuration) as api_client:
    (_, response) = api_client.jobs_api.retrieve_annotations(
            job_id,
            action='download',
            format='COCO 1.0', # or 'MOT 1.1'
            _parse_response=False
     )
    print(response.data)
```

Anyone any idea what could be at the source of this?

**Comment by zhiltsov-max** [comment] 2023-04-05 07:49
Hi, please read about file downloading protocol in CVAT [here](https://opencv.github.io/cvat/docs/api_sdk/sdk/lowlevel-api/#receiving-data). [Here](https://github.com/opencv/cvat/blob/develop/tests/python/rest_api/utils.py#L20-L34) you can find a code snippet for downloading.

**Comment by zhiltsov-max** [comment] 2023-04-13 20:10
I will close the issue, don't hesitate to reopen it, if the problem is not resolved.

**Closed by zhiltsov-max** 2023-04-13 20:10 UTC
Labels: question, sdk/cli
