### ISSUE TITLE
Backup + Restore Successful, Update successful.. cant login!

### ISSUE THREAD

**Issue by davodogster** [opencv/cvat#4805] opened 2022-08-15 06:04 UTC
### Expected Behaviour
being able to login! 

### Current Behaviour

![image](https://user-images.githubusercontent.com/46079516/184584282-b8d6730c-eda7-46ef-aec9-02fb0d8a0c02.png)
![image](https://user-images.githubusercontent.com/46079516/184584857-a422bbf7-c778-4946-bcad-88355dba5957.png)

![image](https://user-images.githubusercontent.com/46079516/184584349-94b1167d-f77d-4be3-938c-590e3f5a6a54.png)

I can view the admin panel:

![image](https://user-images.githubusercontent.com/46079516/184584689-dab5809d-ffae-4192-a336-ed6fdd304bd7.png)

### Possible Solution
Please let me know how to update CVAT and get it working after a successful CVAT restore (v1.7.0) :) Cheers! Sam

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker ):
- Operating System and version (e.g. Linux, ):
- Code example or link to GitHub repo or gist to reproduce problem:

**Comment by muddywellyboots** [comment] 2022-08-15 10:39
We have exactly the same issue after updating. Hope we can get it fixed!

**Comment by davodogster** [comment] 2022-08-15 21:13
Hi @nmanovic is there any easy fix? It appears multiple users are facing this issue.

**Comment by nmanovic** [comment] 2022-08-16 10:04
@muddywellyboots , @davodogster , let's try to reproduce on our side. I see that the previous version is v1.7.0. What is the new version?

**Comment by davodogster** [comment] 2022-08-16 10:05
New version is the latest from docker

Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nmanovic** [comment] 2022-08-16 10:10
The latest version has new microservices. You need to follow https://cvat-ai.github.io/cvat/docs/administration/basics/installation/. Basically need to clone the latest CVAT version: https://github.com/cvat-ai/cvat. And run `CVAT_VERSION=dev docker-compose up -d`

**Comment by nmanovic** [comment] 2022-08-16 10:15
@azhavoro , could you please help our community? Need to improve documentation if it is unclear. Probably @davodogster can help us and contribute to make it better.

**Comment by davodogster** [comment] 2022-08-16 10:16
Will it keep all the data/volumes?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nmanovic** [comment] 2022-08-16 10:19
@davodogster , it should delete nothing. You just update source code for your repo and run/create new containers. It should take time because CVAT will start migration of data after the CVAT container is up and running. But in any case it is better to backup your data just in case: https://cvat-ai.github.io/cvat/docs/administration/advanced/backup_guide/

**Comment by davodogster** [comment] 2022-08-16 20:41
> The latest version has new microservices. You need to follow https://cvat-ai.github.io/cvat/docs/administration/basics/installation/. Basically need to clone the latest CVAT version: https://github.com/cvat-ai/cvat. And run `CVAT_VERSION=dev docker-compose up -d`

Thanks! yes let me know if I can help. The new cvat-ai still clones from opencv/cvat and not cvat-ai.cvat so that could be changed?

**Comment by davodogster** [comment] 2022-08-16 21:35
@azhavoro I had a try at upgrading 1.7.0 to 2.1.0, but cvat_opa error

![image](https://user-images.githubusercontent.com/46079516/184989368-9b6263ba-0420-46b8-829a-4084d035597c.png)

**Comment by nmanovic** [comment] 2022-08-17 02:37
@davodogster , the problem above, which you mentioned for OPA is a networking problem. Just try again. 

```
The "Temporary failure in name resolution" error occurs when the system cannot translate a website name into an IP address.
While the error sometimes appears due to a lost internet connection, there are multiple reasons why it may show
up on your system.
```

**Comment by davodogster** [comment] 2022-08-17 03:53
@nmanovic yes I think you are right. This machine may just be having network issues at the moment. Thanks

**Comment by nmanovic** [comment] 2022-08-20 03:43
@davodogster , I will close the issue. Don't hesitate to reopen. We will also improve our documentation.

**Closed by nmanovic** 2022-08-20 03:43 UTC
