### ISSUE TITLE
Can't create task from Connected file share

### ISSUE THREAD

**Issue by ConsciousML** [opencv/cvat#5228] opened 2022-11-03 16:58 UTC
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

I was running CVAT 2.1 with success for the past few months.

I upgraded to server version 2.3 and now I have a problem uploading a task from a Connected file share.

I have successfully mounted a GCP Cloud Storage as a file share on a Compute Engine hosting CVAT.

When I upload a file to the share, I'm able to see it from the `cvat_server` container doing the following:
```bash
docker exec -it cvat_server bash
ls /home/django/video.mp4
```

I can also see the file in the connected file share from the UI:
![image](https://user-images.githubusercontent.com/6661264/199784102-7bfb5e5a-f16b-4f8d-ac82-14c0e49cb4a6.png)

When I try to create the task I have the following error:
![image](https://user-images.githubusercontent.com/6661264/199785095-59ce79b3-6a77-46c8-94b2-308d8c24fc8d.png)

The logs display:
```bash
Could not create the task on the server. av.error.FileNotFoundError: [Errno 2] No such file or directory: '/home/django/share/video.mp4'.
```

I'm I missing something ?

### Things I tried

- Unmount and mount the connected share
- Rebuild the images:
```bash
docker-compose -f docker-compose.yml -f docker-compose.https.yml -f components/analytics/docker-compose.analytics.yml -f docker-compose.override.yml -f docker-compose.dev.yml build
```

### Your Environment

- Git hash commit (`git log -1`): c7125a8ffbef2945a2256bc584f75353dd69ea1e
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.21
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 22.04
- CVAT_VERSION=dev

**Comment by zhiltsov-max** [comment] 2022-11-04 07:18
@Marishka17 , could you please check?

**Comment by Marishka17** [comment] 2022-11-04 07:42
@zhiltsov-max, yes, I'll check

**Comment by ConsciousML** [comment] 2022-11-04 11:05
I tried
```bash
CVAT_VERSION=v2.2.0 docker-compose -f docker-compose.yml -f docker-compose.https.yml -f docker-compose.https.yml -f docker-compose.override.yml up -d
```
And got the following error:
```bash
ERROR: for cvat_server  Cannot create container for service cvat_server: lstat /var/lib/docker/volumes/cvat_cvat_share/_data/video.mp4: operation canceled
```

**Comment by ConsciousML** [comment] 2022-11-04 11:29
I tried:
```bash
CVAT_VERSION=v2.2.0 docker-compose -f docker-compose.yml -f docker-compose.https.yml -f docker-compose.override.yml up -d
```

And had the same result:
![image](https://user-images.githubusercontent.com/6661264/199962345-7eebf21c-ee20-4f33-8f42-6e088e78ac53.png)

**Comment by zhiltsov-max** [comment] 2022-11-04 11:34
Seem to be a duplicate of #5229

**Comment by ConsciousML** [comment] 2022-11-04 11:52
I found the solution.

When I upgraded from v2.1.0 to v2.3.0, I didn't notice that there was a change in the connected file share config:
```bash
version: '3.3'

services:
  cvat_server:
    environment:
      CVAT_SHARE_URL: 'Mounted from /mnt/share host directory'
    volumes:
      - cvat_share:/home/django/share:ro

volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /mnt/disks/data/cloud/storage
      o: bind
```

I added:
```bash
cvat_worker_default:
    volumes:
      - cvat_share:/home/django/share:ro
```

It works now.

**Closed** 2022-11-10 05:53 UTC
