### ISSUE TITLE
Is it possible to send request from cvat-ui to localhost

### ISSUE THREAD

**Issue by zhitm** [opencv/cvat#6071] opened 2023-04-25 10:21 UTC
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

0. Run server at localhost:2390. It works fine, and it can receive requests from localhost. 
```     http_listener listener("http://localhost:2390"); ```
1. Install cvat for development
2. Add http request at cvat-ui/src/utils/opencv-wrapper: 
```     

const response = await fetch('https://127.0.0.1:2390', {
            method: 'POST',
            body: JSON.stringify({
                x: 10,
                y: 10,
                width: 100,
                height: 100,
            }),
            headers: {
            },
});

```
3. run ```docker run -d --rm --name cvat_opa_debug -p 8181:8181 -v ${PWD}/cvat/apps/iam/rules:/rules --network=host openpolicyagent/opa:0.45.0-rootless run --server --set=decision_logs.console=true /rules```
4. Open cvat at localhost:3000

### Expected Behaviour

I expect the request to reach the server, but it does't. What should i do to establish connection? 

### Current Behaviour

No request, i have push with error 
![image](https://user-images.githubusercontent.com/64278750/234250404-30535932-785e-4503-b655-90161bd4311d.png) 
 means that my changes compiled
But tracking starts even then i comment line with init tracking.

### Your Environment

- Docker version `docker version` (e.g. Docker 17.0.05): 23.0.3
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 22.10

**Comment by bsekachev** [comment] 2023-04-26 13:16
Please, provide request details from the browser dev tools on Network tab. 

> run docker run -d --rm --name cvat_opa_debug -p 8181:8181 -v ${PWD}/cvat/apps/iam/rules:/rules --network=host openpolicyagent/opa:0.45.0-rootless run --server --set=decision_logs.console=true /rules

It is not a command to rebuild CVAT, it just restart OpenPolicyAgent.

**Comment by zhitm** [comment] 2023-04-26 21:21
> Please, provide request details from the browser dev tools on Network tab.
> 
> > run docker run -d --rm --name cvat_opa_debug -p 8181:8181 -v ${PWD}/cvat/apps/iam/rules:/rules --network=host openpolicyagent/opa:0.45.0-rootless run --server --set=decision_logs.console=true /rules
> 
> It is not a command to rebuild CVAT, it just restart OpenPolicyAgent.

![image](https://user-images.githubusercontent.com/64278750/234704480-e52bfa91-9bd5-44ae-810b-a05a189b7de8.png)
![image](https://user-images.githubusercontent.com/64278750/234704581-b0a58dae-86f8-4252-aa9d-ec9b27e38bcb.png)
Why did tracking started if i commented line initing TrackerMIL and code was executed with changes? How to rebuild cvat?

**Comment by bsekachev** [comment] 2023-04-27 07:56
Add ``docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build``

**Comment by zhitm** [comment] 2023-04-27 18:30
> `docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build`

after that i have 
![image](https://user-images.githubusercontent.com/64278750/234958307-d1c2e66d-a76a-4142-bfb6-2216dee10a04.png)
![image](https://user-images.githubusercontent.com/64278750/234958452-8693a7db-a0b2-4b69-ac6b-cd3c54ac11ec.png)

**Comment by zhitm** [comment] 2023-04-27 18:37
After rebuild (no significant changes were made) i can't open cvat at 8080

**Comment by zhitm** [comment] 2023-04-27 21:10
> `docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build`

Thanks! It rebuilds the project, but error still the same - out of bounds. What should i do to send request correctly? 
![Screenshot from 2023-04-27 23-58-50](https://user-images.githubusercontent.com/64278750/234992034-01e997e5-64de-4a41-8176-8f381e92961f.png)

**Comment by bsekachev** [comment] 2023-05-09 09:18
I see ERR_SSL_PROTOCOL_ERROR when doing a POST request to another host. 
That is not a tracker issue, looks like network configuration problems.

**Comment by bsekachev** [comment] 2023-05-09 09:22
Okay, this is not default configuration. We do not support it out of the box. 
I believe the issue is ralated with that you are trying to do a request from HTTP to HTTPS, but I am not expert here.

I will close the issue because it is a very custom case.

**Closed by bsekachev** 2023-05-09 09:22 UTC
Labels: question
