### ISSUE TITLE
cvat_ui fails building

### ISSUE THREAD

**Issue by gadese** [opencv/cvat#1071] opened 2020-01-17 20:54 UTC
I'm having an issue when running "docker-compose build" during the installation process.

It fails with the following error code:

`Killed`
`npm ERR! code ELIFECYCLE`
`npm ERR! errno 137`
`npm ERR! cvat-ui@0.1.0 build: webpack --config ./webpack.config.js`
`npm ERR! Exit status 137`
`npm ERR! `
`npm ERR! Failed at the cvat-ui@0.1.0 build script.`
`npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

`npm ERR! A complete log of this run can be found in:`
`npm ERR!     /root/.npm/_logs/2020-01-17T20_38_46_284Z-debug.log`
`ERROR: Service 'cvat_ui' failed to build: The command '/bin/sh -c npm run build' returned a non-zero code: 137
`

I'm unsure what to try in order to fix it.

Additionnal info:
This happens on both my main Windows machine (Windows 41 version 1909, OS build 18363.592) and my Ubuntu 18.04 WSL machine.

**Comment by nmanovic** [comment] 2020-01-18 04:05
@gadese ,

Could you please send us the full log? Do you use develop branch? Did you build CVAT on your machine previously or it is the first time?

**Comment by gadese** [comment] 2020-01-20 14:11
Hi @nmanovic ,

I'm using the default develop branch, and it is my first time install CVAT.

However, for the log file, I am unable to locate it. There is no /.npm/ folder under my /root/ directory, and there is no /_logs/ folder under my user's /home/ directory either.

**Comment by bsekachev** [comment] 2020-01-20 17:35
@gadese 

But you have some logs in the terminal before the logs you've sent, right?
One more question is how many RAM does your computer have?

**Comment by gadese** [comment] 2020-01-20 18:14
Yes, here you go:
```
cvat_db uses an image, skipping
cvat_redis uses an image, skipping
Building cvat
Step 1/57 : FROM ubuntu:16.04
 ---> 96da9143fb18
Step 2/57 : ARG http_proxy
 ---> Using cache
 ---> f3b5036d4fff
Step 3/57 : ARG https_proxy
 ---> Using cache
 ---> 1e4b24673f76
Step 4/57 : ARG no_proxy
 ---> Using cache
 ---> da3c33fc4214
Step 5/57 : ARG socks_proxy
 ---> Using cache
 ---> 8ce3d82c29db
Step 6/57 : ARG TZ
 ---> Using cache
 ---> 1ec47cb3619c
Step 7/57 : ENV TERM=xterm     http_proxy=${http_proxy}       https_proxy=${https_proxy}     no_proxy=${no_proxy}     socks_proxy=${socks_proxy}     LANG='C.UTF-8'      LC_ALL='C.UTF-8'     TZ=${TZ}
 ---> Using cache
 ---> b7e5322c977b
Step 8/57 : ARG USER
 ---> Using cache
 ---> 3be2628fae53
Step 9/57 : ARG DJANGO_CONFIGURATION
 ---> Using cache
 ---> a5c7b47210d5
Step 10/57 : ENV DJANGO_CONFIGURATION=${DJANGO_CONFIGURATION}
 ---> Using cache
 ---> 8c77b272f78b
Step 11/57 : RUN apt-get update &&     apt-get install -yq         python-software-properties         software-properties-common         wget &&     add-apt-repository ppa:mc3man/xerus-media -y &&     add-apt-repository ppa:mc3man/gstffmpeg-keep -y &&     apt-get update &&     DEBIAN_FRONTEND=noninteractive apt-get install -yq         apache2         apache2-dev         libapache2-mod-xsendfile         supervisor         ffmpeg         gstreamer0.10-ffmpeg         libldap2-dev         libsasl2-dev         python3-dev         python3-pip         tzdata         unzip         unrar         p7zip-full         git-core         libsm6         libxext6 &&     python3 -m pip install -U pip &&     python3 -m pip install -U setuptools &&     ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime &&     dpkg-reconfigure -f noninteractive tzdata &&     add-apt-repository --remove ppa:mc3man/gstffmpeg-keep -y &&     add-apt-repository --remove ppa:mc3man/xerus-media -y &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> bf38e5cfc2dc
Step 12/57 : ENV USER=${USER}
 ---> Using cache
 ---> 2141037e6a05
Step 13/57 : ENV HOME /home/${USER}
 ---> Using cache
 ---> c2b5eb4f740f
Step 14/57 : WORKDIR ${HOME}
 ---> Using cache
 ---> cd966a0e18d6
Step 15/57 : RUN adduser --shell /bin/bash --disabled-password --gecos "" ${USER}
 ---> Using cache
 ---> 14036f9a7caf
Step 16/57 : COPY components /tmp/components
 ---> Using cache
 ---> 82c0816720e8
Step 17/57 : ARG OPENVINO_TOOLKIT
 ---> Using cache
 ---> 5d48525162f6
Step 18/57 : ENV OPENVINO_TOOLKIT=${OPENVINO_TOOLKIT}
 ---> Using cache
 ---> fc5a578fc55c
Step 19/57 : ENV REID_MODEL_DIR=${HOME}/reid
 ---> Using cache
 ---> 12277b2f9a95
Step 20/57 : RUN if [ "$OPENVINO_TOOLKIT" = "yes" ]; then         /tmp/components/openvino/install.sh &&         mkdir ${REID_MODEL_DIR} &&         wget https://download.01.org/openvinotoolkit/2018_R5/open_model_zoo/person-reidentification-retail-0079/FP32/person-reidentification-retail-0079.xml -O reid/reid.xml &&         wget https://download.01.org/openvinotoolkit/2018_R5/open_model_zoo/person-reidentification-retail-0079/FP32/person-reidentification-retail-0079.bin -O reid/reid.bin;     fi
 ---> Using cache
 ---> 266f6d94be8b
Step 21/57 : ARG TF_ANNOTATION
 ---> Using cache
 ---> 2c73472463c7
Step 22/57 : ENV TF_ANNOTATION=${TF_ANNOTATION}
 ---> Using cache
 ---> 8630d3f2ccd7
Step 23/57 : ENV TF_ANNOTATION_MODEL_PATH=${HOME}/rcnn/inference_graph
 ---> Using cache
 ---> 11f264330c91
Step 24/57 : RUN if [ "$TF_ANNOTATION" = "yes" ]; then         bash -i /tmp/components/tf_annotation/install.sh;     fi
 ---> Using cache
 ---> a620bc8949cb
Step 25/57 : ARG AUTO_SEGMENTATION
 ---> Using cache
 ---> daf819080d2e
Step 26/57 : ENV AUTO_SEGMENTATION=${AUTO_SEGMENTATION}
 ---> Using cache
 ---> 03521f214b29
Step 27/57 : ENV AUTO_SEGMENTATION_PATH=${HOME}/Mask_RCNN
 ---> Using cache
 ---> ea2672a4503d
Step 28/57 : RUN if [ "$AUTO_SEGMENTATION" = "yes" ]; then     bash -i /tmp/components/auto_segmentation/install.sh;     fi
 ---> Using cache
 ---> 0436618315e6
Step 29/57 : ARG WITH_TESTS
 ---> Using cache
 ---> 851b5a2c0174
Step 30/57 : RUN if [ "$WITH_TESTS" = "yes" ]; then         wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - &&         echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google-chrome.list &&         wget -qO- https://deb.nodesource.com/setup_9.x | bash - &&         apt-get update &&         DEBIAN_FRONTEND=noninteractive apt-get install -yq             google-chrome-stable             nodejs &&         rm -rf /var/lib/apt/lists/*;         mkdir tests && cd tests && npm install             eslint             eslint-detailed-reporter             karma             karma-chrome-launcher             karma-coveralls             karma-coverage             karma-junit-reporter             karma-qunit             qunit;         echo "export PATH=~/tests/node_modules/.bin:${PATH}" >> ~/.bashrc;     fi
 ---> Using cache
 ---> 7c9e49abdb26
Step 31/57 : COPY cvat/requirements/ /tmp/requirements/
 ---> Using cache
 ---> 21eae4382982
Step 32/57 : COPY supervisord.conf mod_wsgi.conf wait-for-it.sh manage.py ${HOME}/
 ---> Using cache
 ---> 2961c89f9c36
Step 33/57 : RUN python3 -m pip install --no-cache-dir -r /tmp/requirements/${DJANGO_CONFIGURATION}.txt
 ---> Using cache
 ---> bf46fe7f2884
Step 34/57 : RUN python3 -m pip install --no-cache-dir pycocotools==2.0.0
 ---> Using cache
 ---> 65a1821d9e5e
Step 35/57 : RUN apt-get update &&     apt-get install -y ssh netcat-openbsd git curl zip  &&     wget -qO /dev/stdout https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash &&     apt-get install -y git-lfs &&     git lfs install &&     rm -rf /var/lib/apt/lists/* &&     if [ -z ${socks_proxy} ]; then         echo export "GIT_SSH_COMMAND=\"ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30\"" >> ${HOME}/.bashrc;     else         echo export "GIT_SSH_COMMAND=\"ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o ProxyCommand='nc -X 5 -x ${socks_proxy} %h %p'\"" >> ${HOME}/.bashrc;     fi
 ---> Using cache
 ---> 301d15d08eba
Step 36/57 : RUN apt-get update &&     apt install -y poppler-utils &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 8925b6003a7b
Step 37/57 : ARG CUDA_SUPPORT
 ---> Using cache
 ---> fde486380bb7
Step 38/57 : ENV CUDA_SUPPORT=${CUDA_SUPPORT}
 ---> Using cache
 ---> c3ec327b9818
Step 39/57 : RUN if [ "$CUDA_SUPPORT" = "yes" ]; then         /tmp/components/cuda/install.sh;     fi
 ---> Using cache
 ---> 0d8473c45e77
Step 40/57 : ARG WITH_DEXTR
 ---> Using cache
 ---> 2c2e1119d0b2
Step 41/57 : ENV WITH_DEXTR=${WITH_DEXTR}
 ---> Using cache
 ---> 989e5eefcfc0
Step 42/57 : ENV DEXTR_MODEL_DIR=${HOME}/dextr
 ---> Using cache
 ---> c220242dc0d7
Step 43/57 : RUN if [ "$WITH_DEXTR" = "yes" ]; then         mkdir ${DEXTR_MODEL_DIR} -p &&         wget https://download.01.org/openvinotoolkit/models_contrib/cvat/dextr_model_v1.zip -O ${DEXTR_MODEL_DIR}/dextr.zip &&         unzip ${DEXTR_MODEL_DIR}/dextr.zip -d ${DEXTR_MODEL_DIR} && rm ${DEXTR_MODEL_DIR}/dextr.zip;     fi
 ---> Using cache
 ---> 887ce59d0988
Step 44/57 : COPY ssh ${HOME}/.ssh
 ---> Using cache
 ---> f793c5504194
Step 45/57 : COPY utils ${HOME}/utils
 ---> Using cache
 ---> 65b7242d83e0
Step 46/57 : COPY cvat/ ${HOME}/cvat
 ---> Using cache
 ---> b89df6c25212
Step 47/57 : COPY cvat-core/ ${HOME}/cvat-core
 ---> Using cache
 ---> 45b702be60b2
Step 48/57 : COPY tests ${HOME}/tests
 ---> Using cache
 ---> 7e4513850792
Step 49/57 : COPY datumaro/ ${HOME}/datumaro
 ---> Using cache
 ---> e00cab96711d
Step 50/57 : RUN sed -r "s/^(.*)#.*$/\1/g" ${HOME}/datumaro/requirements.txt | xargs -n 1 -L 1 python3 -m pip install --no-cache-dir
 ---> Using cache
 ---> 54a1e540c582
Step 51/57 : RUN patch --binary -p1 < ${HOME}/cvat/apps/engine/static/engine/js/3rdparty.patch
 ---> Using cache
 ---> 471779451f23
Step 52/57 : RUN chown -R ${USER}:${USER} .
 ---> Using cache
 ---> db730e95ec45
Step 53/57 : USER ${USER}
 ---> Using cache
 ---> c41322e5985a
Step 54/57 : RUN mkdir data share media keys logs /tmp/supervisord
 ---> Using cache
 ---> 9e123653590c
Step 55/57 : RUN python3 manage.py collectstatic
 ---> Using cache
 ---> bebc58b8c013
Step 56/57 : EXPOSE 8080 8443
 ---> Using cache
 ---> f82be760d2e1
Step 57/57 : ENTRYPOINT ["/usr/bin/supervisord"]
 ---> Using cache
 ---> 054c882789e9

Successfully built 054c882789e9
Successfully tagged cvat:latest
Building cvat_ui
Step 1/28 : FROM ubuntu:18.04 AS cvat-ui
 ---> ccc6e87d482b
Step 2/28 : ARG http_proxy
 ---> Using cache
 ---> 76eef27fb4ff
Step 3/28 : ARG https_proxy
 ---> Using cache
 ---> 144fc7b9a908
Step 4/28 : ARG no_proxy
 ---> Using cache
 ---> af5ae2c9994c
Step 5/28 : ARG socks_proxy
 ---> Using cache
 ---> 75891c88730d
Step 6/28 : ARG REACT_APP_API_PORT
 ---> Using cache
 ---> 3e09220c4503
Step 7/28 : ARG REACT_APP_API_PROTOCOL
 ---> Using cache
 ---> da1182fe1063
Step 8/28 : ARG REACT_APP_API_HOST
 ---> Using cache
 ---> 8aba2c9889b6
Step 9/28 : ENV TERM=xterm     http_proxy=${http_proxy}       https_proxy=${https_proxy}     no_proxy=${no_proxy}     socks_proxy=${socks_proxy}
 ---> Using cache
 ---> 6a4884ec4b80
Step 10/28 : ENV LANG='C.UTF-8'      LC_ALL='C.UTF-8'
 ---> Using cache
 ---> 03dea83c9d5e
Step 11/28 : RUN apt update && apt install -yq nodejs npm curl &&     npm install -g n && n 10.16.3
 ---> Using cache
 ---> fc7bdfaf4d6d
Step 12/28 : RUN mkdir /tmp/cvat-ui /tmp/cvat-core /tmp/cvat-canvas
 ---> Using cache
 ---> f201d4e4ba48
Step 13/28 : COPY cvat-core/package*.json /tmp/cvat-core/
 ---> Using cache
 ---> 7e58a0817f7b
Step 14/28 : COPY cvat-canvas/package*.json /tmp/cvat-canvas/
 ---> Using cache
 ---> 18d01818bc4a
Step 15/28 : COPY cvat-ui/package*.json /tmp/cvat-ui/
 ---> Using cache
 ---> e4c6d18ac782
Step 16/28 : WORKDIR /tmp/cvat-core/
 ---> Using cache
 ---> 6f3a3ad9dca4
Step 17/28 : RUN npm install
 ---> Using cache
 ---> 9cda6ddf4e74
Step 18/28 : WORKDIR /tmp/cvat-canvas/
 ---> Using cache
 ---> 75ca55c50cb9
Step 19/28 : RUN npm install
 ---> Using cache
 ---> 6d58e67f53fc
Step 20/28 : WORKDIR /tmp/cvat-ui/
 ---> Using cache
 ---> caa243503cc5
Step 21/28 : RUN npm install
 ---> Using cache
 ---> a9f2321a36ea
Step 22/28 : COPY cvat-core/ /tmp/cvat-core/
 ---> Using cache
 ---> df04b0ac9115
Step 23/28 : COPY cvat-canvas/ /tmp/cvat-canvas/
 ---> Using cache
 ---> ad0db886d261
Step 24/28 : COPY cvat-ui/ /tmp/cvat-ui/
 ---> Using cache
 ---> b837b258c292
Step 25/28 : RUN npm run build
 ---> Running in cf7d25d7e380

> cvat-ui@0.1.0 build /tmp/cvat-ui
> webpack --config ./webpack.config.js

Killed
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! cvat-ui@0.1.0 build: `webpack --config ./webpack.config.js`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the cvat-ui@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-20T18_05_46_189Z-debug.log
ERROR: Service 'cvat_ui' failed to build: The command '/bin/sh -c npm run build' returned a non-zero code: 137

```

**Comment by bsekachev** [comment] 2020-01-20 18:19
@gadese 

And what about RAM size?

**Comment by gadese** [comment] 2020-01-20 19:50
I'm running on 16 Gb

**Comment by nmanovic** [comment] 2020-01-21 07:34
@gadese , google says that the most probable reason is RAM. Look here: https://github.com/nimiq/core-js/issues/295.

Please to restart your computer and try again.

**Comment by vinorth05** [comment] 2020-01-21 09:50
I had exactly the same error before when I had 2gb ram on my server.
Then it worked perfectly when I upgraded to 4gb ram.

**Comment by gadese** [comment] 2020-01-21 14:24
> @gadese , google says that the most probable reason is RAM. Look here: [nimiq/core-js#295](https://github.com/nimiq/core-js/issues/295).
> 
> Please to restart your computer and try again.

I really doubt it's my RAM in this case. I've restarted my computer and tried again, and I get the same error. I've even tried to re-clone the repo after a computer reboot and build from scratch and I get the same error.

I've tried running "free -m" before running "docker-compose build" to make sure I had enough RAM, and as you can see I still have ~12 Gb of RAM left.

![image](https://user-images.githubusercontent.com/42775066/72812522-a81fb080-3c2f-11ea-8f80-4b9df85c479d.png)

**Comment by bsekachev** [comment] 2020-01-22 17:12
@gadese 

Could you try to remove all steps after ``COPY cvat-ui/ /tmp/cvat-ui/`` from ``Dockerfile.ui``, create a docker container from the image (with docker run), go there, and try to do ``npm build`` manually?

We can provide some commands if you need more assistance.

**Comment by gadese** [comment] 2020-01-22 19:06
> We can provide some commands if you need more assistance.

Yes please, what commands should I run?

**Comment by bsekachev** [comment] 2020-01-23 10:48
@gadese 

1) Try to build
2) Get error
3) Enter: ``docker run -it <hash> bash``
4) Enter: ``cd /tmp/cvat-ui && npm run build``

< hash > - is a hash of the latest successful docker layer

For example I have hash ``ce74799d961a`` (I simulated built failing):
![Screenshot from 2020-01-23 13-39-58](https://user-images.githubusercontent.com/40690378/72978040-bcf27480-3de6-11ea-9cd4-f801fc7d7ca5.png)

So, if you get error again, you can go and see the full log:
```
/root/.npm/_logs/2020-01-20T18_05_46_189Z-debug.log # for example here
```

**Comment by gadese** [comment] 2020-01-23 14:06
@bsekachev 

Here is the result. (Same error)

![image](https://user-images.githubusercontent.com/42775066/72991105-5574fe80-3dbf-11ea-942b-5e5d0425112c.png)

However, as I've said before, there is no /.npm/ folder under my /root/ directory and I can not find the logs, so it seems the logs are not being saved. I have the sudo rights on my machine, but my user isn't the root user. Could that be an issue?

**Comment by bsekachev** [comment] 2020-01-23 15:06
@gadese 

Are you checking exact in container (in docker OS) or on your host OS?

**Comment by gadese** [comment] 2020-01-23 15:59
You were right, I was looking at my host OS rather than the container. Here's the full log obtained with tail

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle cvat-ui@0.1.0~prebuild: cvat-ui@0.1.0
6 info lifecycle cvat-ui@0.1.0~build: cvat-ui@0.1.0
7 verbose lifecycle cvat-ui@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle cvat-ui@0.1.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/tmp/cvat-ui/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle cvat-ui@0.1.0~build: CWD: /tmp/cvat-ui
10 silly lifecycle cvat-ui@0.1.0~build: Args: [ '-c', 'webpack --config ./webpack.config.js' ]
11 silly lifecycle cvat-ui@0.1.0~build: Returned: code: 137  signal: null
12 info lifecycle cvat-ui@0.1.0~build: Failed to exec build script
13 verbose stack Error: cvat-ui@0.1.0 build: `webpack --config ./webpack.config.js`
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid cvat-ui@0.1.0
15 verbose cwd /tmp/cvat-ui
16 verbose Linux 4.19.27-linuxkit
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v10.16.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 137
22 error cvat-ui@0.1.0 build: `webpack --config ./webpack.config.js`
22 error Exit status 137
23 error Failed at the cvat-ui@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 137, true ]

```

**Comment by bsekachev** [comment] 2020-01-24 16:45
@gadese 

Hmm.. These logs don't provide us useful information anyway.
Two different machines, ~12 GB RAM, the same error. Strangely. 
Does it happen in docker only? Did you try to install CVAT locally without docker?
Maybe the reason is your network, or mirrors where npm finds packages.
I just cannot reproduce it.

**Comment by gadese** [comment] 2020-01-24 17:30
@bsekachev 

I'm not sure how to install it without docker but I can definitely try. Would you mind guiding me through the steps?

**Comment by bsekachev** [comment] 2020-01-24 17:42
@gadese,
Sure. There is a manual in the CONTRIBUTING.md file. You can find it in the repository root.

**Comment by gadese** [comment] 2020-01-24 18:17
@bsekachev it seems to have install properly.

However, when I go to the localhost address on Chrome, I get the following error message

![image](https://user-images.githubusercontent.com/42775066/73093042-bd087800-3eab-11ea-8cd7-acaaf25bd8b7.png)

And if I try to register an account, I get another error

![image](https://user-images.githubusercontent.com/42775066/73093109-dc9fa080-3eab-11ea-8789-9bd7c15abdcf.png)

So I guess it's an issue with my network?

**Comment by bsekachev** [comment] 2020-01-24 19:54
@gadese 

It is expected, because you only run nodejs UI debug server (which serves the browser single page application).
If you also run django CVAT REST API server (as manual says), you get it working. 

But it's only debug environment. I don't know why it works for you locally, but doesn't work in docker.

**Comment by gadese** [comment] 2020-01-24 22:36
Which part of the manual refers to the django REST API server? I can't find it.

Does it being only a debug environment mean I won't be able to use the basic cvat functionalities?

**Comment by bsekachev** [comment] 2020-01-25 08:55
@gadese 
> Which part of the manual refers to the django REST API server? I can't find it.

Running ``server: debug`` configuration in the VS Code. 
Of course, you can do it out of VS Code at all, by running several processes in terminals manually:

```
python manage.py runserver --noreload --insecure 127.0.0.1:7000
python manage.py rqworker default --worker-class cvat.simpleworker.SimpleWorker 
python manage.py rqworker low --worker-class cvat.simpleworker.SimpleWorker
```

But other prerunning steps must be done (dependencies installation and .venv with at least python 3.5). 

> Does it being only a debug environment mean I won't be able to use the basic cvat functionalities?

You are able to use all basic functionalities of CVAT. Moreover, you can use almost all additional components if you setup them (see [Additional component installation section](https://github.com/opencv/cvat/blob/develop/CONTRIBUTING.md#how-to-setup-additional-components-in-development-environment)).

The main difference here is application performance. Python & JS scripts works slower in debug (I cant say exactly how much), but it's a fact. And we use trivial database here: SQLite instead of Postgres.

**Comment by gadese** [comment] 2020-01-27 14:34
Thanks for the detailed description. However, I can't seem to get it to work in VS code.

I've installed VS code and the Debugger for Chrome and Python extensions, reloaded VS code. But I can't seem to find the server debug configuration.

Also, when I  try the commands above, I get

`python manage.py rqworker default --worker-class cvat.simpleworker.SimpleWorker `

Error:
`Error 111 connecting to localhost:6379. Connection refused.
`

**Comment by bsekachev** [comment] 2020-01-27 16:02
@gadese 
Could you attach a screenshot of VS code?

>  Error 111 connecting to localhost:6379. Connection refused.  
Looks like you haven't installed redis

**Comment by gadese** [comment] 2020-01-27 16:24
If I open the ./.env/ folder:

![image](https://user-images.githubusercontent.com/42775066/73192763-858e0b80-40f7-11ea-99d7-02c6eb020deb.png)

It then opens the same Google Chrome page as before, with the same error messages:

![image](https://user-images.githubusercontent.com/42775066/73192792-9048a080-40f7-11ea-871b-cf428dafbe77.png)

If I try to open cvat folder in VS code:

![image](https://user-images.githubusercontent.com/42775066/73191882-3b585a80-40f6-11ea-93e8-86f94d96d3a5.png)

If I press F5 from cvat folder:

![image](https://user-images.githubusercontent.com/42775066/73191943-52974800-40f6-11ea-9197-fa96092df551.png)

**Comment by bsekachev** [comment] 2020-01-27 16:38
@gadese 

Opened root cvat folder
![Screenshot from 2020-01-27 19-32-35](https://user-images.githubusercontent.com/40690378/73193993-82693e80-413c-11ea-93f6-dc935d01ce89.png)

**Comment by gadese** [comment] 2020-01-27 17:09
I don't have any of these options

![image](https://user-images.githubusercontent.com/42775066/73196459-9c376100-40fd-11ea-9d56-f7d00eecc80c.png)

**Comment by bsekachev** [comment] 2020-01-27 17:35
@gadese 

If you can't run worker youself (by using ``python manage.py rqworker default --worker-class cvat.simpleworker.SimpleWorker``) VSCode anyway will not be able to do it > you have some issues with redis. As I said it seems to be you haven't installed or run it. 

I see you are using windows subsystem for linux. 
Actually it can be a root of your issues.
We do not work with it and don't guarantee CVAT works correctly in this case.

**Comment by gadese** [comment] 2020-01-29 18:51
@bsekachev I'm aware WSL could be an issue but I know it should work because a coworker got it to work.
However, as I said I've also tried installing cvat directly on the Windows machine, using Docker for Windows and I still get the initial error message.

Out of curiosity, is your Docker using Linux containers? Or Windows containers?

![containeroption](https://user-images.githubusercontent.com/42775066/73387277-51088400-429e-11ea-9329-7256514c58f3.png)

**Comment by ixtiyoruz** [comment] 2020-02-04 01:45
in my case, the error is the following:
Running hooks in /etc/ca-certificates/update.d...
done.
/usr/local/bin/n -> /usr/local/lib/node_modules/n/bin/n
/usr/local/lib
?붴?? n@6.2.0

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 72, in main
  File "compose\cli\main.py", line 128, in perform_command
  File "compose\cli\main.py", line 303, in build
  File "compose\project.py", line 403, in build
  File "compose\project.py", line 385, in build_service
  File "compose\service.py", line 1110, in build
  File "compose\progress_stream.py", line 30, in stream_output
  File "compose\progress_stream.py", line 95, in print_output_event
  File "compose\progress_stream.py", line 13, in write_to_stream
  File "codecs.py", line 370, in write
  File "site-packages\colorama\ansitowin32.py", line 41, in write
  File "site-packages\colorama\ansitowin32.py", line 162, in write
  File "site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
  File "site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
IOError: [Errno 0] Error
[2276] Failed to execute script docker-compose

**Comment by bsekachev** [comment] 2020-08-26 14:19
I will close the issue for now, do not hesitate reopen it if you still have questions

**Closed by bsekachev** 2020-08-26 14:19 UTC
Labels: question

**Comment by laverntulin** [comment] 2020-11-15 12:16
> @gadese ,
> 
> Could you please send us the full log? Do you use develop branch? Did you build CVAT on your machine previously or it is the first time?

i have the same problem what will i do

**Comment by zhouyuangan** [comment] 2021-02-05 06:06
same problem
