### ISSUE TITLE
Can't load the job having 2627 images

### ISSUE THREAD

**Issue by spt3009** [opencv/cvat#5898] opened 2023-03-22 06:27 UTC
### My actions before raising this issue
I had annotated approximately 1300 images, then I did control+S and closed the window. I am trying to open the job but just keeps loading.....

frames = 0-2625
segment size = 2626
image quality = 70

**Comment by nmanovic** [comment] 2023-03-22 07:19
@spt3009 , could you please provide more information? Which version of CVAT do you use (CVAT.ai cloud or on-prem)? If you use self-hosted version is it the latest release CVAT v2.4.0?

We just need steps to reproduce the issue on our side.

**Comment by spt3009** [comment] 2023-03-22 07:23
Computer Vision Annotation Tool
CVAT is completely re-designed and re-implemented version of Video Annotation Tool from Irvine, California tool. It is free, online, interactive video and image annotation tool for computer vision. It is being used by our team to annotate million of objects with different properties. Many UI and UX decisions are based on feedbacks from professional data annotation team.

Server version: 2.4

Core version: 8.2.0

Canvas version: 2.16.2

UI version: 1.49.3

**Comment by spt3009** [comment] 2023-03-22 07:24
Project #20542 created by shivam4 on March 20th 2023

**Comment by spt3009** [comment] 2023-03-22 07:28
Computer Vision Annotation Tool
CVAT is completely re-designed and re-implemented version of Video Annotation Tool from Irvine, California tool. It is free, online, interactive video and image annotation tool for computer vision. It is being used by our team to annotate million of objects with different properties. Many UI and UX decisions are based on feedbacks from professional data annotation team.

Server version: 2.4

Core version: 8.2.0

Canvas version: 2.16.2

UI version: 1.49.3

Project #20542 created by shivam4 on March 20th 2023

**Comment by outforz** [comment] 2023-03-22 11:14
You must add your images to a .zip archive , and upload it.

**Comment by spt3009** [comment] 2023-03-22 11:16
so, I will I have to delete the task and re-annotate the images ?

**Comment by spt3009** [comment] 2023-03-22 11:17
so, I will I have to delete the task and re-annotate the images ?

**Comment by outforz** [comment] 2023-03-22 11:19
I think I misunderstood your question!
In your case, I would recommend stopping docker and restarting it. 
I have encountered a similar situation.

**Comment by spt3009** [comment] 2023-03-22 11:21
i am not using docker.

**Comment by zhiltsov-max** [comment] 2023-04-05 07:59
@jhaux-askui, it seems like a different problem with the space left on the server. If the server is under your control, please check if there is enough disk space, and it is allowed for use by the containers.

@spt3009, #5974 may fix the problem once merged. It addresses long responses from the server on the job loading, leading to timeout errors.

**Comment by jhaux-askui** [comment] 2023-04-05 10:16
Thanks for the quick answer @zhiltsov-max!

I'll check out if the servers are managed by us.

Today when I tried to load the job I got this error:
```
Error: Request failed with status code 500. "\n<!doctype html>\n<html lang="en">\n<head>\n <title>Server Error (500)</title>\n</head>\n<body>\n <h1>Server Error (500)</h1><p></p>\n</body>\n</html>\n".
```
Then after refreshing it actually worked and loaded everything! It might be because I have a better internet connection today.

I hope that helps :slightly_smiling_face:

**Comment by azhavoro** [comment] 2023-04-21 11:58
> I have a similar problem. After having annotated 1500 images I cannot open the job anymore. In the console I get only a timeout error.
> 
> If I want to export the annotations from jobs page I get the following error:
> 
> ```
> Could not export dataset for the job xxx
> 
> Error: Request failed with status code 500. "django.db.utils.OperationalError: could not resize shared memory segment "/PostgreSQL.1284416766" to 33554432 bytes: No space left on device\nCONTEXT: parallel worker\n\n".
> ```
> 
> It looks like there is no space left on the servers?
> 
> Is there any way I can debug what is going wrong? I would really like to not lose those annotations.

Try to increase shared memory size for cvat_db container https://docs.docker.com/compose/compose-file/compose-file-v3/#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir

**Comment by bsekachev** [comment] 2023-05-24 12:34
I hope the issue was solved. Do not hesitate to reopen in any case.

**Closed by bsekachev** 2023-05-24 12:34 UTC
Labels: need info
