### ISSUE TITLE
Build error help

### ISSUE THREAD

**Issue by onoderay** [opencv/cvat#1897] opened 2020-07-14 10:28 UTC
my environment is WSL2 (Ubuntu 20.04)
```
docker-compose build
```
Error is shown below

```
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/p/po-debconf/po-debconf_1.0.19_all.deb  Hash Sum mismatch

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Fetched 185 MB in 11min 48s (260 kB/s)
ERROR: Service 'cvat' failed to build: The command '/bin/sh -c apt-get update &&     apt-get --no-install-recommends install -yq         software-properties-common &&     add-apt-repository ppa:mc3man/xerus-media -y &&     add-apt-repository ppa:mc3man/gstffmpeg-keep -y &&     apt-get update &&     DEBIAN_FRONTEND=noninteractive apt-get --no-install-recommends install -yq         apache2         apache2-dev         apt-utils         build-essential         libapache2-mod-xsendfile         supervisor         ffmpeg         gstreamer0.10-ffmpeg         libavcodec-dev         libavdevice-dev         libavfilter-dev         libavformat-dev         libavutil-dev         libldap2-dev         libswresample-dev         libswscale-dev         libldap2-dev         libsasl2-dev         pkg-config         python3-dev         python3-pip         tzdata         p7zip-full         git         ssh         poppler-utils         curl &&     curl https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash &&     apt-get --no-install-recommends install -y git-lfs && git lfs install &&     python3 -m pip install --no-cache-dir -U pip==20.0.1 setuptools>=49.1.0 &&     ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime &&     dpkg-reconfigure -f noninteractive tzdata &&     add-apt-repository --remove ppa:mc3man/gstffmpeg-keep -y &&     add-apt-repository --remove ppa:mc3man/xerus-media -y &&     rm -rf /var/lib/apt/lists/* &&     echo 'application/wasm wasm' >> /etc/mime.types' returned a non-zero code: 1
```

**Comment by azhavoro** [comment] 2020-07-14 17:33
@onoderay Hi, please don't ignore the issue template.
Looks like there is network issue, could you try re-build?

**Comment by azhavoro** [comment] 2020-07-28 14:00
@onoderay I'll close this issue. Feel free to re-open if the issue is still actual for you.

**Closed by azhavoro** 2020-07-28 14:00 UTC
