### ISSUE TITLE
Error: Could not create the task | Azure Blob Storage

### ISSUE THREAD

**Issue by Alex97schmid-zeiss** [opencv/cvat#4998] opened 2022-09-27 09:36 UTC
### My actions before raising this issue
**I'm currently configuring a cvat project / task with an azure blob storage.**
So far, I was able to add the cloud storage. It already shows me the images in the cloud storage preview. 

![image](https://user-images.githubusercontent.com/63061479/192499793-d4b59b82-dc25-4a24-a38e-b8b3f25a25df.png)

### Current Behaviour
But unfortunately, when I'm creating a new task, it return me an error: _Could not create the task_. Opening the browser console gives me more details: _Could not create the task on the server. TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'._

![image](https://user-images.githubusercontent.com/63061479/192500436-fae34ba7-5615-49d1-88cd-5ef8d9efa4b4.png)

### Possible Solution
**Is there maybe something wrong with my manifest.json file?**
{"version":"1.0"} {"type":"images"} {"name":"clinical_data/image_data/ISB/048/a_374360619_10485316_ISconf","extension":".jpg","width":1920,"height":1080}

### Context
If I'm creating the task with local added images, if works normally, so definitely an issue with the blob-storage configuration. 
Did somebody face a similar error in the past?

**Comment by ShakhanovG** [comment] 2022-11-09 07:53
I had the same issue with my local minio S3 storage. I tried to attach the S3 bucket to CVAT.

There were 2 test images - image1.png , image2.png

And actually I tried to create a manifest file to upload these images along with it to the trash using this [instruction](https://opencv.github.io/cvat/docs/manual/advanced/dataset_manifest/ ). and after executing the **create.py** script mentioned in the docs, I got the generated json and **[jsonl](https://manifold.net/doc/mfd9/jsonl.htm#:~:text=JSONL%20is%20a%20text%2Dbased,import%20and%20link%20JSONL%20files.)** (not a JSON) files.

1. **manifest.jsonl** content: 
{"version":"1.1"}
{"type":"images"}
{"name":"Image1","extension":".png","width":2560,"height":1080,"meta":{"related_images":[]},"checksum":"3155e9dca73650b59ebc428bae63894d"}
{"name":"Image2","extension":".png","width":2560,"height":1080,"meta":{"related_images":[]},"checksum":"f41852f49e6a75d9a7648a4aa7bc8df0"}

2. **index.json** with the following content {"0":36,"1":175} for 2 images

And after I tried to upload these files (json and jsonl with the picks mentioned before) from attached cloud storage to a new task and it worked for me.

**Possible Solution**
Probably the problem was related to manifest file format or values inside the **jsonl** file. Try to check it (change json to correct **jsonl** format and check values like "name", "type" and so on ) . Thanks . Hope it help you.

**Comment by nmanovic** [comment] 2023-01-05 16:05
@Alex97schmid-zeiss , please let us know if you still have the issue. I will close the issue for now. Don't hesitate to reopen it if you send us steps to reproduce it.

**Closed by nmanovic** 2023-01-05 16:05 UTC
