### ISSUE TITLE
Polygons to bounding boxes

### ISSUE THREAD

**Issue by SantiHM23** [opencv/cvat#1354] opened 2020-04-03 14:15 UTC
Hi! 
In the task I am doing, I run a person detector before using your tool in order to already have most of the bounding boxes that I will need for annotation, and I save them in a .json file in the proper format and upload them. When uploading the file, the bounding boxes are uploaded as polygons instead of boxes. Actually, if I manually draw a box in the CVAT, save it, download as a json and re-upload that same file without modifying anything, the bounding boxes are also uploaded as polygons instead of boxes. Is there anyway to upload them as boxes? From what I have read in the documentation and the issues, I understand that it is much more convenient for using interpolation, which is something I believe I will need in order to mantain the identity of the person through consecutive frames.
Thank you for your help!

**Comment by zhiltsov-max** [comment] 2020-04-03 15:03
Hello. I suppose that you are using COCO format. In this format annotations are imported as polygons if there is `segmentation` field not empty, otherwise they are imported as boxes if there is `bbox` field. Try to leave only `bbox` field or use another format, for instance - Pascal VOC. If there are any troubles with these options, you can try to use Datumaro to prepare annotations in CVAT format and import them.

**Comment by SantiHM23** [comment] 2020-04-03 15:15
Hi! When uploading it with the segmentation field empty, the bounding boxes would directly not appear. I will try with other formats as you suggested. Thsank you!

**Comment by zhiltsov-max** [comment] 2020-04-03 15:29
Is it possible that coco annotations have no image info?

**Comment by SantiHM23** [comment] 2020-04-03 16:00
I have the file with both image names and ids, and the annotations linked to those image ids, and still nothing appears on screen.

**Comment by zhiltsov-max** [comment] 2020-04-03 16:19
Please also check if annotations have labels and the task have same labels defined.

**Comment by SantiHM23** [comment] 2020-04-03 16:27
Yes to both. Maybe it is a problem on how to leave "segmentation" field empty. I tried with:
"segmentation": [[]],
"segmentation": [],
"segmentation": ,
"segmentation": "",

Maybe it should be done in a different way, or not writing that field at all?

**Comment by zhiltsov-max** [comment] 2020-04-03 16:43
The implementation is [here](https://github.com/opencv/cvat/blob/develop/datumaro/datumaro/plugins/coco_format/extractor.py#L148). I don't think this part fails to read annotations.

**Comment by zhiltsov-max** [comment] 2020-04-17 14:19
Tried to reproduce and failed - if `segmentation` is `[]`, annotations are imported as rectangles. Closing, feel free to reopen if the issue persists.

**Closed by zhiltsov-max** 2020-04-17 14:19 UTC
Labels: bug

**Comment by tjsaaby** [comment] 2021-05-23 06:27
In my case even if segmentation is [] as @zhiltsov-max, I also get much bigger boundingboxes as I assume its because it its uploaded as polygons? 

sample from uploaded annotation file:     
"annotations": [
        {
            "id": 1,
            "image_id": 1,
            "category_id": 27.0,
            "segmentation": [],
            "area": 70257.18194521032,
            "bbox": [
                96.5731201171875,
                256.0813903808594,
                197.76092529296875,
                355.2632141113281
            ],
            "iscrowd": 0
        },
