### ISSUE TITLE
Tags for projects and tasks

### ISSUE THREAD

**Issue by igorruy** [opencv/cvat#7349] opened 2024-01-11 14:05 UTC
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Is your feature request related to a problem? Please describe.

This request is related to a new resource for CVAT that aims to assist in the management of projects and activities.

### Describe the solution you'd like

I am a Project Manager and coordinate computer vision model development projects.

As the number of tasks and projects in CVAT increases, it becomes more complex to organize them just by names, responsible persons and date of creation, considering that it is not possible to categorize them. A feature that can be very useful, both for projects and activities, would be the possibility of inserting tags, making it possible to filter and categorize projects and activities according to the tags

My proposal is that the tags are registered for the workspace, being applicable to both activities and projects, without distinction within the same workspace.

**Comment by pktiuk** [comment] 2024-02-02 12:14
I think this issue can be closed, because it is a clear duplicate of: https://github.com/opencv/cvat/issues/6557

**Comment by igorruy** [comment] 2024-02-02 12:19
Yes, I will close

**Closed** 2024-02-02 12:34 UTC
Labels: enhancement
