### ISSUE TITLE
CVAT Buffering For Extended Periods Of Time

### ISSUE THREAD

**Issue by ObjectMuffin** [opencv/cvat#4687] opened 2022-06-10 14:48 UTC
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

Hello! I am part of an innovation team at a public organization currently using CVAT for object tracking. There seems to be a very pressing issue: frames may take up to 5+ minutes to load no matter the internet speed or bandwidth. When you are dealing with 30,000 frames of work to get through this can be very tedious. The videos are uploaded as Mp4 files and are around 20 minutes each. We have tried to cut the video in half but the same issue keeps happening. Is there anything to do to stop this issue from happening? Due to legal reasons, I am not allowed to share the videos as they are public information. 
### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment] 2022-06-10 14:50
@ObjectMuffin , can you reproduce the issue on a public video? What is the resolution of your videos?

**Comment by ObjectMuffin** [comment] 2022-06-10 14:52
The resolution is set at 70.

**Comment by nmanovic** [comment] 2022-06-10 14:53
@ObjectMuffin , I mean what is the width and height of the video?

**Comment by nmanovic** [comment] 2022-06-10 14:58
#4611

**Comment by ObjectMuffin** [comment] 2022-06-10 15:38
That problem has been fixed for login. As for the width and height of the videos they are 389x782 pixels

**Comment by MosesNjau** [comment] 2022-06-10 20:30
The issue for login and being signed out is back, am currently experiencing issues.

**Comment by strickvl** [comment] 2022-06-11 11:42
Currently also experiencing issues logging in.

**Comment by zhiltsov-max** [comment] 2022-10-25 17:36
Hi, please make sure the videos were created with the `use chunks` option enabled: 
https://opencv.github.io/cvat/docs/manual/basics/creating_an_annotation_task/#use-zipvideo-chunks
and `use cache` - disabled. Also, try to reduce the `chunk_size` to lower values (read more here: https://opencv.github.io/cvat/docs/manual/basics/creating_an_annotation_task/#chunk-size). I'll close the issue, feel free to reopen if the problem is still actual. Please also try to upgrade the server to the latest version.

**Closed by zhiltsov-max** 2022-10-25 17:36 UTC
