### ISSUE TITLE
Issue with writing custom models for auto annotation on CVAT

### ISSUE THREAD

**Issue by himanshudw** [opencv/cvat#4942] opened 2022-09-13 14:24 UTC
### My actions before raising this issue
- Read https://stackoverflow.com/questions/48719921/pull-access-denied-repository-does-not-exist-or-may-require-docker-login
- Read https://forums.docker.com/t/docker-error-response-from-daemon-pull-access-denied-for-docker-poject-repository-does-not-exist-or-may-require-docker-login-denied-requested-access-to-the-resource-is-denied/126237/3

The code for auto annotation worked manually for my case but after doing docker rmi image -a  and updating the docker it has stopped working and while deploying my custom model exits without building the image itself with error as described below
![image](https://user-images.githubusercontent.com/61216926/189923234-3e72cf78-fe93-4332-92b5-c8e4d138c056.png)
Faster RCNN gets deployed without an error.

### Expected Behaviour
The command should provide with the auto annotation function and the deployment for the function should succeed.

### Current Behaviour
The function.yml file for the custom model has a base image as openvino_custom which is not there in the docker images -a 
and is shown as below 
![image](https://user-images.githubusercontent.com/61216926/189926322-0eaaae7d-9ac3-4cf7-81cd-41f7b0e502c2.png)

### Possible Solution
The base image that need to be used for the custom model deployment can be used. Also a place where can it be found and placed under which folder

### Context
The aim is to make auto annotation work with nucilo serverless fucntion

### Your Environment
Your Environment
Docker version docker version :20.10.17
Operating System and version :Linux
CVAT Version :dev

**Comment by yasakova-anastasia** [comment] 2022-12-01 08:52
I think the problem is that `openvino_custom` doesn't exist anymore. This is not a CVAT issue, I think you need to deal with docker images. I will close this issue. If you do not agree with this, you can open the issue again.

**Closed by yasakova-anastasia** 2022-12-01 08:52 UTC
Labels: bug
