### ISSUE TITLE
Unable to invoke nuclio functions from cvat

### ISSUE THREAD

**Issue by yasakova-anastasia** [opencv/cvat#4855] opened 2022-08-26 07:43 UTC
Hi 

Unfortunately, I am not able to make the semi automatic annotation work. 
I followed the guide to set it up: https://cvat-ai.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/
I can indeed invoke the function with nuctl but not from cvat. 

When testing the yolov3 from cvat I get the following error:
`Detection error occured
Error: Request failed with status code 500. "500 Server Error: Internal Server Error for url: http://nuclio:8070/api/function_invocations".`

I am working with 
commit 3bd7c7e422d57986bd629da07214a3a3e666c68c (HEAD -> master, tag: v2.1.0, origin/master)
nuclio 1.5.16 as stated in `cvat/components/serverless/docker-compose.serverless.yml `

looking at the nuclio logs with logs --follow nuclio --tail=1: 
22.08.18 13:24:11.788 [0;37mashboard.platform.invoker[0m [0;34m(I)[0m Executing function {"method": "POST", "url": "http://172.17.0.1:8000", "headers": {"Accept":["*/*"],"Accept-Encoding":["gzip, deflate"],"Connection":["close"],"Content-Length":["612797"],"Content-Type":["application/json"],"User-Agent":["python-requests/2.26.0"],"X-Nuclio-Function-Name":["openvino-omz-public-yolo-v3-tf"],"X-Nuclio-Function-Namespace":["nuclio"],"X-Nuclio-Log-Level":[""],"X-Nuclio-Path":["/"],"X-Nuclio-Project-Name":["cvat"],"X-Nuclio-Target":["openvino-omz-public-yolo-v3-tf"]}}
22.08.18 13:24:11.788 [0;37m.api/function_invocations[0m [0;33m(W)[0m Failed to invoke function {"err": "Failed to send HTTP request", "errVerbose": "\nError - Post \"http://172.17.0.1:8000\": dial tcp 172.17.0.1:8000: connect: no route to host\n    /nuclio/pkg/platform/abstract/invoker.go:119\n\nCall stack:\nFailed to send HTTP request\n    /nuclio/pkg/platform/abstract/invoker.go:119\nFailed to send HTTP request", "errCauses": [{"error": "Post \"http://172.17.0.1:8000\": dial tcp 172.17.0.1:8000: connect: no route to host"}]}
22.08.18 13:24:11.788 [0;37m         dashboard.server[0m [0;32m(D)[0m Handled request {"requestMethod": "POST", "requestPath": "/api/function_invocations", "requestHeaders": {"Accept":["*/*"],"Accept-Encoding":["gzip, deflate"],"Connection":["close"],"Content-Length":["612797"],"Content-Type":["application/json"],"User-Agent":["python-requests/2.26.0"],"X-Nuclio-Function-Name":["openvino-omz-public-yolo-v3-tf"],"X-Nuclio-Function-Namespace":["nuclio"],"X-Nuclio-Log-Level":[""],"X-Nuclio-Path":["/"],"X-Nuclio-Project-Name":["cvat"],"X-Nuclio-Target":["openvino-omz-public-yolo-v3-tf"]}, "requestBody": "{\"image\": 
.... 

For me it looks like that cvat tries to correctly reach http://172.17.0.1:8000 but cvat cannot talk to nuclio. 

I have very limited knowledge about networking, so any pointers to debugging this would be great. Thank you!

![image](https://user-images.githubusercontent.com/37105377/185411712-7fb698c5-2426-41f8-97d6-ab13cafe1411.png)

### Details:

`docker ps` :

CONTAINER ID   IMAGE                                        COMMAND                  CREATED          STATUS                    PORTS                                                                                          NAMES
90da9c9eb929   cvat/openvino.omz.public.yolo-v3-tf:latest   "processor"              10 minutes ago   Up 10 minutes (healthy)   0.0.0.0:8000->8080/tcp, :::8000->8080/tcp                                                      nuclio-nuclio-openvino-omz-public-yolo-v3-tf

9914fa07ec33   cvat/openvino.dextr:latest                   "processor"              10 minutes ago   Up 10 minutes (healthy)   0.0.0.0:49201->8080/tcp, :::49201->8080/tcp                                                    nuclio-nuclio-openvino-dextr

4e7eb17e209b   alpine:3.11                                  "/bin/sh -c '/bin/sl…"   47 minutes ago   Up 47 minutes                                                                                                            nuclio-local-storage-reader

a6e2ee805a5c   openvino/cvat_ui                             "/docker-entrypoint.…"   2 hours ago      Up 2 hours                80/tcp                                                                                         cvat_ui

948469b65c8f   openvino/cvat_server                         "/usr/bin/supervisord"   2 hours ago      Up 2 hours                8080/tcp                                                                                       cvat

68475d07147d   redis:4.0-alpine                             "docker-entrypoint.s…"   2 hours ago      Up 2 hours                6379/tcp                                                                                       cvat_redis

b8eb3153ad24   postgres:10-alpine                           "docker-entrypoint.s…"   2 hours ago      Up 2 hours                5432/tcp                                                                                       cvat_db

1014c7b27c0e   quay.io/nuclio/dashboard:1.5.16-amd64        "/docker-entrypoint.…"   2 hours ago      Up 2 hours (healthy)      80/tcp, 0.0.0.0:8070->8070/tcp, :::8070->8070/tcp                                              nuclio

d7084596806e   traefik:v2.4                                 "/entrypoint.sh --pr…"   2 hours ago      Up 2 hours                0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 80/tcp, 0.0.0.0:8090->8090/tcp, :::8090->8090/tcp   traefik

578b14aa28d3   openpolicyagent/opa:0.34.2-rootless          "/opa run --server -…"   2 hours ago      Up 2 hours                0.0.0.0:8181->8181/tcp, :::8181->8181/tcp                                                      cvat_opa

71297bac6ff6   cvat/ultralytics-yolov5:latest               "processor"              4 hours ago      Up 4 hours (healthy)      0.0.0.0:49204->8080/tcp, :::49204->8080/tcp                                                    nuclio-nuclio-ultralytics-yolov5

`nuctl get functions`:

  NAMESPACE |              NAME              | PROJECT | STATE | NODE PORT | REPLICAS  
  nuclio    | openvino-dextr                 | cvat    | ready |     49201 | 1/1       
  nuclio    | openvino-omz-public-yolo-v3-tf | cvat    | ready |      8000 | 1/1       
  nuclio    | ultralytics-yolov5             | cvat    | ready |     49204 | 1/1   
  
Issue by @RadekZenkl

**Comment by azhavoro** [comment] 2022-08-26 13:10
@RadekZenkl It's very strange that the nuclio function was deployed on port 8000, please specify your environmet (OS at least) and exact steps to reporduce the issue. This error occurs only with yolov3? What about other functions?

**Comment by RadekZenkl** [comment] 2022-08-29 08:29
Hi @azhavoro 

I reinstalled cvat from scratch and redeployed the nuclio functions. I also switched `CVAT_VERSION=dev`, but I am still getting the same error. 

My environment is:

Fedora 35, 5.18.18-100.fc35.x86_64
Docker version 20.10.17, build 100c701
docker-compose version 1.29.2, build unknown
CVAT: v2.0.0-170-gf70aa2e8
Nuclio Version is now 1.8.14 (same as in docker-compose.serverless.yml)

I start CVAT with the following commands:
`CVAT_HOST=<host ip>`
`docker-compose -f docker-compose.yml -f docker-compose.override.yml -f components/serverless/docker-compose.serverless.yml up -d`

the deployed tested functions are:
  NAMESPACE |              NAME              | PROJECT | STATE | REPLICAS | NODE PORT  
  nuclio    | openvino-omz-public-yolo-v3-tf | cvat    | ready | 1/1      |     49156  
  nuclio    | ultralytics-yolov5             | cvat    | ready | 1/1      |     49154 
  
Upon invoking them from CVAT I get the following errors:
`Detection error occurred
Error: Request failed with status code 503. "HTTPConnectionPool(host='host.docker.internal', port=49156): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fea383f24c0>: Failed to establish a new connection: [Errno 113] No route to host'))".`

Respectively:

`Detection error occurred
Error: Request failed with status code 503. "HTTPConnectionPool(host='host.docker.internal', port=49154): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fea3832af70>: Failed to establish a new connection: [Errno 113] No route to host'))".`

![image](https://user-images.githubusercontent.com/37105377/187155749-c79c933e-ee78-404f-bc90-a128dd83d8f9.png)

docker ps: 
CONTAINER ID   IMAGE                                        COMMAND                  CREATED          STATUS                    PORTS                                                                                          NAMES
ac2c54541ba4   cvat.ultralytics-yolov5:latest               "processor"              15 minutes ago   Up 15 minutes (healthy)   0.0.0.0:49154->8080/tcp, :::49154->8080/tcp                                                    nuclio-nuclio-ultralytics-yolov5
4eb11f156d7e   gcr.io/iguazio/alpine:3.15                   "/bin/sh -c '/bin/sl…"   26 minutes ago   Up 26 minutes                                                                                                            nuclio-local-storage-reader
d4a7809fbd0b   cvat/ui:dev                                  "/docker-entrypoint.…"   2 days ago       Up 2 days                 80/tcp                                                                                         cvat_ui
1eddf5af993e   cvat/server:dev                              "/usr/bin/supervisor…"   2 days ago       Up 2 days                 8080/tcp                                                                                       cvat_utils
11079503e618   cvat/server:dev                              "/usr/bin/supervisor…"   2 days ago       Up 2 days                 8080/tcp                                                                                       cvat_worker_low
15abc87448e1   cvat/server:dev                              "/usr/bin/supervisor…"   2 days ago       Up 2 days                 8080/tcp                                                                                       cvat_worker_default
bd8759fbf37b   cvat/server:dev                              "/usr/bin/supervisor…"   2 days ago       Up 2 days                 8080/tcp                                                                                       cvat_server
5e13968d0e36   redis:4.0-alpine                             "docker-entrypoint.s…"   2 days ago       Up 2 days                 6379/tcp                                                                                       cvat_redis
0532e119524c   postgres:10-alpine                           "docker-entrypoint.s…"   2 days ago       Up 2 days                 5432/tcp                                                                                       cvat_db
393217273fe5   traefik:v2.4                                 "/entrypoint.sh --pr…"   2 days ago       Up 2 days                 0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 80/tcp, 0.0.0.0:8090->8090/tcp, :::8090->8090/tcp   traefik
e6003dd2eb8b   openpolicyagent/opa:0.34.2-rootless          "/opa run --server -…"   2 days ago       Up 2 days                 0.0.0.0:8181->8181/tcp, :::8181->8181/tcp                                                      cvat_opa
fc5f91a79d8c   quay.io/nuclio/dashboard:1.8.14-amd64        "/docker-entrypoint.…"   2 days ago       Up 2 days (healthy)       80/tcp, 0.0.0.0:8070->8070/tcp, :::8070->8070/tcp                                              nuclio
a7f426ec2b57   cvat/openvino.omz.public.yolo-v3-tf:latest   "processor"              4 days ago       Up 2 days (healthy)       0.0.0.0:49153->8080/tcp, :::49153->8080/tcp                                                    nuclio-nuclio-openvino-omz-public-yolo-v3-tf

The Nuclio functions are deployed with the following command:
`nuctl deploy --project-name cvat   --path serverless/openvino/dextr/nuclio/   --volume `pwd`/serverless/common:/opt/nuclio/common   --platform local`

Thank you for your help

**Comment by azhavoro** [comment] 2022-09-13 09:26
What is output of `docker exec cvat_server bash -c "cat /etc/hosts"` command?

**Comment by RadekZenkl** [comment] 2022-09-13 14:51
hi, the output from `docker exec cvat_server bash -c "cat /etc/hosts"`

127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.1	host.docker.internal
172.18.0.8	6caf11600a3e


and  `docker exec cvat_worker_low bash -c "cat /etc/hosts"`:

127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.18.0.7	416bbed5334e

**Comment by azhavoro** [comment] 2022-09-13 16:27
The reason is that the `cvat_worker_low` container does not have `host.docker.internal` definition.
This issue has been fixed, update cvat source code and restart containers.

**Comment by RadekZenkl** [comment] 2022-09-14 08:24
Hey, I updated to v2.2.0. 

The docker internal is now part of `cvat_worker_low`

`docker exec cvat_worker_low bash -c "cat /etc/hosts"`
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.1	host.docker.internal
172.24.0.10	0dff89163759

`docker exec cvat_server bash -c "cat /etc/hosts"`
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.1	host.docker.internal
172.24.0.9	584bb612ca13


the error still prevails 
![image](https://user-images.githubusercontent.com/37105377/190101413-57235c9e-a80f-44fb-84d9-6186f9730e52.png)

**Comment by azhavoro** [comment] 2022-09-14 08:55
I will try to reproduce the issue on Fedora

**Comment by azhavoro** [comment] 2022-09-16 07:23
Unfortunately, the problem does not occur in a freshly installed Fedora 35 (VM). I think the issue may be related to firewall settings. What is output of `docker exec cvat_server bash -c "curl -Lv 172.17.0.1"`
Also please provide outputs from `docker network ls`, `docker network inspect cvat_cvat` and `docker network inspect bridge`

**Comment by RadekZenkl** [comment] 2022-09-16 09:06
Executing `docker exec cvat_server bash -c "curl -Lv 172.17.0.1"` leads to:
* Uses proxy env variable no_proxy == 'elasticsearch,kibana,logstash,nuclio,opa,'
*   Trying 172.17.0.1:80...
* TCP_NODELAY set
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* connect to 172.17.0.1 port 80 failed: No route to host
* Failed to connect to 172.17.0.1 port 80: No route to host
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (7) Failed to connect to 172.17.0.1 port 80: No route to host



`docker network ls` :
NETWORK ID     NAME        DRIVER    SCOPE
31e852eb1cf3   bridge      bridge    local
f5f391a4393c   cvat_cvat   bridge    local
051a298d6127   host        host      local
aaa792e4ade3   none        null      local

`docker network inspect cvat_cvat`:
[
    {
        "Name": "cvat_cvat",
        "Id": "f5f391a4393c09e9fcb3fd2ff4a353fdaa8af71cdeee0c07b9b0030e2018c1ea",
        "Created": "2022-09-14T10:17:11.296275775+02:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.24.0.0/16",
                    "Gateway": "172.24.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "0dff8916375946ead88e5adba36a241a04abd7da398e4506c1d63ccf22c0ace1": {
                "Name": "cvat_worker_low",
                "EndpointID": "ee86a940ab22340ecb270aa9edf6832f486c2734853e95f7fc0e13c4f2a29d3f",
                "MacAddress": "02:42:ac:18:00:0a",
                "IPv4Address": "172.24.0.10/16",
                "IPv6Address": ""
            },
            "1f0f6b5e6a301dff273676655cf6c370a16f257f953f6ea50db216eed3019361": {
                "Name": "cvat_ui",
                "EndpointID": "7fb7c47bf413f52e107d6ad8e289c998701e485b2b101c1b01f1c64e63583cfa",
                "MacAddress": "02:42:ac:18:00:0b",
                "IPv4Address": "172.24.0.11/16",
                "IPv6Address": ""
            },
            "36cacd95f6320f618d3c0bdd89c987c29a884b586992d757b30d6b2607e479d7": {
                "Name": "traefik",
                "EndpointID": "1461bd79489a6ac793dd08ea0828b6516e8f9993ecb606914b520cbc4602c78e",
                "MacAddress": "02:42:ac:18:00:03",
                "IPv4Address": "172.24.0.3/16",
                "IPv6Address": ""
            },
            "3e9596fbac84eab82c830e731da928e7a61a5832401ee130f4b000c4b6b45ec1": {
                "Name": "cvat_redis",
                "EndpointID": "15de39856f75bf2fb474b8faabc82d96b7fcff3ecfaaf3a7cce2d5265ecacb73",
                "MacAddress": "02:42:ac:18:00:04",
                "IPv4Address": "172.24.0.4/16",
                "IPv6Address": ""
            },
            "56a7dc71396b4249c89da37e8ce02d0c19bbe6d65ea261f1873ff0404529875e": {
                "Name": "nuclio",
                "EndpointID": "3848322d96d635367da02849b67a8bfba139c40db6c93c3bd6f62be13d917179",
                "MacAddress": "02:42:ac:18:00:05",
                "IPv4Address": "172.24.0.5/16",
                "IPv6Address": ""
            },
            "584bb612ca132f5cb6ed9c12ca1ea604773bf3a40156c4b424701b221e44b72a": {
                "Name": "cvat_server",
                "EndpointID": "16f8ba4f85973324a7219bc8cf4b3f627219be5595342abb0400ab2aeb5d3acc",
                "MacAddress": "02:42:ac:18:00:09",
                "IPv4Address": "172.24.0.9/16",
                "IPv6Address": ""
            },
            "6575c38cc93926d4778b5cac50496215048318871602f5369f33646f297ce835": {
                "Name": "cvat_db",
                "EndpointID": "673434d7a76d9b48a64996bddd573531636697205840c346624c8ae4649fbe2e",
                "MacAddress": "02:42:ac:18:00:02",
                "IPv4Address": "172.24.0.2/16",
                "IPv6Address": ""
            },
            "76bb06e8884f18901156969bc0cd21f40058a5db70feaae8bb53443860243410": {
                "Name": "cvat_opa",
                "EndpointID": "886e5c4b71425fdf6dca9a9127683a3dade0d7c062e0a4c1884dcc405ff6bdae",
                "MacAddress": "02:42:ac:18:00:06",
                "IPv4Address": "172.24.0.6/16",
                "IPv6Address": ""
            },
            "a2ebc26b52ae5b526d5f48f0a8961ffc386652c3d93fff890ab252ab2ca39b15": {
                "Name": "cvat_worker_default",
                "EndpointID": "0f9526b1ab5816c465cece7d7c869c345e816ae932dab01e0ec0c1f093889895",
                "MacAddress": "02:42:ac:18:00:07",
                "IPv4Address": "172.24.0.7/16",
                "IPv6Address": ""
            },
            "a4be6f7adbe2f8a147d553d61878bed3b8dbbb8ef8759b25a4674372fee1e4bf": {
                "Name": "cvat_utils",
                "EndpointID": "01529e4bb41c15c05797f131dd1fdcb05af4297dd34af96e2d1b5fab287f732e",
                "MacAddress": "02:42:ac:18:00:08",
                "IPv4Address": "172.24.0.8/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "cvat",
            "com.docker.compose.project": "cvat",
            "com.docker.compose.version": "1.29.2"
        }
    }
]


`docker network inspect bridge`
[
    {
        "Name": "bridge",
        "Id": "31e852eb1cf386f961f6825e7aa4a00f52acab6394cee3df0d471abed36cd259",
        "Created": "2022-09-14T08:46:50.787634195+02:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "032f75358c3f568dd2bd0a8626bfa5057f00dd3954a9bde5b5516727e2c7a872": {
                "Name": "nuclio-nuclio-pth.facebookresearch.detectron2.retinanet-r101",
                "EndpointID": "faa3c3082f5f4eac495fa4208a39b925d4d00018da60a855bb5e5327f70b03d6",
                "MacAddress": "02:42:ac:11:00:02",
                "IPv4Address": "172.17.0.2/16",
                "IPv6Address": ""
            },
            "25a668e1943478c6d73f4070b4a43ddf2367dcebec59a96b8db2900cd16da624": {
                "Name": "nuclio-nuclio-openvino-dextr",
                "EndpointID": "9a04570da7568eed4c996afe82ab7adba119afb0baec6fb608078b1586ce4208",
                "MacAddress": "02:42:ac:11:00:07",
                "IPv4Address": "172.17.0.7/16",
                "IPv6Address": ""
            },
            "ac2c54541ba41319b3a5dc637856bd9a65a39bc946eab050d73908421d8129cd": {
                "Name": "nuclio-nuclio-ultralytics-yolov5",
                "EndpointID": "45ee4e6309b5a7e530b5e906d494e9db5a47175ebaf1f987168508631c1d5cb4",
                "MacAddress": "02:42:ac:11:00:04",
                "IPv4Address": "172.17.0.4/16",
                "IPv6Address": ""
            },
            "c24ecd872cb611bae775070cd658f2633abb74f20e2d980806e279492584e49b": {
                "Name": "nuclio-nuclio-openvino-omz-public-yolo-v3-tf",
                "EndpointID": "3a0833b2ce4ea37a36e8d87f52d0b51c7df9840dfb9233d5d5a99a37724886e8",
                "MacAddress": "02:42:ac:11:00:03",
                "IPv4Address": "172.17.0.3/16",
                "IPv6Address": ""
            },
            "ea3af58a3e5e61e42af241ec6e35889c13795644a365fd090faee72b60bf87d3": {
                "Name": "nuclio-local-storage-reader",
                "EndpointID": "2cfa71d9827999b16aaafc7dc20c75f584c5e2de76d90ae2db14d27672fc7999",
                "MacAddress": "02:42:ac:11:00:05",
                "IPv4Address": "172.17.0.5/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    }
]

**Comment by GalymzhanAbdimanap** [comment] 2022-11-11 08:24
@RadekZenkl  have you solved this problem? I have the same problem with hrnet but yolo dextr are working properly
 Ubuntu 20.04
 cvat 2.2
Docker version 20.10.21
docker-compose version 1.29.2
nuclio 1.8.14

**Comment by RadekZenkl** [comment] 2022-11-11 13:11
Hi, no I still haven't solved the problem. 
I have a different problem, my docker containers do not get invoked, because they don't receive the request.

**Comment by nmanovic** [comment] 2023-01-05 17:10
Please try our latest release. I believe right now some issues with nuclio should be resolved.

**Closed by nmanovic** 2023-01-05 17:10 UTC

**Comment by ellkrauze** [comment] 2024-07-05 07:08
Hello, I have just faced this problem. When I try to invoke a nuclio function from cvat, I get
```html
Detection error occurred
<html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1>
```
```bash
nuctl get functions
 NAMESPACE | NAME          | PROJECT | STATE | REPLICAS | NODE PORT 
 nuclio    | walls-segment | cvat    | ready | 1/1      | 32771 
```
Nuclio function's status in dashboard is
```
Function deploy complete   [externalInvocationURLs: ["0.0.0.0:32771"], functionName: "walls-segment", httpPort: 32771, internalInvocationURLs: ["172.17.0.4:8080"]] 
```
