### ISSUE TITLE
Cannot save the label to the task 

### ISSUE THREAD

**Issue by jayhuashi** [opencv/cvat#4228] opened 2022-01-24 04:35 UTC
### My actions before raising this issue
- [ Yes] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ Yes] Searched [past issues](/issues)

### Expected Behaviour

I expect to save my current label before I close the task 

### Current Behaviour

It did not save, showing 

![Screen Shot 2022-01-23 at 23 32 20](https://user-images.githubusercontent.com/50454373/150722483-98ff5f9d-5f1d-4432-a6fc-244e988306eb.png)

### Context

I cannot use it properly to label my dataset now

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

commit f9e10ff05991fd83e939d9d6b73253a8ed485c34
Docker Engine
v20.10.12
Docker Desktop 4.4.2 (73305) I
Operating System: macOS Monterey Version 12.1

CONTAINER ID   IMAGE                                 COMMAND                  CREATED          STATUS              PORTS                                                    NAMES
85325fb47df7   openvino/cvat_ui                      "/docker-entrypoint.…"   37 minutes ago   Up About a minute   80/tcp                                                   cvat_ui
b3be27257fce   openvino/cvat_server                  "/usr/bin/supervisord"   37 minutes ago   Up About a minute   8080/tcp                                                 cvat
80bf432f8a30   openpolicyagent/opa:0.34.2-rootless   "/opa run --server -…"   37 minutes ago   Up About a minute   0.0.0.0:8181->8181/tcp                                   cvat_opa
78ab341ad04d   traefik:v2.4                          "/entrypoint.sh --pr…"   38 minutes ago   Up About a minute   0.0.0.0:8080->8080/tcp, 80/tcp, 0.0.0.0:8090->8090/tcp   traefik
a72d760d55d5   redis:4.0-alpine                      "docker-entrypoint.s…"   39 minutes ago   Up About a minute   6379/tcp                                                 cvat_redis
b931a64685bb   postgres:10-alpine                    "docker-entrypoint.s…"   39 minutes ago   Up About a minute   5432/tcp                                                 cvat_db

2022-01-24 04:36:59,354 DEBG 'runserver' stderr output:

[Mon Jan 24 04:36:59.353919 2022] [wsgi:error] [pid 234:tid 139733613655808] [remote 172.18.0.3:46472] [2022-01-24 04:36:59,353] WARNING django.request: Bad Request: /api/v1/jobs/13/annotations

2022-01-24 04:36:59,354 DEBG 'runserver' stderr output:

[Mon Jan 24 04:36:59.354337 2022] [wsgi:error] [pid 234:tid 139733613655808] [remote 172.18.0.3:46472] WARNING - 2022-01-24 04:36:59,353 - log - Bad Request: /api/v1/jobs/13/annotations

2022-01-24 04:37:00,758 DEBG 'runserver' stderr output:

[Mon Jan 24 04:37:00.758183 2022] [wsgi:error] [pid 234:tid 139733630441216] [remote 172.18.0.3:46476] [2022-01-24 04:37:00,757] INFO cvat.server.task_15: get repository request

2022-01-24 04:37:00,759 DEBG 'runserver' stderr output:

[Mon Jan 24 04:37:00.758723 2022] [wsgi:error] [pid 234:tid 139733630441216] [remote 172.18.0.3:46476] INFO - 2022-01-24 04:37:00,757 - views - get repository request

2022-01-24 04:37:00,803 DEBG 'runserver' stderr output:

[Mon Jan 24 04:37:00.802860 2022] [wsgi:error] [pid 234:tid 139733613655808] [remote 172.18.0.3:46480] [2022-01-24 04:37:00,802] WARNING django.request: Bad Request: /api/v1/jobs/13/annotations

2022-01-24 04:37:00,805 DEBG 'runserver' stderr output:

[Mon Jan 24 04:37:00.804688 2022] [wsgi:error] [pid 234:tid 139733613655808] [remote 172.18.0.3:46480] WARNING - 2022-01-24 04:37:00,802 - log - Bad Request: /api/v1/jobs/13/annotations

**Comment by bsekachev** [comment] 2022-01-24 06:48
Hi,

Could you please send us stacktrace from your browser?
To do this open your browser devtools and go to console tab.

**Comment by jayhuashi** [comment] 2022-01-24 15:19
@bsekachev 
The message I got from the console.trace() in the console tab



<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta
            name="description"
            content="Computer Vision Annotation Tool (CVAT) is a free, open source, web-based image and video annotation tool which is used for labeling data for computer vision algorithms. CVAT supports the primary tasks of supervised machine learning: object detection, image classification, and image segmentation. CVAT allows users to annotate data for each of these cases"
        />
        <meta name="”robots”" content="index, follow" />
        <title>Computer Vision Annotation Tool</title>
    </head>

    <body>
        <div id="root"></div>
        <div id="layout-grid"></div>
    <script type="text/javascript" src="/cvat-ui.6b2ae289a73efc92057f.min.js"></script></body>
</html>


Do I get the correct stacktrace?

Thank you for the response!

**Comment by bsekachev** [comment] 2022-01-24 17:45
What you send is not stacktrace, but probably you will not be able to provide it. 

I would suggest trying to debug the application code, unfortunately there are not other ways to understand the root cause.. 
If you are ready to do this, I can try to instruct you.

**Comment by jayhuashi** [comment] 2022-01-24 20:48
Sure! 

Can you provide me with some instructions and I will learn to debug it.

Thank you!

**Comment by bsekachev** [comment] 2022-01-25 07:22
First of all open the browser dev tools and go to "Sources" tab. 
Then open  the file: ``webpack:/src/actions/annotation-actions.ts`` in the left sidebar and left a breakpoint as it shown on the screenshot (line number can be a bit different in your case).

![image](https://user-images.githubusercontent.com/40690378/150929530-d4c23aaa-1fbd-43d2-953d-1994246c21b9.png)
Go back to the browser (do not to close dev tools) and start saving annotation.
On dev tools the breakpoint should be triggered, then try to go to ``Console`` tab and do something like: ``error.toString()`` or ``e.toString()``.

**Comment by bsekachev** [comment] 2022-09-06 20:34
I will close the issue for now. 
Do not hesitate to reopen if you have any updates.

**Closed by bsekachev** 2022-09-06 20:34 UTC
Labels: need info
