### ISSUE TITLE
dump annotations error

### ISSUE THREAD

**Issue by alontrais** [opencv/cvat#1081] opened 2020-01-20 21:36 UTC
When I click on dump annotations I get this error on log:
2020-01-19 23:18:08,222 DEBG 'rqworker_default_1' stderr output:
23:18:08 cvat.apps.engine.utils.InterpreterError: AssertionError
Traceback (most recent call last):
File "/home/django/cvat/apps/engine/utils.py", line 45, in execute_python_code
exec(source_code, global_vars, local_vars)
File "<string>", line 1, in <module>
File "<string>", line 310, in dump_as_cvat_interpolation
File "/home/django/cvat/apps/annotation/annotation.py", line 340, in tracks
tracked_shapes = TrackManager.get_interpolated_shapes(track, 0, self._db_task.size)
File "/home/django/cvat/apps/engine/data_manager.py", line 347, in get_interpolated_shapes
assert shape["frame"] > curr_frame
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/rq/worker.py", line 812, in perform_job
rv = job.perform()
File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 588, in perform
self._result = self._execute()
File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 594, in _execute
return self.func(self.args, *self.kwargs)
File "/home/django/cvat/apps/engine/annotation.py", line 135, in dump_task_data
annotation.dump(filename, dumper, scheme, host)
File "/home/django/cvat/apps/engine/annotation.py", line 740, in dump
execute_python_code("{}(file_object, annotations)".format(dumper.handler), global_vars)
File "/home/django/cvat/apps/engine/utils.py", line 54, in execute_python_code
raise InterpreterError("{}".format(error_class))
cvat.apps.engine.utils.InterpreterError: AssertionError
Traceback (most recent call last):
File "/home/django/cvat/apps/engine/utils.py", line 45, in execute_python_code
exec(source_code, global_vars, local_vars)
File "<string>", line 1, in <module>
File "<string>", line 310, in dump_as_cvat_interpolation
File "/home/django/cvat/apps/annotation/annotation.py", line 340, in tracks
tracked_shapes = TrackManager.get_interpolated_shapes(track, 0, self._db_task.size)
File "/home/django/cvat/apps/engine/data_manager.py", line 347, in get_interpolated_shapes
assert shape["frame"] > curr_frame
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/rq/worker.py", line 812, in perform_job
rv = job.perform()
File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 588, in perform
self._result = self._execute()
File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 594, in _execute
return self.func(self.args, *self.kwargs)
File "/home/django/cvat/apps/engine/annotation.py", line 135, in dump_task_data
annotation.dump(filename, dumper, scheme, host)
File "/home/django/cvat/apps/engine/annotation.py", line 740, in dump
execute_python_code("{}(file_object, annotations)".format(dumper.handler), global_vars)
File "/home/django/cvat/apps/engine/utils.py", line 54, in execute_python_code
raise InterpreterError("{}".format(error_class))
cvat.apps.engine.utils.InterpreterError: AssertionError
What could be the cause of this error?

**Comment by bsekachev** [comment] 2020-01-21 15:37
@alontrais 

Hi,
How many jobs in the task?

**Comment by alontrais** [comment] 2020-01-22 07:20
@bsekachev 
Hi,
The task has 1000 jobs, the annotations file size is about 80 MB.

**Comment by bsekachev** [comment] 2020-01-22 17:05
@alontrais 

It's hard to investigate reasons on our side.
We will try to reproduce, but it, probably won't be fast.

**Comment by alontrais** [comment] 2020-01-23 09:11
@bsekachev 
Thanks!
I use the newest version [0.5.2].
The error occurs when the annotation files are heavy.
How can I investigate the reasons?

**Comment by bsekachev** [comment] 2020-01-24 16:52
@alontrais 

We met this issue before #610
And it was fixed there #667 in 0.5.0 by sorting jobs before dumping. 

It wasn't easy to investigate the problem. We were browsing the production database and analyzed the code because the issue could not be reproduced after dumping the db and recovering it in a debug environment.

**Comment by azhavoro** [comment] 2020-03-24 07:42
@alontrais did you use frame filter for your task?

**Comment by bsekachev** [comment] 2020-07-09 17:45
@alontrais 

So, no answer for a long time. Not sure the issue is relevant. I will close it, but you can reopen if you still experience the issue

**Closed by bsekachev** 2020-07-09 17:45 UTC
