### ISSUE TITLE
Invalid interpolation format for "cvat_server" option in service "services"

### ISSUE THREAD

**Issue by kwende** [opencv/cvat#5936] opened 2023-03-25 16:47 UTC
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

When pulling master and attempting to do a docker-compose build / docker-compose up -d (per the instructions here: https://opencv.github.io/cvat/docs/administration/basics/installation/), I get 

"ERROR: Invalid interpolation format for "cvat_server" option in service "services": "cvat/server:${CVAT_VERSION:-dev}""

### Steps to Reproduce (for bugs)

1. git clone https://github.com/opencv/cvat
2. cd cvat
3. docker-compose up -d (or docker-compose build .)
4. Get ERROR: Invalid interpolation format for "cvat_server" option in service "services": "cvat/server:${CVAT_VERSION:-dev}"
5. Unable to proceed. 

### Expected Behaviour

Running docker-compose should do all the things it's supposed to do here, allowing me to run a containerized version of CVAT. 

### Current Behaviour

I get "ERROR: Invalid interpolation format for "cvat_server" option in service "services": "cvat/server:${CVAT_VERSION:-dev}" instead. 
### Context

I'm simply trying to run CVAT. 

### Your Environment

- Git hash commit (`git log -1`):
commit 61470b621e0786a7977dbc131a84550a49524382 (HEAD, tag: v2.4.0, origin/master)
Merge: 2c4676ac 86c9da3c
Author: Nikita Manovich <nikita@cvat.ai>
Date:   Thu Mar 16 10:14:05 2023 +0200

    Release v2.4.0

- Docker version `docker version` (e.g. Docker 17.0.05):
Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:33:13 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:31:25 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS):
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by azhavoro** [comment] 2023-03-27 14:40
@kwende, @Hyrtsi, @selectchanges what shell are you using?

**Comment by selectchanges** [comment] 2023-03-27 14:42
I' using Bash

**Comment by kwende** [comment] 2023-03-27 17:46
> what shell are you using?

Bash.

**Comment by mrawding** [comment] 2023-03-29 15:43
I ran into this issue today. I fixed it by removing my docker compose installation and replacing with the plugin. Originally I had this installed:

```docker-compose -v```
```docker-compose version 1.25.0, build unknown```

```apt list --installed | grep compose```
```docker-compose/focal,now 1.25.0-1 all [installed]```


After removing: ```sudo apt remove docker-compose -y```

I installed the plugin ```sudo apt install docker-compose-plugin```

Now docker command is ```docker compose``` instead of ```docker-compose``` and CVAT v2.4.0 works with ```docker compose up -d```

This is on ubuntu 20.04 LTS:

Version of plugin is:


```
apt list --installed | grep compose

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

docker-compose-plugin/focal,now 2.17.2-1~ubuntu.20.04~focal amd64 [installed]
```

**Comment by henning1419** [comment] 2023-03-29 19:45
I can confirm @mrawding solution. This error occurs because from 2.3.0 to 2.4.0 `version: '3.3'` was removed from the beginning of the `docker-compose.yml`. `docker compose` can handle it and `docker-compose` not.

**Comment by kwende** [comment] 2023-03-30 22:59
My setup was a tad different, but I really appreciate the input of everyone above. Nice job all. 

Basically, I think the key issue is that I skimmed over the Docker installation notes in the Wiki on this repo because I said to myself, "I have it installed". However, there's a tad more to it than that. You must do the following: 

```
sudo apt-get update
sudo apt-get install \
    ca-certificates \
    curl \
    gnupg

sudo mkdir -m 0755 -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

echo \
  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
```

Once done, then it does, indeed, work. I think the docs should be updated to indicate the fact you need the docker compose _plugin_ and not docker-compose. I imagine it's implicitly stated elsewhere, but it's easy to overlook.

**Comment by nmanovic** [comment] 2023-03-31 07:55
@kwende , thank you for the update. Could you please contribute to the documentation?

I will close the issue.

**Closed by nmanovic** 2023-03-31 07:55 UTC
