### ISSUE TITLE
Unable to create superuser

### ISSUE THREAD

**Issue by navyverma** [opencv/cvat#1154] opened 2020-02-18 13:37 UTC
I am able to build and run cvat tool. But when I trying to create a superuser then it is giving me below error.

**ImportError: No module named 'gitdb.utils.compat'**

I am running below command for creating a superuser.

**docker exec -it cvat bash -ic 'python3 ~/manage.py createsuperuser'**

Does anyone have any idea or suggestion for the above problem?

**Comment by azhavoro** [comment] 2020-02-18 13:45
@navyverma Please update CVAT, the issue should be fixed by #1146.
Duplicate of #1152

**Comment by LEE-SEON-WOO** [comment] 2020-02-18 14:10
![image](https://user-images.githubusercontent.com/12380660/74743536-e4ccdf00-52a3-11ea-91e9-726d1ed16c81.png)

**Closed** 2020-02-19 07:53 UTC
