### ISSUE TITLE
How to restrict users export datasets in jobs, tasks, projects?

### ISSUE THREAD

**Issue by KOR-TEH** [opencv/cvat#5937] opened 2023-03-26 19:48 UTC
### My actions before raising this issue
- [x] Read (https://www.opencv.ai/post/cvat-open-policy-agent)

It's just post about help. However, I tried to delete EXPORT_DATASET, EXPORT_ANNOTATIONS in jobs.rego.
After cvat_opa reboot - still having this picture.

### Your Environment
Ubuntu 20 LTS

**Comment by KOR-TEH** [comment] 2023-03-26 20:00
And little comment. When I GET /api/auth/rules in jobs.rego rules didn't change after cvat_opa microservice restart

**Comment by zhiltsov-max** [comment] 2023-04-05 07:52
Duplicate of https://github.com/opencv/cvat/issues/5955, please follow the advice there.

**Closed by zhiltsov-max** 2023-04-05 07:52 UTC
