### ISSUE TITLE
Get all tasks in results

### ISSUE THREAD

**Issue by MIRA-KUMAR** [opencv/cvat#5976] opened 2023-04-05 00:48 UTC
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

How do I get all tasks with the api. When I specify the page number inside kwargs, it throws error; 
Got an unexpected parameter 'kwargs' to method `list`

with ApiClient(configuration) as api_client:
        (data, response) = api_client.tasks_api.list(kwargs={'page':1})

How else should I specify?

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by zhiltsov-max** [comment] 2023-04-05 07:25
Hi, please check this [link](https://opencv.github.io/cvat/docs/api_sdk/sdk/lowlevel-api/#paginated-responses) about paginated lists in API. 

Please note, that to pass a dict of kwargs in Python, you need to expand it using the `**` operator: 

```python
def foo(**kwargs):
    ...

kwargs_dict = { 'x': 5, 'y': 42 }
foo(**kwargs_dict)
```

An example of using a list operation via SDK can be found [here](https://opencv.github.io/cvat/docs/api_sdk/sdk/reference/apis/tasks-api/#example-7).

**Comment by zhiltsov-max** [comment] 2023-04-13 20:12
I will close the issue, don't hesitate to reopen it, if the problem is not resolved.

**Closed by zhiltsov-max** 2023-04-13 20:12 UTC
Labels: question, sdk/cli
