### ISSUE TITLE
Cannot upload large videos (5472x3078)

### ISSUE THREAD

**Issue by RyanHir** [opencv/cvat#4770] opened 2022-07-20 17:47 UTC
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues) (including old repo)

### Expected Behaviour

Ideally I can upload a MP4 of a large size into the website from either my local machine or a file share.

### Current Behaviour

When uploading I get an error to check my browser console, which notified me that the issue is wit libopenh264 
![Screenshot from 2022-07-20 12-33-53](https://user-images.githubusercontent.com/4690732/180046413-cb67f871-6c33-4c21-a3b4-0fcbc49dff4c.png)

The logs from openh264 when upload fails are attached at the bottom.

### Steps to Reproduce (for bugs)

1. Create a video with a high resolution such as 5472x3078 (I have a bitrate of about 155000 kbps)
2. Create new project on Web UI
3. Create new task on Web UI
4. Upload video from either locally or from the file share.

### Context

I have drone footage that has very small and dark items which require using the original footage to pull the most detail when zooming. I can ingest the footage after resizing to 1080p but this looses detail which is undesired.

### Your Environment
- Git hash commit (`git log -1`): 3b1116185baee734ed4f276ced50cabf8bb67053
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.17
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
<details>
<summary>Logs from `cvat` container</summary>

```
cvat          | ERROR - 2022-07-20 17:34:05,967 - media_extractors - [OpenH264] this = 0x0x6203ed0, Error:ParamValidationExt(), width > 0, height > 0, width * height <= 9437184, invalid 5504 x 3088 in dependency layer settings!
cvat          | ERROR - 2022-07-20 17:34:05,967 - media_extractors - [OpenH264] this = 0x0x6203ed0, Error:WelsInitEncoderExt(), ParamValidationExt failed return 2.
cvat          | ERROR - 2022-07-20 17:34:05,967 - media_extractors - [OpenH264] this = 0x0x6203ed0, Error:CWelsH264SVCEncoder::Initialize(), WelsInitEncoderExt failed.
cvat          | ERROR - 2022-07-20 17:34:05,967 - media_extractors - Initialize failed
```
 </details>

**Comment by RyanHir** [comment] 2022-07-20 21:21
I am currently focusing discussion on the other issue.

**Comment by bsekachev** [comment] 2022-08-25 20:32
@azhavoro 

Do you think we have any solutions/workarounds to resolve the issue?

**Comment by azhavoro** [comment] 2022-08-26 13:00
duplicate of #4527
@RyanHir  There is openh264 encoder limitation, see #4527 for details

@bsekachev At the moment, I would suggest only extracting images from such videos with ffmpeg.

**Comment by kirill-sizov** [comment] 2022-08-29 13:03
Close because this issue is duplicate of #4527

**Closed by kirill-sizov** 2022-08-29 13:03 UTC
Labels: duplicate
