### ISSUE TITLE
Error after adding tag

### ISSUE THREAD

**Issue by idx-jsuther** [opencv/cvat#1546] opened 2020-05-15 16:21 UTC
### My actions before raising this issue
- [ x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. Create task with one label.
2. Add tag to image.
3. Select tag in objects menu.
4. Click anywhere on the image in the current frame

### Your Environment

- Git hash commit (`git log -1`): release 1.0.0 beta2
- Docker version `docker version` (e.g. Docker 17.0.05): 19.03.8
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Windows 10
- Error message: 
```
TypeError
Cannot read property 'removeClass' of undefined

TypeError: Cannot read property 'removeClass' of undefined
    at Mu.deactivateShape (http://localhost:8080/cvat-ui.min.js:72:1383432)
    at Mu.deactivate (http://localhost:8080/cvat-ui.min.js:72:1383945)
    at Mu.activate (http://localhost:8080/cvat-ui.min.js:72:1386524)
    at Mu.notify (http://localhost:8080/cvat-ui.min.js:72:1376376)
    at Cc.notify (http://localhost:8080/cvat-ui.min.js:72:1293598)
    at Cc.activate (http://localhost:8080/cvat-ui.min.js:72:1296682)
    at Lu.activate (http://localhost:8080/cvat-ui.min.js:72:1390992)
    at od.componentDidUpdate (http://localhost:8080/cvat-ui.min.js:72:1424967)
    at yl (http://localhost:8080/cvat-ui.min.js:43:100837)
    at t.unstable_runWithPriority (http://localhost:8080/cvat-ui.min.js:51:3465)

```

-Logs: https://pastebin.com/gJm3ejaL

**Comment by bsekachev** [comment] 2020-05-15 19:13
@idx-jsuther 

Please update CVAT. The issue should be resolved. 
Probably duplicate of #1540
Let us know if it is not true.

**Closed by bsekachev** 2020-05-15 19:13 UTC
