### ISSUE TITLE
Error installing CVAT- The no_proxy variable is not set

### ISSUE THREAD

**Issue by clarecatcreates** [opencv/cvat#4797] opened 2022-08-09 20:27 UTC
I tried to install CVAT using the installation guide found below and ran into the following error:
https://github.com/maheriya/cvat/blob/master/cvat/apps/documentation/installation.md#windows-10

$ docker-compose build
The no_proxy variable is not set. Defaulting to a blank string.
cvat_db uses an image, skipping
cvat_redis uses an image, skipping
traefik uses an image, skipping
cvat_opa uses an image, skipping
cvat uses an image, skipping
cvat_ui uses an image, skipping

Does anyone know how to resolve this? Thank you

**Comment by clarecatcreates** [comment] 2022-08-12 01:14
Figured it out. The link referenced above was rather old. Following the Installation.md file in the code package I was able to install cvat successfully.

**Comment by zhiltsov-max** [comment] 2022-08-21 12:10
Closing, feel free to reopen if the problem is is not resolved.

**Closed** 2022-08-21 12:10 UTC

**Comment by JK-rez** [comment] 2022-08-23 17:32
> I tried to install CVAT using the installation guide found below and ran into the following error: https://github.com/maheriya/cvat/blob/master/cvat/apps/documentation/installation.md#windows-10
> 
> $ docker-compose build The no_proxy variable is not set. Defaulting to a blank string. cvat_db uses an image, skipping cvat_redis uses an image, skipping traefik uses an image, skipping cvat_opa uses an image, skipping cvat uses an image, skipping cvat_ui uses an image, skipping
> 
> Does anyone know how to resolve this? Thank you

Having same issue, havent found a installation.md file.
When running on docker the container also keeps crashing, (Exit status in 2s)
The cvat was pulled from https://github.com/opencv/cvat
Followed instruction from https://hub.docker.com/r/openvino/cvat_server and https://cvat-ai.github.io/cvat/docs/administration/basics/installation/
Thank you

**Comment by zhiltsov-max** [comment] 2022-08-24 06:47
Could you please provide more details? Logs from `docker logs cvat_server` would be appreciated. The `no_proxy` variable should not affect the startup process heavily.

**Comment by sunwell1994** [comment] 2022-08-26 21:10
> > I tried to install CVAT using the installation guide found below and ran into the following error: https://github.com/maheriya/cvat/blob/master/cvat/apps/documentation/installation.md#windows-10
> > $ docker-compose build The no_proxy variable is not set. Defaulting to a blank string. cvat_db uses an image, skipping cvat_redis uses an image, skipping traefik uses an image, skipping cvat_opa uses an image, skipping cvat uses an image, skipping cvat_ui uses an image, skipping
> > Does anyone know how to resolve this? Thank you
> 
> Having same issue, havent found a installation.md file. When running on docker the container also keeps crashing, (Exit status in 2s) The cvat was pulled from https://github.com/opencv/cvat Followed instruction from https://hub.docker.com/r/openvino/cvat_server and https://cvat-ai.github.io/cvat/docs/administration/basics/installation/ Thank you

the command "docker exec -it cvat bash -ic 'python3 ~/manage.py createsuperuser'
" cannot work. It always returns "Error: No such container: cvat"

**Comment by zhiltsov-max** [comment] 2022-08-27 12:12
@sunwell1994, please check it with `cvat_server` instead, if you are using a recent version from the develop branch:

`docker exec -it cvat_server bash -ic 'python3 ~/manage.py createsuperuser`

We have renamed that container in a recent update.

**Comment by AbdelsalamHaa** [comment] 2022-09-20 02:58
Hi, I have the same issue but slightly different. 

I installed everything and everything worked fine. 
But the next time I power on my PC I couldn't access it through my local host, and I get "This site can't be reached"
Here is the message written when I run 

`docker-compose up -d`

```
time="2022-09-20T10:56:47+08:00" level=warning msg="The \"no_proxy\" variable is not set. Defaulting to a blank string."
time="2022-09-20T10:56:47+08:00" level=warning msg="The \"no_proxy\" variable is not set. Defaulting to a blank string."
time="2022-09-20T10:56:47+08:00" level=warning msg="The \"no_proxy\" variable is not set. Defaulting to a blank string."
time="2022-09-20T10:56:47+08:00" level=warning msg="The \"no_proxy\" variable is not set. Defaulting to a blank string."
Container cvat_opa  Created
Container cvat_redis  Running
Container traefik  Running
Container cvat_db  Running
Container cvat_utils  Running
Container cvat_worker_low  Running
Container cvat_server  Running
Container cvat_ui  Running
Container cvat_worker_default  Running
Container cvat_opa  Starting
Container cvat_opa  Started
```
