### ISSUE TITLE
Re: CVAT Server Requirement for 20+ Point of Access

### ISSUE THREAD

**Issue by garyJune** [opencv/cvat#4701] opened 2022-06-19 04:52 UTC
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

### Expected Behaviour

- Smooth Experience like the one hosted on cvat.org

### Current Behaviour

- Loading of images takes a long time
- Lags occur at peak access

### Possible Solution

- Searched and test is conducted on various instance of AWS from m5a.2xlarge, t2.medium, t2.xlarge and others. (https://github.com/openvinotoolkit/cvat/issues/1345, and other conversations in gitter)
- Setup Load Balancer on AWS -> Is it possible to provide some guidance?

### Steps to Reproduce (for bugs)

1. Open an instance of m5a.2xlarge on AWS
2. Clone and setup CVAT through defined installation in https://openvinotoolkit.github.io/cvat/docs/manual/
3. Use multiple devices to access 

### Context

- Access and performance of CVAT becomes degraded

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by alalek** [comment] 2022-06-19 10:50
BTW,

> Use multiple devices to access
> Loading of images takes a long time
> Lags occur at peak access

Slowdown may be caused by network bandwidth limitation of AWS instance. It depends on used images/videos (their resolution). You could check this case by monitoring of CPU/network load of AWS instance.
Or this may be caused by slow Internet connection of access points (check browser console - F12 (or similar), "Network" tab).

If access is performed from the office (all access points are from a single location) - consider configuration of local server setup with 1Gb+ network.

**Comment by zhiltsov-max** [comment] 2022-10-25 17:15
Hi, I'll close the issue. Feel free to reopen, if the problem is still actual.

**Closed by zhiltsov-max** 2022-10-25 17:15 UTC
