### ISSUE TITLE
Errors while running cvat container

### ISSUE THREAD

**Issue by 4DVivi** [opencv/cvat#4888] opened 2022-08-31 08:16 UTC
Hi, 

I have already used CVAT on my old laptop and it worked perfectly. Now, I tried to install it on my new laptop and I can not make it work.
In my Docker container, there are 5/9 CVAT containers running (see screenshot).

![CVAT](https://user-images.githubusercontent.com/112544387/187628476-4b037a39-c9e0-4260-a330-32b71aa5131e.PNG)

Error message from all these containers is the same:

Error: could not find config file supervisord/worker.low.conf
For help, use /usr/bin/supervisord -h

How can I fix this?
Sorry, I am not a programmer.

Thank you very much for your help!

Best regards,

Vivi 

### My actions before raising this issue
- [ x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05): v20.10.17
- Are you using Docker Swarm or Kubernetes? Swarm(?)
- Operating System and version (e.g. Linux, Windows, MacOS): Windows 10
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by dschoerk** [comment] 2022-08-31 08:24
i'd suggest to use a release version instead of the latest development branch. 

https://github.com/opencv/cvat/releases

v2.1.0 is working well for me.

**Comment by kirill-sizov** [comment] 2022-08-31 09:06
Hi, @4DVivi we know about this problem and currently work on it

duplicate of #4816

**Comment by JK-rez** [comment] 2022-09-01 17:19
Hi had a similar issue and found a potential "fix"

**Step 1:** Download source code from cvat (as in installation guide) 

-   git clone https://github.com/opencv/cvat
-   cd cvat

**Step 2:**  pull the dev version and assign it to CVAT_VERSION:

- CVAT_VERSION=dev docker-compose pull

**Step 3:** Build the images and compose the config file: 

- docker-compose -f docker-compose.yml -f docker-compose.dev.yml build

**Step 4:** starts the containers 

- docker-compose up -d

**System specs:**
Windows 11
WSL2 with Ubuntu 20.04
Docker v20.10.17

**Comment by kirill-sizov** [comment] 2022-09-06 11:46
We've merged #4889, now `cvat_server` container should start up normally.
I will close this issue, but feel free to reopen if the problem persists

**Closed by kirill-sizov** 2022-09-06 11:46 UTC
Labels: duplicate, infra
