### ISSUE TITLE
CVAT new UI: a bug with hidden objects mapping

### ISSUE THREAD

**Issue by aschernov** [opencv/cvat#1840] opened 2020-07-03 08:41 UTC
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Hidden objects should have a correct mapping. After pressing T+H all the objects must become invisible on a frame and have a corresponding icon with the current condition on the right objects panel. The second pressing T+H must return visibility for all objects and change the current condition on the right panel.

### Current Behaviour

It's enough to repeat the hide/unhide action (T+H) several times to get the following result:
![hiding](https://user-images.githubusercontent.com/45849884/86449704-380a7000-bd21-11ea-8d38-a045ed125eea.JPG)

### Steps to Reproduce (for bugs)

1. Draw several objects
1. Try to use T+H hotkey to visibility settings. Noticed that this problem mostly happens after moving between frames

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment] 2020-07-03 09:24
Probably related with #1834 and will be fixed after updating of server. Need to check.

**Comment by bsekachev** [comment] 2020-07-09 15:21
@aschernov 

Could you look if the issue is relevant?

**Comment by aschernov** [comment] 2020-07-10 05:20
Seems, the problem was fixed. Thank you!

**Closed** 2020-07-10 06:10 UTC
Labels: bug
