### ISSUE TITLE
cvat_ui is loading infinetly

### ISSUE THREAD

**Issue by vskubriev** [opencv/cvat#714] opened 2019-09-13 15:41 UTC
After successful docker-compose build and up, cvat_ui is not responding correctly. Interface is loading infinetly, as shown below:

![image](https://user-images.githubusercontent.com/4639077/64874797-6fa21180-d654-11e9-9def-89413f025148.png)

I tried to setup from master (c05c7aea8b548d71f9b5cce62370160051535237).

Can you help me to solve the issue. Any additional information I will attach at monday. Please specify what is necessary for you.

I made the following changes in `docker-compose.yml` for our case:

```
diff --git a/docker-compose.yml b/docker-compose.yml
index 163bbba..40be99f 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -50,11 +50,16 @@ services:
         DJANGO_CONFIGURATION: "production"
         WITH_TESTS: "no"
         TZ: "Etc/UTC"
-        OPENVINO_TOOLKIT: "no"
+        OPENVINO_TOOLKIT: "yes"
+        CUDA_SUPPORT: "yes"
+        WITH_DEXTR: "yes"
+    runtime: "nvidia"
     environment:
       DJANGO_MODWSGI_EXTRA_ARGS: ""
       UI_PORT: 9080
-
+      NVIDIA_VISIBLE_DEVICES: all
+      NVIDIA_DRIVER_CAPABILITIES: compute,utility
+      NVIDIA_REQUIRE_CUDA: "cuda>=9.0"
     volumes:
       - cvat_data:/home/django/data
       - cvat_keys:/home/django/keys
```

**Comment by bsekachev** [comment] 2019-09-13 17:50
@vskubriev 

It's a pre-alpha functionality. We don't recommend use it till the next release.

**Comment by nmanovic** [comment] 2019-09-15 15:54
@vskubriev , could you please open developer tools in chrome and look in console log? Let's try to understand what is going on.

**Comment by bsekachev** [comment] 2019-09-15 16:05
@nmanovic

It isn't a first case. A man in telegram has reported me the same

**Comment by vskubriev** [comment] 2019-09-16 08:06
> @vskubriev
> 
> It's a pre-alpha functionality. We don't recommend use it till the next release.
> Previous UI version is expected to be work.

Could you clarify how to use previous UI version or just use repo from Release 0.5.0 ?

**Comment by bsekachev** [comment] 2019-09-16 08:21
@vskubriev 
Go to default port: 8080, not 9080
``localhost:8080``

**Comment by vskubriev** [comment] 2019-09-16 08:23
> @vskubriev , could you please open developer tools in chrome and look in console log? Let's try to understand what is going on.

Log from console attached.
[1568621232833.log](https://github.com/opencv/cvat/files/3615253/1568621232833.log)

**Comment by vskubriev** [comment] 2019-09-16 08:24
> @vskubriev
> Go to default port: 8080, not 9080
> `localhost:8080`

There is error `Bad Request (400)` on `8080` port.

**Comment by vskubriev** [comment] 2019-09-16 08:39
Issue resolved ?

I just changed servername and then ui on 8080 is opens normally.

```
ERROR django.security.DisallowedHost: Invalid HTTP_HOST header
```

**Comment by bsekachev** [comment] 2019-09-16 08:44
@vskubriev 
Great.
Nevertheless we should investigate about new ui. 
Let's leave the issue open.

**Comment by vskubriev** [comment] 2019-09-16 10:22
> @nmanovic
> 
> It isn't a first case. A man in telegram has reported me the same

Why is in official manual there is installing from master ?

`https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/installation.md#additional-components`

Is it would be better to checkout release tag/branch before run docker-compose then it would be logical to indicate this in installation manual

**Comment by nmanovic** [comment] 2019-09-16 12:06
@vskubriev , please don't hesitate to send us a patch if you see how to improve the installation guide.

**Comment by vskubriev** [comment] 2019-09-16 13:23
> @vskubriev , please don't hesitate to send us a patch if you see how to improve the installation guide.

Thanks. Will do.

**Comment by nmanovic** [comment] 2019-11-01 20:04
@vskubriev , new CVAT UI was reimplemented. I will close the issue because it isn't actual anymore. Don't hesitate to reopen it if you still can reproduce the issue on develop branch.

**Closed by nmanovic** 2019-11-01 20:04 UTC
Labels: bug

**Comment by vskubriev** [comment] 2019-11-05 11:49
@nmanovic it's time to upgrade installed CVAT ?
