### ISSUE TITLE
Repeated (duplicate) file names in a project cause failed to export project dataset

### ISSUE THREAD

**Issue by shaojun** [opencv/cvat#4207] opened 2022-01-20 06:50 UTC
### My actions before raising this issue
- [v] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [v] Searched [past issues](/issues)

_I'm pretty sure there were similar topics/issues opened before, but I can't searched it out anymore, so have to create one again._

I Uploaded 2 videos into 2 tasks in one project for object detection labeling, when export project dataset, popup errors:

> Error: Request failed with status code 500. "datumaro.components.errors.RepeatedItemError: Item ('frame_000195', 'default') is repeated in the source sequence.\n".

### Expected Behaviour

The image files exported from a project should never have a name conflict.
### Current Behaviour

> Error: Request failed with status code 500. "datumaro.components.errors.RepeatedItemError: Item ('frame_000195', 'default') is repeated in the source sequence.\n".

### Possible Solution
Could prefix the task name into file name when importing.
Could prefix a GUID into file name  when importing.

### Context
With a multi-user project, each user may create task and upload image files seperately, so the duplicate file name is highly possible to happen between tasks in a project, especially for those video source which have a very simple naming convention of `frame_`+_frameNumber_, then so project export will fail.

**Comment by shaojun** [comment] 2022-01-25 02:36
could you check, or is there any misunderstanding?

**Comment by zhiltsov-max** [comment] 2022-01-25 09:47
Hi. For project export, we discussed few different image name decoration options, but they haven't been implemented yet. This feature was postponed for future project updates (driven by @ActiveChooN atm). Currently, you can put tasks in different subsets, or you can export tasks separately, then try to rename images with Datumaro ([`datum transform -t rename dataset/:<format> -- -e "|pattern|replace|"`](https://openvinotoolkit.github.io/datumaro/docs/user-manual/command-reference/transform/)) and merge using [`patch`](https://openvinotoolkit.github.io/datumaro/docs/user-manual/command-reference/patch/).

**Comment by shaojun** [comment] 2022-01-25 09:56
@zhiltsov-max thanks for the great effort, so looking forward for the implementation, as now for my multi tasks project, i have to export one by one, and `rename` them seperatly.

**Comment by zhiltsov-max** [comment] 2022-01-27 09:18
Duplicate of https://github.com/openvinotoolkit/cvat/issues/2046

**Closed** 2024-01-30 14:40 UTC
Labels: duplicate
