### ISSUE TITLE
Invite-only users?

### ISSUE THREAD

**Issue by Fred-Erik** [opencv/cvat#7687] opened 2024-03-27 14:20 UTC
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

### Is your feature request related to a problem? Please describe.

I'd like to host my self-hosted publicly so my workers can easily login from home without accessing our company VPN. I've added an organization and I invite my users that way. However, you could still make an account and access the mounted volume and use our models.

Is there a way to make user creation invite-only? I.e. disable the "Create an account" link and make it so you can only register if the Maintainer has invited someone.

**Comment by bsekachev** [comment] 2024-03-27 16:54
Disable registration endpoint on the server. 

Duplicate of #1283

**Closed by bsekachev** 2024-03-27 16:54 UTC
Labels: enhancement
