### ISSUE TITLE
Unable to upload YOLO annotations from cvat YOLO export (after re-zip)

### ISSUE THREAD

**Issue by kasuen** [opencv/cvat#5654] opened 2023-02-01 10:04 UTC
### My actions before raising this issue
- [ x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ x] Searched [past issues](/issues)

Trying to upload annotations to a job but failing due to "not finding image".  Please see Error Popup below.
For the purposes of this test, I only have annotations on frame 400.

When using the original (untouched) zip file that is provided by the CVAT export, I am able to upload it directly and create annotations from that zip file.  No issues.
However, if I unzip the file. then use terminal (macos) to zip, via  "zip -r" the opened folder  and then attempt to upload this zip file, I am provided with an error.  

### Steps to Reproduce (for bugs)

1.  Upload a video to a task and label soemthing on frame 100.
2.  Export the dataset using YOLO v1.1
3.  Download the provided zip file -- do not include images.
4.  Unzip the downloaded zip file. 
5.  Zip the newly unzipped file via zip -r
6.   Create a new task with the same video
7.  Attempt to upload annotations for the task.  using the newly re-zipped file.

### Expected Behaviour

We expect the behavior to be identical to using the original zip file.  As the only action that was done was open the folder, and re-zip.

### Current Behaviour

Currently we are receiving the pop up error:

Could not upload annotation for the [task 5](http://localhost:8080/tasks/5)

Error: Request failed with status code 500. "datumaro.components.errors.ItemImportError: Failed to import item ('frame_000400', 'train'): Can't find image info for '/home/django/data/tasks/5/tmp/tmpe1xra07m/test_me/obj_train_data/frame_000400.PNG'\n"..

### Context

Trying to upload annotations

### Your Environment

- Git hash commit (`git log -1`):  commit 3775bc25578888a2b12a05218df253398a926909 (HEAD -> develop, origin/develop, origin/HEAD)
Author: Kirill Lakhov <kirill.lakhov@cvat.ai>
Date:   Mon Jan 30 22:44:51 2023 +0300

    New models UI (#5635)

- Docker version `docker version` (e.g. Docker 17.0.05): Docker version 20.10.22, build 3a2c30b
- Are you using Docker Swarm or Kubernetes? no
- Operating System and version (e.g. Linux, Windows, MacOS): MacOS
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by whittenator** [comment] 2023-02-28 14:59
Yeah, I had this same exact problem and could not figure it out until I realized what I was doing! 

So, where you are probably messing up is that you are rezipping the entire folder again. You need to rezip ONLY the contents INSIDE the folder. 

For example if you export annotations you get the following zip output:
![image](https://user-images.githubusercontent.com/17066507/221891448-89a64be0-f3c6-4d4b-8c46-dd7c5e8c8fff.png)

If you rezip the entire folder again its messing up the structure and making it look like so:
![image](https://user-images.githubusercontent.com/17066507/221891979-1eae653c-6c1c-4851-8ece-74b07cfcee8c.png)

You should only rezip the contents inside the folder and then upload that!

**Comment by chebaperez** [comment] 2023-03-20 14:10
I had this same exact problem. However, I have already tried the approach suggested for @whittenator and unfortunately, it did not work for me. I made sure to only rezip the contents inside the folder, but I am still encountering the same issue. 

My zip:
![image](https://user-images.githubusercontent.com/8001802/226364536-8c78f390-46d9-4413-b97d-69f32fea84fa.png)

Content example of **obj_train_data** directory:
![image](https://user-images.githubusercontent.com/8001802/226365529-0feee857-3b73-4bb6-8554-d7ae34932dc8.png)

Content example of **train.txt** file:
![image](https://user-images.githubusercontent.com/8001802/226365380-81fda3a8-4571-4162-ba78-53dde3c329b1.png)

The error:
![image](https://user-images.githubusercontent.com/8001802/226363636-e6e6b3e4-bb41-412b-8134-f496d0745b34.png)

Any other suggestions or solutions that I could try?

Thanks!

**Comment by zhiltsov-max** [comment] 2023-03-22 17:06
Hi, please follow the answer above and check the files inside the archive. The expected file structure is described [here](https://opencv.github.io/cvat/docs/manual/advanced/formats/format-yolo/#yolo-export). Please note that there is often a problem with an extra leading directory in the archive (so the files are 1 level deeper than expected). I will close the issue, don't hesitate to reopen if the problem is not resolved.

**Closed by zhiltsov-max** 2023-03-22 17:06 UTC
