### ISSUE TITLE
Assign Tasks/Jobs to different users

### ISSUE THREAD

**Issue by MIRA-KUMAR** [opencv/cvat#5951] opened 2023-03-29 00:52 UTC
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. https://opencv.github.io/cvat/docs/api_sdk/sdk/highlevel-api/
2. Unable to assign tasks/jobs to different users
3. How to do that with above api?

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

**Comment by nmanovic** [comment] 2023-03-31 08:04
@SpecLad , could you please answer?

**Comment by zhiltsov-max** [comment] 2023-04-05 07:43
Hi, please use [this test](https://github.com/opencv/cvat/blob/develop/tests/python/sdk/test_jobs.py#L89-L98) as an example for the High-level SDK API. You need to call the `update()` method of the task or job and pass the assignee field.

```python
with Client(...) as client:
    client.tasks.retrieve(task_id).update({'assignee_id': assignee_id1})
    client.jobs.retrieve(job_id).update({'assignee': assignee_id2})
```

Job update parameters: https://opencv.github.io/cvat/docs/api_sdk/sdk/reference/models/patched-job-write-request/
Task update parameters: https://opencv.github.io/cvat/docs/api_sdk/sdk/reference/models/patched-task-write-request/

**Comment by zhiltsov-max** [comment] 2023-04-13 20:12
I will close the issue, don't hesitate to reopen it, if the problem is not resolved.

**Closed by zhiltsov-max** 2023-04-13 20:12 UTC
Labels: question, sdk/cli
