### ISSUE TITLE
Incorrect confusion matrix when GT job is created with a percentage of the entire task dataset (less than 100%)

### ISSUE THREAD

**Issue by Marishka17** [opencv/cvat#7424] opened 2024-02-01 18:18 UTC
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Create a task
2. Create a GT job with some percentage of annotations (less than 100)
3. Annotate the GT job, change stage/state
4. Create a quality report for the task
5. Check comparision_summary -> annotations -> confusion_matrix

There is an example with the resulting incorrect confusion matrix.
![image](https://github.com/opencv/cvat/assets/49038720/a08666e5-62e1-4ffc-a375-e60911fb27e4)

**Comment by Viditagarwal7479** [comment] 2024-03-05 23:56
@nmanovic can you please assign this issue to me?

**Comment by Viditagarwal7479** [comment] 2024-03-08 15:56
Does anyone has any idea Why in this [line](https://github.com/opencv/cvat/blob/develop/cvat/apps/quality_control/quality_reports.py#L151) the annotation of type `dm.AnnotationType.label` is missing?

**Comment by Viditagarwal7479** [comment] 2024-03-08 20:36
Hey @Marishka17 , Can you please let me know what type of annotation are you performing i.e., annotating as a label, mask, shape, skeleton, etc?

**Comment by Viditagarwal7479** [comment] 2024-03-09 11:32
As per my experiments the issue is coming when label type as `Tag` is used, in case label type `Rectangle` is used then there's no issue. Looking at the code, the implementation of all types of labels is same expect for the `Tag` i.e., `dm.AnnotationType.label`. I am looking at fixing this for `dm.AnnotationType.label`

**Comment by zhiltsov-max** [comment] 2024-03-11 15:46
Seems like the problem is that confusion matrices are missing from data accumulation during task report computation from job reports ([here](https://github.com/opencv/cvat/blob/cd5cd4412afa9829c56fcb63cf49458ccc65de08/cvat/apps/quality_control/quality_reports.py#L2387-L2409)). To reproduce: create a task with several normal jobs and a gt job. Compute a quality report.

**Comment by Marishka17** [comment] 2024-03-11 15:59
@Viditagarwal7479, Looks like I missed in the experiment that my 2 tasks had different numbers of jobs. I've rechecked the issue and prepared 2 backups for investigation. 
 [task_task with 1 job_backup_2024_03_11_15_48_45.zip](https://github.com/opencv/cvat/files/14561154/task_task.with.1.job_backup_2024_03_11_15_48_45.zip)
[task_task with 10 jobs_backup_2024_03_11_15_48_27.zip](https://github.com/opencv/cvat/files/14561155/task_task.with.10.jobs_backup_2024_03_11_15_48_27.zip)

**Comment by zhiltsov-max** [comment] 2024-03-13 08:02
@Viditagarwal7479, basically, I agree about the 2nd variant, but consider using the same approach as in the frame confusion matrix accumulation for job reports. There can be many jobs in the task, and accumulating them with numpy will be more efficient.

**Comment by Viditagarwal7479** [comment] 2024-03-13 08:08
True, this sounds good. In the loop I will store all the confusion matrix rows in a list and then using numpy compute the final confusion matrix in a single function call.

**Comment by Viditagarwal7479** [comment] 2024-03-16 13:41
Hello @Marishka17, how did you create a task with multiple jobs? When I am trying to add more jobs, it only gives the option to add a single ground truth job. Except for that single GT job, I am unable to find the option to add any other job.
<img width="1470" alt="image" src="https://github.com/opencv/cvat/assets/72168180/847aa331-2ae5-4447-b5fe-5c00a494e317">

**Comment by zhiltsov-max** [comment] 2024-03-16 14:06
@Viditagarwal7479 , it is done by specifying Segment size during task creation in the Advanced options. In CVAT, you can only create normal jobs during task creation. Suppose you have 10 images. Segment size of 2 will create 5 jobs.

**Comment by Viditagarwal7479** [comment] 2024-03-16 14:08
Ohh amazing. Thank you so much @zhiltsov-max.

**Closed** 2024-03-25 14:48 UTC
Labels: bug, good first issue
