### ISSUE TITLE
CVAT will not let me upload any type of annotation

### ISSUE THREAD

**Issue by canweffplease** [opencv/cvat#4776] opened 2022-07-22 13:49 UTC
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I have tried multiple different formats and I keep getting an error telling me to check the browser console every time I try to upload annotations. 
### Expected Behaviour

For testing purposes, I want it so that I can export annotations from CVAT, delete those annotations, then import them back. 
### Current Behaviour

CVAT will not let me upload. 
### Steps to Reproduce (for bugs)

1. Annotate 12 files in CVAT
1. Export the annotations 
1. Delete annotations in the CVAT UI 
1. Import exported annotations back into task

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.
![image](https://user-images.githubusercontent.com/87316434/180453083-21d4e0d2-5ba2-4d02-a3c6-8d1cb9b32ea1.png)
![image](https://user-images.githubusercontent.com/87316434/180453200-6b65d494-0c61-4257-9ee9-7ffe6f551ca1.png)

**Comment by bsekachev** [comment] 2022-08-25 07:55
Hi, I am not sure the issue is still relevant. 

So, have you tried to do logout/login? 
If it is not the first time you use CVAT, was you able to dump annotations before?
Could you please send us logs from cvat container? (docker logs cvat)

**Comment by bsekachev** [comment] 2022-09-06 20:32
I will close the issue for now. 
Do not hesitate to reopen if you have any updates.

**Closed by bsekachev** 2022-09-06 20:32 UTC
Labels: need info

**Comment by bit-scientist** [comment] 2023-02-21 05:51
@bsekachev could you help solve this #5653?
