### ISSUE TITLE
Unable to edit skeleton SVG

### ISSUE THREAD

**Issue by iqraRajpoot** [opencv/cvat#6022] opened 2023-04-14 08:17 UTC
### My actions before raising this issue
https://opencv.github.io/cvat/docs/manual/advanced/annotation-with-skeletons/editing-the-skeleton/

I am trying to edit the skeleton from the svg, when click to add one more connection link by clicking on a button called "Click two points to setup an edge" to SVG and then clicking to continue it gives error, and all of the projects and tasks deleted from the organization.

### Steps to Reproduce (for bugs)
1. create a project and upload an SVG file for the skeleton and save that project. 
2. Then, delete the skeleton from that project.
3. afterward upload SVG again and try to add a new connection between keypoints in the skeleton by clicking on a button called "Click two points to setup an edge".
4. Click on "continue," and an error message will appear. After that, all the projects in the entire organization will be deleted. (I am attaching screenshots of the error message and LOGs).
5. 
![Screenshot from 2023-04-06 15-41-22](https://user-images.githubusercontent.com/35895082/231985782-3aa886ad-c7b5-46c1-90f4-d5ae99396d51.png)
![Screenshot from 2023-04-06 15-41-30](https://user-images.githubusercontent.com/35895082/231985787-bbbd349d-a8af-4903-a5df-b1875574e3de.png)
![Screenshot from 2023-04-06 15-44-17](https://user-images.githubusercontent.com/35895082/231985790-f20d3a09-6aa3-4b07-a82d-5c556d4f3fe3.png)
![Screenshot from 2023-04-14 13-03-05](https://user-images.githubusercontent.com/35895082/231985802-f898d595-8599-4176-a86c-2c720ced9055.png)

### Expected Behaviour
it should allow us to add links to the SVG of the skeleton, Atleast, it should not delete all the projects from the whole organization.

### Current Behaviour
it is deleting all of the projects and task and giving me the error of " could not fetch projects" when I click on projects and task tabs.
![Screenshot from 2023-04-14 13-15-09](https://user-images.githubusercontent.com/35895082/231985994-b292457d-8375-4115-bcda-e9e56c43669b.png)

**Comment by iqraRajpoot** [comment] 2023-04-27 06:47
Here is the required information 
**SVG File:**
![b279ed20-aec1-40f7-95c5-63d892ac171a](https://user-images.githubusercontent.com/35895082/234780485-84d269b7-8703-4d91-ae4d-04eb29e8fc21.svg)
**CVAT server logs:**
[cvat_server_logs.txt](https://github.com/opencv/cvat/files/11340327/cvat_server_logs.txt)
**Git commit hash**
commit fb4af9ca09ffbf294fdb2b87b0b23a184894f1eb (HEAD -> release-2.3.0, origin/release-2.3.0)
Merge: 7e53d673 d699f1fa
Author: Nikita Manovich <nikita@cvat.ai>
Date:   Thu Dec 22 17:54:39 2022 +0200
Merge branch 'master' into release-2.3.0

**Comment by iqraRajpoot** [comment] 2023-04-27 06:50
Here is the required information 
**SVG File:**
https://drive.google.com/drive/folders/1E-yUfKuhyuT8meLxOVKXMmtskrH_d2yE?usp=sharing
**CVAT server logs:**
[cvat_server_logs.txt](https://github.com/opencv/cvat/files/11340327/cvat_server_logs.txt)
**Git commit hash**
commit fb4af9ca09ffbf294fdb2b87b0b23a184894f1eb (HEAD -> release-2.3.0, origin/release-2.3.0)
Merge: 7e53d673 d699f1fa
Author: Nikita Manovich <nikita@cvat.ai>
Date:   Thu Dec 22 17:54:39 2022 +0200
Merge branch 'master' into release-2.3.0

**Comment by iqraRajpoot** [comment] 2023-05-03 06:34
@bsekachev I wanted to follow up on the issue I raised earlier and let you know that I have provided all the required information. I am waiting for your response and would appreciate it if you could take a look at the issue.
thank you.

**Comment by bsekachev** [comment] 2023-05-03 09:26
Hi @iqraRajpoot 

I was not able to reproduce exactly the error you reported.
But I can confirm that the skeleton file you provided is not correct a little bit. It can not be added to a project.
If this file was provided by CVAT, it is a bug.

To fix that, you need to remove "id" properties from ```<desc data-description-type="labels-specification"> </desc> value```. 
In this example I have:

```
<desc data-description-type="labels-specification">{"1":{"name":"1","attributes":[],"color":"#d12345","type":"points"},"2":{"name":"2","attributes":[],"color":"#350dea","type":"points"},"3":{"name":"3","attributes":[],"color":"#479ffe","type":"points"},"4":{"name":"4","attributes":[],"color":"#4a649f","type":"points"},"5":{"name":"5","attributes":[],"color":"#478144","type":"points"},"6":{"name":"6","attributes":[],"color":"#57236b","type":"points"},"7":{"name":"7","attributes":[],"color":"#1cdda5","type":"points"},"8":{"name":"8","attributes":[],"color":"#e2bc6e","type":"points"},"9":{"name":"9","attributes":[],"color":"#f067db","type":"points"},"10":{"name":"10","attributes":[],"color":"#63bbfa","type":"points"},"11":{"name":"11","attributes":[],"color":"#22b16f","type":"points"},"12":{"name":"12","attributes":[],"color":"#daddec","type":"points"},"13":{"name":"13","attributes":[],"color":"#2ac791","type":"points"},"14":{"name":"14","attributes":[],"color":"#de22a0","type":"points"},"15":{"name":"15","attributes":[],"color":"#a7a570","type":"points"},"16":{"name":"16","attributes":[],"color":"#74db1b","type":"points"},"17":{"name":"17","attributes":[],"color":"#aaa246","type":"points"},"18":{"name":"18","attributes":[],"color":"#bfa552","type":"points"},"19":{"name":"19","attributes":[],"color":"#9b8d37","type":"points"},"20":{"name":"20","attributes":[],"color":"#c8023c","type":"points"},"21":{"name":"21","attributes":[],"color":"#c0762a","type":"points"},"22":{"name":"22","attributes":[],"color":"#76bb18","type":"points"},"23":{"name":"23","attributes":[],"color":"#afc7d8","type":"points"},"24":{"name":"24","attributes":[],"color":"#3b1ebf","type":"points"},"25":{"name":"25","attributes":[],"color":"#3d4e6a","type":"points"},"26":{"name":"26","attributes":[],"color":"#b295e8","type":"points"},"27":{"name":"27","attributes":[],"color":"#a8eeed","type":"points"},"28":{"name":"28","attributes":[],"color":"#1cb413","type":"points"},"29":{"name":"29","attributes":[],"color":"#b19fbd","type":"points"},"30":{"name":"30","attributes":[],"color":"#5cc934","type":"points"},"31":{"name":"31","attributes":[],"color":"#179232","type":"points"},"32":{"name":"32","attributes":[],"color":"#5d93c8","type":"points"},"33":{"name":"33","attributes":[],"color":"#0b9b66","type":"points"},"34":{"name":"34","attributes":[],"color":"#1004d4","type":"points"}}</desc>
```

Feature "Click two points to setup an edge" works as expected for me, there are not any errors.

**Comment by bsekachev** [comment] 2023-05-03 09:27
@yasakova-anastasia Could you please look at the issue ``cvat.apps.engine.models.Label.skeleton.RelatedObjectDoesNotExist: Label has no skeleton.`` in provided server logs?

**Comment by yasakova-anastasia** [comment] 2023-05-03 13:35
This issue (`cvat.apps.engine.models.Label.skeleton.RelatedObjectDoesNotExist: Label has no skeleton`) has been fixed by #5700.

We can't add a skeleton with sample svg to an existing project or task. I created an issue on this topic (#5706).

**Comment by iqraRajpoot** [comment] 2023-05-08 06:42
@bsekachev this Svg file was generated by CVAT and then downloaded as an Svg.

**Comment by bsekachev** [comment] 2023-05-08 19:38
Regarding the wrong SVG file downloaded, please refer to #5706. We will fix it ASAP.

**Closed** 2023-05-19 07:53 UTC
Labels: need info
