### ISSUE TITLE
Can't load video after restoring from backup

### ISSUE THREAD

**Issue by yasakova-anastasia** [opencv/cvat#4838] opened 2022-08-25 10:13 UTC
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Able to view data (video) after restoring from backup

### Current Behaviour

Keep buffering and the browser crash
![image](https://user-images.githubusercontent.com/44031030/184573117-6874b85e-ad30-4df0-ad94-819ecf26fc08.png)
![image](https://user-images.githubusercontent.com/44031030/184573140-302db474-0f77-48b5-8375-0ab55023e575.png)

### Steps to Reproduce (for bugs)

1. Back up the Project.
2. Restore the Project to another CVAT with "Create from backup".
3. Open Task.
4. Select job.
5. The data (video) keep buffering until the browser crash and show "This page is having problem".

### Your Environment

- Git hash commit (`git log -1`): b7dba6aa
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.17
- Are you using Docker Swarm or Kubernetes? Docker
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 18.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

Issue by @soizhiwen

**Comment by nmanovic** [comment] 2023-01-05 17:22
I was not able to reproduce the bug now. Probably it was fixed. I will close the issue.

**Closed by nmanovic** 2023-01-05 17:22 UTC
Labels: bug
