### ISSUE TITLE
CVAT new UI: Error in AAM

### ISSUE THREAD

**Issue by TOsmanov** [opencv/cvat#1750] opened 2020-06-18 12:23 UTC
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

N/A
### Current Behaviour

An error occurs in AAM when switching to 2 frames, if the frames have objects created in shape mode.
### Possible Solution

N/A
### Steps to Reproduce (for bugs)

1. Сreate a task
1. Create objects on 2 frames (in shape mode)
1. Go to AAM
1. Switch 2 frames forward

### Context

N/A
### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS): 
Windows 10 (version 1809), 
Google chrome (Version 83.0.4103.106 (Official Build) (64-bit))
CVAT version
Server: 1.1
Core: 2.1.1
Canvas: 1.1.1
UI: 1.2.2
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>TypeError
Cannot read property 'pinned' of undefined

TypeError: Cannot read property 'pinned' of undefined
    at Du.deactivateShape (https://cvat.org/cvat-ui.min.js:72:1389530)
    at Du.deactivate (https://cvat.org/cvat-ui.min.js:72:1389953)
    at Du.activate (https://cvat.org/cvat-ui.min.js:72:1392547)
    at Du.notify (https://cvat.org/cvat-ui.min.js:72:1382384)
    at Ac.notify (https://cvat.org/cvat-ui.min.js:72:1298346)
    at Ac.activate (https://cvat.org/cvat-ui.min.js:72:1301430)
    at Iu.activate (https://cvat.org/cvat-ui.min.js:72:1397015)
    at pd.componentDidUpdate (https://cvat.org/cvat-ui.min.js:72:1430935)
    at yl (https://cvat.org/cvat-ui.min.js:43:100837)
    at t.unstable_runWithPriority (https://cvat.org/cvat-ui.min.js:51:3465)
</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment] 2020-06-18 13:17
Duplicate of #1614

**Closed** 2020-06-19 07:49 UTC
Labels: bug
