### ISSUE TITLE
Another track ID in annotation and on opened task

### ISSUE THREAD

**Issue by sbanori** [opencv/cvat#753] opened 2019-10-04 09:01 UTC
Hello everyone :)

I uploaded own model to CVAT, I made task with video and I used auto annotation.
In my case I have video with 126 frames, and model recognized total 925 boxes.
When I use dump annotation "CVAT XML 1.1 for images", everything looks ok and logically.
But when I use "CVAT XML 1.1 for video", I don't understand how works the naming of track Id in dumped xml file, because in opened task in CVAT's window I see another numbers. Total number of tracks is the same like in the CVAT's task window (925).

I supposed that was a problem with incorrect dumping annotation, but I made a test. I added new task with the same video and uploaded annotation. Boxes are on correct places so it means that CVAT understand this naming.

Numbers of track are from 0 to 924, but numbers in task's window ale from 1 to 925. I see that numbers of tracks are totally disagree with numbers of instances in task's window. They aren't even in close proximity to each other. Track with id = 916 on frame 49, can have BB on instance id = 123 on frame 49. Only frame is the same.

How it works?

**Comment by azhavoro** [comment] 2019-10-10 09:32
Hi @sbanori
all tracks are indexed during dump and track IDs in the dumped file are not correspond to IDs in the CVAT's task window, it's not a bug. We have 'track id' attribute for 'CVAT for video' format by historical reason and for backward compatibility.
https://github.com/opencv/cvat/blob/develop/cvat/apps/annotation/cvat.py#L309:L312

**Comment by azhavoro** [comment] 2019-10-11 06:17
I'll close the issue for now, don't hesitate ask your questions on gitter.

**Closed by azhavoro** 2019-10-11 06:17 UTC
Labels: question
