### ISSUE TITLE
Can we only export annotated images along with their annotation?

### ISSUE THREAD

**Issue by ing-oasis** [opencv/cvat#4937] opened 2022-09-13 04:23 UTC
Kia Ora.

Thanks for your hard work, it is a great experience to use CVAT in recent months.

### Expected Behaviour
I know that it used to be this way, just export annotated images and discard unannotated ones.

### Current Behaviour
If annotate frames in videos, tick 'save images' would export all images, annotated or not.

### Possible Solution
Add a checkbox, so users can choose to export all images or just annotated ones.

Regards

**Comment by nmanovic** [comment] 2022-09-13 04:27
@ing-oasis , the biggest problem here is to understand what an image is annotated. In general "image is annotated" isn't equal to "image has annotation". But probably we can provide some settings for an export operation. Thus an user will decide.

**Comment by ing-oasis** [comment] 2022-09-13 04:32
> @ing-oasis , the biggest problem here is to understand what an image is annotated. In general "image is annotated" isn't equal to "image has annotations". But probably we can provide some settings for an export operation. Thus an user will decide.

Thanks for the quick reply. "image has annotations" is enough for me, sorry for the confusion.

**Comment by zhiltsov-max** [comment] 2022-09-16 09:27
Hi, currently we can only export all images from CVAT, both annotated and un-annotated. Please refer to https://github.com/opencv/cvat/issues/1251#issuecomment-598221121 for a solution.

**Comment by nmanovic** [comment] 2023-01-05 16:39
@ing-oasis , we don't have nearest plans to improve the functionality. To reduce the number of issues on GitHub I will close the issue. Don't hesitate to contribute us. We will be happy to access a feature like that.

**Closed by nmanovic** 2023-01-05 16:39 UTC
Labels: enhancement

**Comment by IndefiniteBen** [comment] 2023-08-04 15:42
I think an option like this in the UI has value over the solution in #1251, as that solution still requires downloading all of the images before removing the unannotated ones locally. 
If you can download only annotated images it will reduce the download time and size. 

Obviously this is fairly low priority and closed, but I thought it worth mentioning the issue with the proposed solution.

**Comment by AlainPilon** [comment] 2023-08-29 13:41
Google landed me here. I think this feature would be mostly useful when generating a set of images from a video sequence as I am currently doing. Taking an image every 45 frames, about 1/4 of my images are not usable so having a quick way to clean them up with the 'do not include pictures without annotations' would be useful.

**Comment by dceluis** [comment] 2023-10-27 07:49
I agree, it would be very useful!

**Comment by zhiltsov-max** [comment] 2023-10-27 08:04
@AlainPilon, there is the `frame step` [task creation option](https://opencv.github.io/cvat/docs/manual/basics/create_an_annotation_task/#advanced-configuration) related to the situation you mentioned. Did you try it and does it work for you?

**Comment by AlainPilon** [comment] 2023-10-27 13:04
@zhiltsov-max taking pictures every x frame is easy, what we are talking about is that once I have extracted 100 pictures, out of 4500 (if taking pic every 45 frames), if I only annotated 90, I would not want the export to include the extra 10 as they have no value.

**Comment by dceluis** [comment] 2023-10-28 06:22
@zhiltsov-max To expand a bit on the use case, with an example. On a 10-minute video, I may identify about 30 frames to annotate and add to my larger dataset. In my current workflow, I would use any other software to crop the video into the particular section of interest. Then I would upload that to cvat and annotate its frames.

The problem is that cropping the video with to-the-frame precision requires me to craft a particular ffmpeg command to do it correctly. Plus, if the 30 frames are not consecutive then I would need to possibly crop the video in many places, (and upload them separately to cvat), or export the frames one by one with vlc for example, and upload those.

If we had the option to export only the annotated frames from Cvat then annotating a frame becomes (implicitly) _the way_ of extracting the frames of interest. I could upload a complete video, import all frames, and export only the ones I found of enough interest to annotate. This saves time and effort when working with larger, unedited videos.

**Comment by cjfinc** [comment] 2024-01-02 21:21
The proposed solution with Datumaro is bad, because you have to export full dataset in Datumaro format first, that could be 10-100-1000X larger if you have not many frames annotated in your videos. That will eat a lot of space on the server to prepare export files and will took ridiculously a lot of time. 
https://github.com/opencv/cvat/issues/1251#issuecomment-598221121

It's strange it takes so long for team to fix it / add option.
Anyway, here is my fix if you need it
https://gist.github.com/cjfinc/732c30731a93247b043df70f41bf76ae

**Comment by Quakumei** [comment] 2024-10-22 07:06
Did the feature make it to the codebase?

**Comment by gstrat88** [comment] 2025-03-14 13:39
> The proposed solution with Datumaro is bad, because you have to export full dataset in Datumaro format first, that could be 10-100-1000X larger if you have not many frames annotated in your videos. That will eat a lot of space on the server to prepare export files and will took ridiculously a lot of time. [#1251 (comment)](https://github.com/cvat-ai/cvat/issues/1251#issuecomment-598221121)
> 
> It's strange it takes so long for team to fix it / add option. Anyway, here is my fix if you need it https://gist.github.com/cjfinc/732c30731a93247b043df70f41bf76ae

by looking at the source code my proposal for a pull request is to utilize the datumaro filter options
i believe each format ([e.g[(https://github.com/cvat-ai/cvat/blob/develop/cvat/apps/dataset_manager/formats/yolo.py)) could use a _export_common helper function whenever possible and inside there, filter by datumaro which provides the needed filter out of the box

I can help with that if we decide so!

**Comment by zhiltsov-max** [comment] 2025-03-14 13:54
Such feature wasn't included in the codebase. However, there is an updated code snippet than can help getting the result:

```python
import json
import sys
from argparse import ArgumentParser
from typing import List, Optional

from cvat_sdk import make_client


def main(args: Optional[List[str]] = None) -> int:
    parser = ArgumentParser(description="Downloads task annotations")
    parser.add_argument("--org", help="Org slug")
    parser.add_argument("task_id", type=int, help="Task id")
    parsed_args = parser.parse_args(args)

    with make_client(
        "https://app.cvat.ai", port=443, credentials=("username", "password")  # fill yours
    ) as client:
        client.organization_slug = parsed_args.org
        client.config.status_check_period = 2

        task = client.tasks.retrieve(parsed_args.task_id)

        # Option A: download raw annotations and parse annotation objects
        annotations = task.get_annotations()
        print(annotations.shapes[0])

        # or download raw annotations explicitly
        (_, response) = task.api.retrieve_annotations(task.id, _parse_response=False)
        annotations = json.loads(response.data)
        print(annotations["shapes"][0])

        # filter and save as raw annotations or convert into your desired format manually
        with open(f"task-{task.id}-annotations.json", "w") as f:
            json.dump(annotations, f, indent=2)

        # Option B: mark frames with no annotations as "deleted", export dataset
        annotations = task.get_annotations()

        frames_with_annotations: set[int] = set()
        for tag in annotations.tags:
            frames_with_annotations.add(tag.frame)

        for shape in annotations.shapes:
            frames_with_annotations.add(shape.frame)

        # tracks will require more analysis, as only the keyframes are present in the response

        # remove the empty frames
        meta = task.get_meta()
        frame_step = int(meta.frame_filter.split("=")[-1]) if meta.frame_filter else 1
        task.remove_frames_by_ids(
            list(
                set(range(meta.start_frame, meta.stop_frame + 1, frame_step))
                - set(frames_with_annotations)
            )
        )

        task.export_dataset(
            format_name="CVAT for images 1.1",  # specify the format needed
            # check https://app.cvat.ai/api/swagger/#/server/server_retrieve_annotation_formats
            # for format names
            filename=f"task-{task.id}-export.zip",
            include_images=True, # True / False
        )

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))

```
