### ISSUE TITLE
Polygon editor does not open

### ISSUE THREAD

**Issue by raunilillemets** [opencv/cvat#602] opened 2019-07-31 10:16 UTC
Hello, according to the manual (section "annotation with polygons") it is possible to edit the polygon after completing it by double-clicking with pressed Shift.

However, if I hover over the polygon and double-click with pressed Shift, the polygon editor does not open. Instead, the zoom level is reset to the default zoom level.

CVAT version is 0.5

**Comment by raunilillemets** [comment] 2019-07-31 10:38
Further testing showed that this is show specific to my computer/browser (Google Chrome version 75.0.3770.142). In incognito mode and a colleague's computer the functionality worked perfectly. Disabling all extensions and cleaning cache did not help.

Since there is no way that any of the CVAT developers can re-produce this, I think that this issue needs to be closed (unless I can find more information about why this happens on my computer).

**Comment by bsekachev** [comment] 2019-07-31 10:52
@raunilillemets 
This is interesting issue. As far as I known your case is the second. We have came across to this issue once before and we also didn't find the reason, just used incognito mode.

**Comment by bsekachev** [comment] 2019-07-31 10:54
@raunilillemets 
I believe it should be investigated. But we couldn't reproduce it, so, I just don't know what to do.

**Comment by nmanovic** [comment] 2019-08-02 09:21
@raunilillemets , @bsekachev , let's keep the bug for a while. I hope to hear more from our community how to reproduce it.

**Comment by FCollaPi** [comment] 2020-02-26 23:33
I am facing a similar issue. The first time I try shift + double click it works just fine. The second time the polygon I am trying to edit goes hidden (radio button keeps the same but it has to be double clicked for the object to go visible again). Then the third time I try it the zoom is reset. I can only make it work again by refreshing the page but then the bug loop restarts.

CVAT is version 3.2.0.

docker-compose version 1.25.4, build unknown
docker-py version: 4.2.0
CPython version: 3.5.2
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016

Google Chrome Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by bsekachev** [comment] 2020-02-27 05:30
@FCollaPi Sounds like another issue. In your case probably there are some exceprtions in the browser console, aren't they? Anyway, I would recommend you update CVAT because the version 3.2 is rather old

**Comment by FCollaPi** [comment] 2020-02-27 15:53
@bsekachev Yes, I am getting this error:

`cd88c77a0c88.js:15050 Uncaught TypeError: Cannot read property 'mousedown' of undefined
    at Function.SVG.off (cd88c77a0c88.js:15050)
    at initializer.off (cd88c77a0c88.js:15097)
    at initializer.draggable (cd88c77a0c88.js:17849)
    at PolygonView._makeNotEditable (eda1cbda7f00.js:5563)
    at PolygonView._makeNotEditable (eda1cbda7f00.js:6912)
    at PolygonView.onShapeUpdate (eda1cbda7f00.js:6483)
    at PolygonView.onShapeUpdate (eda1cbda7f00.js:6944)
    at PolygonModel.notify (eda1cbda7f00.js:1281)
    at PolygonModel.notify (eda1cbda7f00.js:4069)
    at PolygonModel.set active [as active] (eda1cbda7f00.js:4379)
SVG.off @ cd88c77a0c88.js:15050
off @ cd88c77a0c88.js:15097
draggable @ cd88c77a0c88.js:17849
_makeNotEditable @ eda1cbda7f00.js:5563
_makeNotEditable @ eda1cbda7f00.js:6912
onShapeUpdate @ eda1cbda7f00.js:6483
onShapeUpdate @ eda1cbda7f00.js:6944
notify @ eda1cbda7f00.js:1281
notify @ eda1cbda7f00.js:4069
set active @ eda1cbda7f00.js:4379
resetActive @ eda1cbda7f00.js:9091
resetActive @ eda1cbda7f00.js:9746
(anonymous) @ eda1cbda7f00.js:9890
handle @ cd88c77a0c88.js:23821
dispatch @ cd88c77a0c88.js:23468
elemData.handle @ cd88c77a0c88.js:23276`

Regarding the version, I installed CVAT following the guide on https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/installation.md just yesterday from develop branch. Is there any way to get a more recent one?

**Comment by FCollaPi** [comment] 2020-02-27 16:00
Correction: I was getting the version in a wrong way. Opening About tab I get

Server version: 0.6

Core version: 0.5.2

Canvas version: 0.5.2

UI version: 0.5.2

**Comment by bsekachev** [comment] 2020-02-27 16:24
@FCollaPi 

Can you provide steps to reproduce the issue?

**Comment by FCollaPi** [comment] 2020-02-27 16:50
@bsekachev 

- I installed CVAT following https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/installation.md
- Installed openVINO following https://github.com/opencv/cvat/tree/develop/components/openvino (downloaded 2019 R3 version from Intel website)
- Installed DEXTR following https://github.com/opencv/cvat/blob/develop/cvat/apps/dextr_segmentation/README.md
- Then during annotation it happens as I first commented:

> I am facing a similar issue. The first time I try shift + double click it works just fine. The second time the polygon I am trying to edit goes hidden (radio button keeps the same but it has to be double clicked for the object to go visible again). Then the third time I try it the zoom is reset. I can only make it work again by refreshing the page but then the bug loop restarts.

**Comment by bsekachev** [comment] 2020-02-28 12:28
@FCollaPi 

Okay, I checked it.
I get a bit other exceptions:

```
Uncaught TypeError: Cannot read property 'drawstart' of undefined
    at Function.SVG.off (svg.js:3493)
    at initializer.off (svg.js:3521)
    at PolyshapeEditorView._endEdit (polyshapeEditor.js:430)
    at PolyshapeEditorView.onPolyshapeEditorUpdate (polyshapeEditor.js:457)
    at PolyshapeEditorModel.notify (listener.js:48)
    at PolyshapeEditorModel.cancel (polyshapeEditor.js:83)
    at PolyshapeEditorModel.finish (polyshapeEditor.js:63)
    at PolyshapeEditorController.finish (polyshapeEditor.js:108)
    at initializer.<anonymous> (polyshapeEditor.js:405)
SVG.off @ svg.js:3493
off @ svg.js:3521
_endEdit @ polyshapeEditor.js:430
onPolyshapeEditorUpdate @ polyshapeEditor.js:457
notify @ listener.js:48
cancel @ polyshapeEditor.js:83
finish @ polyshapeEditor.js:63
finish @ polyshapeEditor.js:108
(anonymous) @ polyshapeEditor.js:405
[Violation] 'mousedown' handler took 1797ms
polyshapeEditor.js:426 Uncaught TypeError: Cannot read property 'remove' of null
    at PolyshapeEditorView._endEdit (polyshapeEditor.js:426)
    at PolyshapeEditorView.onPolyshapeEditorUpdate (polyshapeEditor.js:457)
    at PolyshapeEditorModel.notify (listener.js:48)
    at PolyshapeEditorModel.cancel (polyshapeEditor.js:83)
    at PolyshapeEditorModel.finish (polyshapeEditor.js:63)
    at annotationUI.js:228
    at logger.js:455
    at _fireCallback (mousetrap.js:616)
    at Mousetrap.self._handleKey (mousetrap.js:677)
    at Mousetrap.handleKey (mousetrap.js:994)
```

But behavior looks to be similar.

**Comment by bsekachev** [comment] 2020-02-28 13:10
@FCollaPi 

This PR should help: #1212

**Comment by FCollaPi** [comment] 2020-02-28 18:02
@bsekachev It's working! Thank you

**Comment by bsekachev** [comment] 2020-07-09 17:40
Let's close the issue. In new UI probably it is not a problem. Do not hesitate reopen if you still experience it.

**Closed by bsekachev** 2020-07-09 17:40 UTC
Labels: bug
