### ISSUE TITLE
[CLI] Cannot create a task with the current code

### ISSUE THREAD

**Issue by yohayonyon** [opencv/cvat#1522] opened 2020-05-12 08:14 UTC
Hi,

I already have one working CVAT server with a ~1 month old code.
I deployed a new server yesterday and CLI for task create does not work. I get:

> 400 Client Error: Bad Request for url: http://<machine_ip>:8080/api/v1/tasks/2/data

Same command works on the old server. LS command works well on the new server.

It seems like an issue in the current code.

**Comment by bsekachev** [comment] 2020-05-12 08:19
Probably related #1469

**Comment by yohayonyon** [comment] 2020-05-14 06:27
With the code from zm/fix-coverage it works fine.

**Comment by yohayonyon** [comment] 2020-05-14 06:45
More specific - the needed fix is in the CLI code. So, a server from origin/develop and a CLI tool code from zm/fix-coverage works as well.

**Comment by azhavoro** [comment] 2020-05-14 06:58
@yohayonyon Hi, could you please specify commit that you use? `docker log -1`
Thanks

**Comment by yohayonyon** [comment] 2020-05-14 07:30
I guess that you have meant git log -1 :-)

On the server:
`commit d62ae15f7709f2d1fd8c8bd58c1570e7312f493e (HEAD -> develop, origin/develop, origin/HEAD)
Author: Dmitry Kalinin <dmitry.kalinin@intel.com>
Date:   Wed May 13 23:01:13 2020 +0300`

On the machine using the CLI tool:
`commit 20f61dcb6b2027fae85ac4ab18e6b94419de4d62 (HEAD -> zm/fix-coverage, origin/zm/fix-coverage)
Merge: 0c94a85 5ab5499
Author: zhiltsov-max <zhiltsov.max35@gmail.com>
Date:   Wed May 13 11:42:05 2020 +0300`

**Comment by azhavoro** [comment] 2020-05-14 07:59
> I guess that you have meant git log -1 :-)

sure, sorry for that
I'll try to reproduce the issue

**Comment by yohayonyon** [comment] 2020-05-14 08:40
To be clear - when the machine sending the CLI commands used the develop code it failed. When using the commit above, it passed.

**Comment by azhavoro** [comment] 2020-07-30 06:28
@yohayonyon Should be fixed in the develop branch. I'll close the issue, feel free to reopen if the problem is still actual for you.

**Closed by azhavoro** 2020-07-30 06:28 UTC
Labels: bug
