### ISSUE TITLE
unable to see the auto segmentation option in cvat

### ISSUE THREAD

**Issue by ghSaint** [opencv/cvat#1243] opened 2020-03-07 13:52 UTC
hihi, i tried to follow the below 2 links instructions. however, after successfully installing and downloading the required stuff, the auto segmentation option is still not made available in cvat.

https://github.com/opencv/cvat/blob/develop/cvat/apps/auto_annotation/README.md
https://github.com/opencv/cvat/blob/develop/components/auto_segmentation/README.md

how could i go about resolving it?

**Comment by azhavoro** [comment] 2020-03-10 07:09
@ghSaint Hi,
What docker-compose command did you use to build the images?

**Comment by BenoCharlo** [comment] 2020-03-10 15:14
Hello, I am facing the same issue. I can't figure out how to activate the auto-segmentation mode even if I pass the "yes" argument to AUTO_SEGMENTATION in my docker-compose file.

Is there anything else I should change before seeing the auto-segmentation live after creating my bounding box?

Thank you :)

**Comment by azhavoro** [comment] 2020-03-10 15:34
@BenoCharlo Hi, mask RCNN Object Detector model should be available if you built images with command:
`docker-compose -f docker-compose.yml -f components/auto_segmentation/docker-compose.auto_segmentation.yml up -d build` You dont need manually change docker-compose file. 
Usage of this component is different from you description, the model should be visible in the `Models` menu as described here:
![image](https://user-images.githubusercontent.com/41117609/76329304-748f0780-62fd-11ea-9293-fcdfff246989.png)
Maybe do you mean https://github.com/opencv/cvat/tree/develop/cvat/apps/dextr_segmentation?

**Comment by BenoCharlo** [comment] 2020-03-10 15:39
> @BenoCharlo Hi, mask RCNN Object Detector model should be available if you built images with command:
> `docker-compose -f docker-compose.yml -f components/auto_segmentation/docker-compose.auto_segmentation.yml up -d build` You dont need manually change docker-compose file.
> Usage of this component is different from you description, the model should be visible in the `Models` menu as described here:
> ![image](https://user-images.githubusercontent.com/41117609/76329304-748f0780-62fd-11ea-9293-fcdfff246989.png)
> Maybe do you mean https://github.com/opencv/cvat/tree/develop/cvat/apps/dextr_segmentation?

Thank you @azhavoro, Il will try it out and keep you posted.

**Comment by azhavoro** [comment] 2020-03-13 09:46
@ghSaint Hi, did you fix the issue?

**Comment by azhavoro** [comment] 2020-03-24 07:50
I hope you fix the issue and close it. Don't hesitate to reopen if the issue is still relevant for you.

**Closed by azhavoro** 2020-03-24 07:50 UTC
