### ISSUE TITLE
Failed installing cvat on ubuntu 18.04

### ISSUE THREAD

**Issue by marcobevih2o** [opencv/cvat#704] opened 2019-09-10 12:06 UTC
I try to install cvat on ubuntu 18.04. but the installation procedure faild at this point

Successfully built 6589b39062ca
Successfully tagged cvat:latest
Building cvat_ui
Step 1/17 : FROM ubuntu:18.04 AS cvat-ui
 ---> 7698f282e524
Step 2/17 : ARG http_proxy
 ---> Using cache
 ---> 7363be2f907b
Step 3/17 : ARG https_proxy
 ---> Using cache
 ---> fd397f6e388f
Step 4/17 : ARG no_proxy
 ---> Using cache
 ---> 95720115074b
Step 5/17 : ARG socks_proxy
 ---> Using cache
 ---> 54760755446b
Step 6/17 : ENV TERM=xterm     http_proxy=${http_proxy}       https_proxy=${https_proxy}     no_proxy=${no_proxy}     socks_proxy=${socks_proxy}
 ---> Using cache
 ---> 2dfc665d1b08
Step 7/17 : ENV LANG='C.UTF-8'      LC_ALL='C.UTF-8'
 ---> Using cache
 ---> fc0b353e2ba2
Step 8/17 : RUN apt update && apt install -yq nodejs npm curl &&     npm install -g n && n 10.16.3
 ---> Running in 327556caa49b

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:4 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [766 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
Get:8 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [4957 B]
Get:9 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [7802 B]
Get:10 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [640 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:13 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [19.0 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1284 kB]
Ign:15 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [8000 B]
Get:17 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [2496 B]
Get:18 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [4212 B]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [944 kB]
Err:15 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
  File has unexpected size (944475 != 944473). Mirror sync in progress? [IP: 91.189.88.175 80]
  Hashes of expected file:
   - Filesize:944473 [weak]
   - SHA256:788d8f45d75965dd2488c7e7544abf405cda2d344e1aafd52173605a87545c6b
   - SHA1:77c8a594b696d2b4c1b57d648b67ab3805fac60d [weak]
   - MD5Sum:8526e702a621000576befde8d0c18dc1 [weak]
  Release file created at: Tue, 10 Sep 2019 08:16:28 +0000
Fetched 16.1 MB in 13s (1256 kB/s)
Reading package lists...
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/main/binary-amd64/Packages.gz  File has unexpected size (944475 != 944473). Mirror sync in progress? [IP: 91.189.88.175 80]
   Hashes of expected file:
    - Filesize:944473 [weak]
    - SHA256:788d8f45d75965dd2488c7e7544abf405cda2d344e1aafd52173605a87545c6b
    - SHA1:77c8a594b696d2b4c1b57d648b67ab3805fac60d [weak]
    - MD5Sum:8526e702a621000576befde8d0c18dc1 [weak]
   Release file created at: Tue, 10 Sep 2019 08:16:28 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
ERROR: Service 'cvat_ui' failed to build: The command '/bin/sh -c apt update && apt install -yq nodejs npm curl &&     npm install -g n && n 10.16.3' returned a non-zero code: 100

**Comment by bsekachev** [comment] 2019-09-10 13:21
@marcobevih2o 

Is this error reproduced in every built?

**Comment by marcobevih2o** [comment] 2019-09-11 09:11
i solved installing nodejs before start steps in the installation guide

**Comment by nmanovic** [comment] 2019-09-13 07:49
@marcobevih2o , I don't think that your step helped your resolve your problems. It was a network issue. I will close the issue for now. Let's see if somebody else has a similar problem.

**Closed by nmanovic** 2019-09-13 07:49 UTC
Labels: question

**Comment by QuarTerll** [comment] 2020-05-22 01:58
why not just uploading your final official successful image on the docker hub even alpha edition? Then we can just pull it.

**Comment by bsekachev** [comment] 2020-05-22 09:51
@QuarTerll 

Unfortunately it isn't simple because of bureaucracy and legal issues.
