### ISSUE TITLE
Wrong filename used when importing from cloud storage after another import

### ISSUE THREAD

**Issue by SpecLad** [opencv/cvat#7428] opened 2024-02-02 16:09 UTC
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Create a task.
2. Export the task's annotations twice: first to the local computer (name it `foobar.zip`), then to a cloud storage (name it `bazquux.zip`).
3. Import the annotations from `foobar.zip`.
4. Import the annotations from the cloud storage, entering `bazquux.zip` as the name.

The last step fails and shows the following error:

> rest_framework.exceptions.NotFound: The file 'foobar.zip' not found on the cloud storage '[redacted]'.

### Expected Behavior

CVAT should import the annotations from `bazquux.zip`.

### Context

I hit this while testing import-related functionality.

### Environment

```Markdown
Reproducible on commit 27f8aa7ea and also on app.cvat.ai.
```

**Comment by umangapatel123** [comment] 2024-03-09 11:34
@nmanovic I am interested to contribute in this issue.  can you please assign this issue to me?

**Comment by umangapatel123** [comment] 2024-03-10 18:30
@nmanovic I have reproduced the issue. The error mentioned in the issue is correct. Here is the screenshot of the issue
![issue](https://github.com/opencv/cvat/assets/113035910/981373fc-967b-4d62-be4d-187dd5aa4d50)

Upon reviewing the code, I figured out that there is an issue with the import annotation typescript code which is located at `cvat/cvat-ui/src/components/import-dataset/import-dataset-modal.tsx`. whenever the local file is imported, the `file` parameter is used from the `uploadParams` to store file metadata and for cloud import `fileName` is used to store file name. There is also a separate state to only store `file`. so when `foobar.zip` is uploaded its metadata is stored in `file` and `uploadParams.file`. After importing is done `closeModal` function (Line no. 227 ) is called to reset parameters but it only sets `file` to null. It doesn't set `uploadParams.file` to null.
![closeModal](https://github.com/opencv/cvat/assets/113035910/0604784c-0b62-49ec-bf1d-c5b8e826e920)

Also, there is no dependency on `file` in useEffect at line 95. so there also it doesn't set `uploadParams.file` to null
![uploadParams](https://github.com/opencv/cvat/assets/113035910/9d01ea13-e3e6-49b9-b12c-fe3b4c785e9f)

When we import annotation from the cloud, according to line number 243 `uploadParams.file` is used since it is not null. Hence it considers the filename as `foobar.zip` instead of `bazquux.zip`
![importDataSetAsync](https://github.com/opencv/cvat/assets/113035910/2f189b5e-7165-4faf-aa5d-530ff172f0f5)

Please allow me to solve this issue. Also, if you have any suggestions please let me know.

**Comment by nmanovic** [comment] 2024-03-11 08:58
@klakhov , could you please comment?

**Comment by klakhov** [comment] 2024-03-11 10:22
Hi @umangapatel123, it looks like you found out the root cause of the issue.
The problem may be solved with updating `useEffect` you've mentioned. As its already done with `resource` variable. We need to reset uploadParams.file and probably uploadParams.fileName when `file` is reset.

If you want to improve this component even further, you can see that the component has large state, there is lots of `useState` here. It would be great if we could use `useReducer` instead of many `useState`. You can see the [example here](https://github.com/opencv/cvat/blob/develop/cvat-ui/src/components/annotation-page/annotations-actions/annotations-actions-modal.tsx). With that approach we can use something like `SET_FILE` action to update state in all required places simultaneously.

You can start working on the PR to this issue. The first approach is fine. But it would be great if you could help us with refactoring too.

**Closed** 2024-03-15 07:55 UTC
Labels: bug, good first issue
