### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by azhavoro** [opencv/cvat#2308] opened 2020-10-12 14:00 UTC
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

```js
TypeError: Cannot read property 'id' of undefined
    at Worker.e.onerror (https://cvat.org/cvat-ui.9db7ed0e8341e910b6de.min.js:22:109591)
```

### Expected Behaviour
Proper error message in the browser console

### Current Behaviour
If a data chunk cannot be downloaded by the client by some reason this exception occurs.

### Possible Solution
Handle the error event properly

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):2b221d26fd65cd4f7c81d19247459f3f2416ed73
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment] 2021-07-26 10:37
@azhavoro 

The issue is still relevant and one of the most often email notifications we recieve.

**Comment by bsekachev** [comment] 2022-08-21 11:45
The issue is quite old and maybe outdated. 
Since it does not have a way to reproduce I will close the issue now and maybe will investigate it in the future if it appears again.

**Closed by bsekachev** 2022-08-21 11:45 UTC
Labels: bug
