### ISSUE TITLE
Custom Model Deployment 

### ISSUE THREAD

**Issue by purvaja2001** [opencv/cvat#7541] opened 2024-03-01 07:39 UTC
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

### Steps to Reproduce

1. Deployment of serverless in CVAT.
2. Using custom model

### Expected Behavior

It should either give out an error or allow us to deploy other models but when my custom model is working properly, I am not able to deploy the existing models as well.
It is in Building state since 3 days, Error is not coming. I am unable to view or deploy other models as well

**Comment by nmanovic** [comment] 2024-03-01 09:52
@purvaja2001 , please provide us exact steps to reproduce the issue. We cannot help if we don't know on how to reproduce the issue on our side.

**Comment by nmanovic** [comment] 2024-03-05 06:43
@purvaja2001 , if you cannot deploy a function from our open-source repository, we can help because we have all the necessary code to reproduce the issue on our side. If you are trying to deploy your own function, we cannot help. Please read our documentation and other examples. I will close the issue.

**Closed by nmanovic** 2024-03-05 06:43 UTC
Labels: bug, need info

**Comment by purvaja2001** [comment] 2024-03-07 07:23
Hi, it's not about deployment of custom model. 
Why is it not possible to deploy another model or access the Models tab while one model is in building state ?

**Comment by venuss920** [comment] 2024-08-22 11:20
I am also trained my model and have stored in a local directory, I am using hugging face transformers fro SAM fine tuning, however I am not able to deploy it on CVAt? is there any development or any path to follow this?
