### ISSUE TITLE
Incorrect Task Progress Bar on official CVAT (app.cvat.ai) and 2.4.2, 2.4.3

### ISSUE THREAD

**Issue by mnicnc404** [opencv/cvat#6098] opened 2023-05-03 08:24 UTC
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Bug Abstract

Both CVAT 2.4.2, 2.4.3 and official CVAT ( [https://app.cvat.ai](https://app.cvat.ai) ) shows incorrect progress on task progress bar when any of the underneath jobs is labeled as `acceptance`. The number of completed jobs should be accepted jobs within the task, but instead it shows `[number of labels] * [number of completed jobs]` and thus the whole task can never be `completed`. 
**Update: 2.4.1 does not have this bug!**

### Steps to Reproduce (for bugs)

1. Create a task with 2 jobs and 3 labels. Set job 1 as completed. 
![cvat-1](https://user-images.githubusercontent.com/2225912/235851279-24da18e6-af75-4785-9c14-f876c3dc3ac7.png)
2. Return to task page. It should be `1 of 2 jobs`, but instead it shows `3 of 2 jobs`. (3 == 1(completed jobs) * 3(labels))
![cvat-2](https://user-images.githubusercontent.com/2225912/236148229-b445c98b-4b17-4655-ac0d-0df638125550.png)
3. Set job 2 as completed. Now both job 1 and job 2 are completed.
![cvat-3](https://user-images.githubusercontent.com/2225912/235851298-714c5691-3f8e-4de9-8c95-66f60687c71f.png)
4. Return to task page. It should be `1 of 2 jobs`, but instead it shows `6 of 2 jobs`. (6 == 2(completed jobs) * 3(labels))
![cvat-4](https://user-images.githubusercontent.com/2225912/236148325-cb2f0881-0434-4e12-8b3c-81c93465b9da.png)
5. Add new label `d`. Now the task has 4 labels.
![cvat-5](https://user-images.githubusercontent.com/2225912/235851345-b11ed682-9e22-453b-8dbd-dc3440835df5.png)
6. Return to task page. It should be `1 of 2 jobs`, but instead it shows `8 of 2 jobs`. (8 == 2(completed jobs) * 4(labels))
![cvat-6](https://user-images.githubusercontent.com/2225912/236148401-adc90ff5-c460-458d-81a8-db60b1c2602b.png)

### Expected Behaviour

The number showed on the task progress bar should be `[number of completed jobs] of [total jobs]`.

### Current Behaviour

The number showed on the task progress bar currently is `[(number of completed jobs) * (number of labels)] of [total jobs]`.

### Possible Solution

Not sure about the detailed implementation of getting `completed jobs` so no solution here.

### Context

This bug might confuse my users.

### Your Environment

Including official CVAT ( [https://app.cvat.ai](https://app.cvat.ai) ) and CVAT 2.4.2, 2.4.3

My Environment:
- Git hash commit (`git log -1`): `8a2c23f2c83f01d84f62c5b9c7bcfece2f97169b`
- Docker version `docker version` (e.g. Docker 17.0.05): `20.10.21`
- Are you using Docker Swarm or Kubernetes? `No`
- Operating System and version (e.g. Linux, Windows, MacOS): `Linux (Ubuntu 22.04)`
- Code example or link to GitHub repo or gist to reproduce problem: N/A
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary> (Cannot get log from official CVAT)
    </details>

**Comment by zhiltsov-max** [comment] 2023-05-04 15:03
Duplicate of #6034

**Closed by zhiltsov-max** 2023-05-04 15:03 UTC
